### ISSUE TITLE
Ассистент слышит сам себя при кнопке с server_action.

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#10]
Если в payload от смартапа отдавать кнопки с server_action:
`"suggestions":{"buttons":[{"title":"test","action":{"type":"server_action","server_action":{"action_id":"test"}}}]}`
то ассистент (на адройде 9 точно) начинает слышать сам себя:
![my_voice_little](https://user-images.githubusercontent.com/18159237/97543689-a282a280-19d9-11eb-9489-71a5e5d2e3f2.jpeg)

Чаще всего баг повторяется при следующих действиях:

1. Запускаем смартап.
2. Нажимаем любую кнопку c server_action.
3. Ждём ответа от ассистента, **обязательно дослушать до конца**.
4. Когда микрофон активируется, смартап ждет от вас ответа, снова нажать на кнопку с server_action.

После чего наблюдается, что приложение слышит само себя, т.е. ответ от ассистента распознаётся системой распознавания.

Если кнопки отдаются **без** server_action:
`"suggestions":{"buttons":[{"title":"test","action":{"type":"text","text":"test"}}]}`
то в этом случае такой проблемы нет.

**Comment by Genenko-Svetlana** [comment]
Исправление ожидает влития и тестирования

**Comment by talagaev** [comment]
этот кажется Антон Гимон уже завел тике в нам

**Comment by Genenko-Svetlana** [comment]
Дмитрий, проверьте, пожалуйста, устранена ли проблема.

**Comment by subnetsRU** [comment]
Проблема по прежнему актуальна. Версия Салюта 20.11.0.4145
![5080035b-40b0-480c-a7cb-3e8c895a6477](https://user-images.githubusercontent.com/18159237/98903437-a1b53a80-24c8-11eb-8158-d297461cf561.jpeg)

**Comment by talagaev** [comment]
@sdtestersd не помнишь, почили ли?

**Comment by sdtestersd** [comment]
Исправлено в 20.11.1 МП Салют

**Comment by Genenko-Svetlana** [comment]
@sdtestersd @talagaev эта версия уже вышла?

**Comment by sdtestersd** [comment]
20.11.1 МП Салют уже вышла.

**Comment by subnetsRU** [comment]
Да, приложение обновилось. Повторить проблему не удаётся. Всё работает корректно. Спасибо.
