### ISSUE TITLE
Ошибка -2010 при чтении текста

### ISSUE THREAD

**Issue by danchistyakov** [sberdevices/salute-issues#100]
**Где нашелся баг**: в ассистенте;
**Описание проблемы**: ошибка -2010 при чтении текста;
**Проблема воспроизводится у других пользователей?** Варианты: да;
**Дополнительная информация**: могу предоставить данные по Апу.

**Comment by RulevAnton** [comment]
-2010 Отправка данных в TTS прервалась неизвестной ошибкой.
Что-то некорректное походу в синтез передали. 
Нужен message_id для анализа.

**Comment by danchistyakov** [comment]
message id: 1607523264112
Время 17:14;
MI 9;
Салют.

**Comment by RulevAnton** [comment]
Текст превышает ограничение на кол-во символов в 4 kB.
В присланном текста (там сказка) 4141 байт.

**Comment by danchistyakov** [comment]
Скажите, а можно это ограничение снять?

**Comment by RulevAnton** [comment]
Более правильным выходом будет отправлять несколько отдельных запросов на синтез.

**Comment by danchistyakov** [comment]
У меня просто ап, где ассистент читает сказки, поэтому даже не знаю. Итак массив большой, разбивать его ещё на части это адок.

**Comment by RulevAnton** [comment]
Это неправильно с точки зрения производительности сервиса и безопастности.

**Comment by RulevAnton** [comment]
Нужно помощь какая-то с разделением на отдельные запросы?

**Comment by RulevAnton** [comment]
Или закрываем?

**Comment by danchistyakov** [comment]
В принципе можете закрыть, но в идеале конечно бы повысить)

**Comment by RulevAnton** [comment]
Опять же, повысить не можем, есть вероятность, что этот лимит может даже снизиться.

**Comment by danchistyakov** [comment]
Ок, тогда нету вопросов.
