### ISSUE TITLE
Когда обращаюсь к random Апп ничего не возвращает

### ISSUE THREAD

**Issue by danchistyakov** [sberdevices/salute-issues#101]
**Где нашелся баг**: в ассистенте;
**Описание проблемы**: Когда обращаюсь к random Апп ничего не возвращает;
**Проблема воспроизводится у других пользователей?** не знаю;
**Дополнительная информация**: информация по Апу.

**Comment by danchistyakov** [comment]
Message id: -1;
MI 9;
19:57 MSK;

**Comment by vkycniichai** [comment]
Ранее предоставлялся комментарий по багу. 
"По Вашему кейсу заведен баг на нашей стороне. id: SMSAIDE-1612
Сроки решения, ориентировочно - 10.12.2020, либо 15.12.2020"
Вопрос решается в [90-м тикете](https://github.com/sberdevices/salute-issues/issues/90).
