### ISSUE TITLE
Статус Апа не меняется без очистки кэша

### ISSUE THREAD

**Issue by danchistyakov** [sberdevices/salute-issues#103]
**Где нашелся баг**: в инструментах;
**Описание проблемы**: статус Апа не меняется без очистки кэша и различается дата редактирования;
**Проблема воспроизводится у других пользователей?** не знаю;
**Дополнительная информация**: там где указано: запущено — обычный режим браузера;
там где "Отправлен на модерацию" — инкогнито.
![Screenshot_23](https://user-images.githubusercontent.com/47912489/101881258-35038d80-3ba5-11eb-9801-f1d7f6fff28b.jpg)
![Screenshot_24](https://user-images.githubusercontent.com/47912489/101881268-3a60d800-3ba5-11eb-9ac1-0dc08aa02096.jpg)

**Comment by xoxulin** [comment]
Взяли на анализ. Постараемся решить в Январе 2021.

**Comment by xoxulin** [comment]
Взяли в текущий спринт.

**Comment by Ibragimow** [comment]
https://sbtatlas.sigma.sbrf.ru/jira/browse/SMSADT-3013

**Comment by Genenko-Svetlana** [comment]
@DCStudioProjects  
Есть вариант переключения версий смартапа через дропдаун из навигационной панели.
“Работает” - это опубликованная версия смартап.
Если переключиться на “черновик“, то можно будет без перезагрузки страницы и без очистки кэша посмотреть статус черновика, который может быть в текущий момент “Отправлено на модерацию”.
![Uploading image (6).png…]()
