### ISSUE TITLE
приставка уходит в режим заставки

### ISSUE THREAD

**Issue by kamnevtmb** [sberdevices/salute-issues#105]
**Где нашелся баг**: сбербокс
**Описание проблемы**: играя в игры canvas, конкретно замечено в игре холдем покер, игра шла только через кнопку голосового асистента, приставка включила скринсейвер прямо в момент моего ответа
**Проблема воспроизводится у других пользователей?** как минимум у 2х людей
**Дополнительная информация**: повторное нажатие на кнопку асистента отключает заставку

**Comment by subnetsRU** [comment]
Присоединяюсь.
Тоже такое было один раз, но, если мне не изменяет память, то в chat app.
Видимо в какой-то момент приставка не апдейтит значение timeout

**Comment by Genenko-Svetlana** [comment]
Срок исправления - февраль, 2021

**Comment by talagaev** [comment]
https://sbtatlas.sigma.sbrf.ru/jira/browse/STAROS-5671

**Comment by talagaev** [comment]
@Genenko-Svetlana  тут надо на коллег из строс асайнить

**Comment by Genenko-Svetlana** [comment]
@talagaev на кого?

**Comment by talagaev** [comment]
ну кажется у вас тут никого нет от Старос. Нужны или Саша Дубинин или Антон Дудаков

**Comment by Genenko-Svetlana** [comment]
Срок - февраль, 2021

**Comment by Genenko-Svetlana** [comment]
Перенос срока - 19.03.21

**Comment by subnetsRU** [comment]
Что по тикету ?

**Comment by Genenko-Svetlana** [comment]
@subnetsRU версия 1.70 должна была исправить

**Comment by subnetsRU** [comment]
Ок, понаблюдаю. Спасибо.

**Comment by Genenko-Svetlana** [comment]
@subnetsRU удалось понаблюдать?

**Comment by subnetsRU** [comment]
Лично у меня, проблема не повторялась. А как у автора данного тикета не знаю.

**Comment by Genenko-Svetlana** [comment]
@kamnevtmb  проверьте, пожалуйста
