### ISSUE TITLE
a11y: Доступность интерфейсов SmartMarket

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#107]
**Где пригодится фича**: везде
**Описание фичи**: Добавить в настройки сбер профиля галку "слабовидящий", "слабослышащий" и передавать эту информацию в JSON для смартапа.
**Дополнительная информация**: Вчера получил отзыв от незрячего человека и я задумался.

Задумался над тем, что мы ведь действительно в смартапах рассчитываем на экран и, дабы сократить проговариваемый ассистентом текст, в TTS отправляем что-то типа "<ЭТО> на вашем экране". Но, для незрячих людей это тупик.... Было бы здорово, если в JSON приходил некий флаг и тогда смартап мог бы общаться с таким пользователем так как будто никакого экрана у него нет и запускать chat app, а не canvas app версию смартапа в независимости от поверхности пользователя.

Тоже самое и для слабослышащих. Зачастую мы отправляем в TTS чуть больше того, что выводим на экран, чтобы сэкономить место (например). Подобный флаг в JSON мог бы подсказать нам, что надо наоборот упирать на визуализацию, а не на голос.

Ведь нам по силам сделать такие доработки в своих смартапах и помочь таким людям.

А сейчас слабовидящий человек даже каталог смартапов не может изучить.

**Comment by xoxulin** [comment]
Это системное требование ко всей платформе, которое должно позволять активировать полностью Speech режим всей платформы. Должно быть озвучание расширенное, а именно на любой экнш уметь озвучить что на экране согласно a11y стандарту WAI-ARIA от W3C. Девайсы должны поддерживать, должны поддерживать смартапы, должны поддерживать в том числе пульты – на них должна быть разметка шрифтом Браиля по ключевым кнопкам.

**Comment by subnetsRU** [comment]
Это в идеале.

А для начала было бы хорошо иметь в JSON поля, которые бы подсказывали смартапу на какой из интерфейсов вывода (аудио/визуализация) ему стоит упирать.

Ну и, возможно, создать отдельную категорию приложений в каталоге, которые адаптированы для таких людей.

**Comment by Ibragimow** [comment]
@subnetsRU 
Спасибо за идею. Она обсуждается с прошлого декабря, и мы планируем ее реализовать. Однако назвать сроки я сейчас не готов, задача довольно глобальна, и решение ее выходит за рамки нашей доски. Поэтому я ее закрою и перенесу в Declined. Но прошу понимать правильно, что это не отказ, а напротив - эскалация. И спасибо еще раз!
