### ISSUE TITLE
Интент "Включи на" принудительно завершает смартап

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#11]
Запускаю смартап. 
ASR распознаёт сказанное мной как "включи на" и при этом смартап принудительно завершается, а затем предлагается выбрать голос ассистента.
![enable](https://user-images.githubusercontent.com/18159237/97544914-4f115400-19db-11eb-8ac5-a55d5e2da03c.jpeg)

Это в дополнение к списку, который был озвучен в ТГ @smartapp_studio
* погода
* сколько времени
* установка таймера
* громкость
* переход назад и переход на главный экран
* курс валют
* смена персонажа

**Comment by subnetsRU** [comment]
Обнаружен ещё один интент - «выбрать» ([ТГ](https://t.me/smartapp_studio/3637))

**Comment by Genenko-Svetlana** [comment]
Заведён дефект

**Comment by kuznetsovn** [comment]
7 ноября обновили пром, ошибка ушла

**Comment by subnetsRU** [comment]
Проверил, подтверждаю.
Спасибо.
