### ISSUE TITLE
[SmartApp API] не отображаются карточки если в json есть bubble

### ISSUE THREAD

**Issue by exitoso** [sberdevices/salute-issues#112]
**Где нашелся баг**: SmartApp API
**Описание проблемы**: если в json ответе Салюту передавать одновременно и bubble и card, то карточки не отображаются. Если из json убрать bubble то карточки отображаются.
**Проблема воспроизводится у других пользователей?** не знаю.
**Дополнительная информация**: содержимое payload в котором одновременно есть и bubble и card можно посмотреть в прикрепленном файле
[log1.txt](https://github.com/sberdevices/salute-issues/files/5695378/log1.txt)

**Comment by Genenko-Svetlana** [comment]
Была неверная структура внутри items
{
    "items": [
    {
        "bubble": {
            "text": "Ну, привет!",
            "markdown": false
        },
    },
    {
        "card": {
            "type": "grid_card",
            "columns": 2,
            "item_width": "small",
            "items": [
                {
                    "type": "greeting_grid_item",
                    "paddings": {
                        "top": "5x",
                        "left": "5x",
                        "right": "5x",
                        "bottom": "5x"
                    },
                    "top_text": {
                        "type": "text_cell_view",
                        "text": "1",
                        "typeface": "caption",
                        "text_color": "default"
                    },
                    "bottom_text": {
                        "type": "text_cell_view",
                        "text": "Привет1",
                        "typeface": "body3",
                        "text_color": "default",
                        "max_lines": 1
                    },
                    "actions": [{
                            "text": "Привет1"
                        }
                    ]
                },
                {
                    "type": "greeting_grid_item",
                    "paddings": {
                        "top": "5x",
                        "left": "5x",
                        "right": "5x",
                        "bottom": "5x"
                    },
                    "top_text": {
                        "type": "text_cell_view",
                        "text": "2",
                        "typeface": "caption",
                        "text_color": "default"
                    },
                    "bottom_text": {
                        "type": "text_cell_view",
                        "text": "Привет2",
                        "typeface": "body3",
                        "text_color": "default",
                        "max_lines": 1
                    },
                    "actions": [{
                            "text": "Привет2"
                        }
                    ]
                }
            ]
        }
    }
    ]
}

**Comment by Genenko-Svetlana** [comment]
@exitoso проверяйте и если всё ОК, можно закрыть тикет )))
