### ISSUE TITLE
Q&A 2020

### ISSUE THREAD

**Issue by Ibragimow** [sberdevices/salute-issues#113]
Тикет создан для сбора вопросов для грядущей Q&A-встречи. 
В качестве Assignee ставлю пока себя, мониторит Наталия Макарова.

**Comment by subnetsRU** [comment]
>Q&A-встречи

Речь про сбор в zoom'е ?

**Comment by Ibragimow** [comment]
@subnetsRU да, про Zoom-сессию, которая состоится 28 декабря в 18.00 по Мск.
Приходите!

**Comment by subnetsRU** [comment]
* web версия каталога на сайте будет ?
* как вы смотрите на то, чтобы сделать телеграм бота, который постит в канал новые (только что опубликованные) навыки ?
* будут ли выложены примеры по проектированию Canvas App для СБЕР Салют ?
* когда появится возможность запустить свой Canvas App на Салют, чтобы тестировать ?
* кто-то просматривает assistant-client issues и стоит ли там ожидать ответа ?

**Comment by Hecatoncheir** [comment]
Появятся ли assistant-client и plasma на wasm?

**Comment by Sergeycul** [comment]
1. Есть ли планы по видеоурокам для разработчиков?
2. Когда ждать какое-то упоминание на каталог в СБОЛ в виде рекламного блока?
3. Намекните о новых устройствах в 2021 году, чтобы иметь планы, в какую сторону смотреть с апами?
4. Планируются ли боткэмбы или хакатоны для разработчиков?
5. Приходили ли к Сберу уже коммерческие заказчики (кроме тех, что мы уже давно знаем в каталоге), кого пока попросили подождать аккредитации разработчиков? И планирует ли Сбер отдавать такие заказы на реализацию разработчикам?
6. Порадуйте цифрами динамики, какова сейчас средняя посещаемость апов?
7. Очень нравится реклама про Жорика по ТВ. Может, есть смысл вместе с разработчиками придумать тоже какой-то крутой вирусный ролик для online?

Остальное спрошу на встрече ))

**Comment by and7ey** [comment]
1. Как разработчики портала применяют его в повседневной жизни? Где он стоит (в какой комнате, квартире/доме и т.п.), какие задачи выполняет, какие смартапы используются, как часто используется и т.п.?
2. Планируется ли выпуск какого-либо устройства вообще без экрана и без возможности его подключения (как яндекс.станция мини, например)?
3. Планируется ли запуск SberPlay на портале?
4. Не планируется ли прошивку портала сделать открытой? (=опубликовать ее исходный код)
5. Сможет ли когда-нибудь СберСалют, запущенный на планшете, выполнять все те же функции, что и СберПортал? 

#портал

**Comment by and7ey** [comment]
1. Сейчас инструментов разработчиков стало много - Code, Graph, SmartAPI, AimyLogic - какой из них рекомендуется использовать в каких случаях?
2. (вроде на этот вопрос все-таки не ответили) Планируется ли сделать SberCloud бесплатным для хостинга смартапов на SmartAPI и (что тоже очень важно!) - данных смартапа?
3. Планируется ли создать примера CanvasApp'a, который корректно отображается на всех устройствах - SberPortal, SberBox, приложения Салют? Т.е. пример фронта с адаптивной версткой.

**Comment by Sergeycul** [comment]
Еще немножко уже про Сберпортал.
1. Можно ли Портал приспособить для просмотра в машине, т.е. можно ли его как-то запитать от прикуривателя? Может через переходники?
2. Планируется ли дать возможность отключать экран при прослушивании музыки? Пара дней опыта показала, что если я ставлю музыку ко сну (ночью), то не хочу чтобы экран освещал комнату.
3. Планируется ли использовать портал, как фоторамку, куда можно залить свои фото и показывать на Главной, когда портал в состоянии паузы?
