### ISSUE TITLE
[smartapp share] Добавить возможность запуска смартапа не только с аккаунта разработчика

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#115]
Перерыл все тикеты, но так и не нашёл. Хотя мы об этом точно говорили, но где... вспомнить и найти не смог.

**Где пригодится фича**: в studio
**Описание фичи**: Добавить возможность давать запускать (шарить) смартапы для других аккаунтов ДО модерации. Например дав человеку некую ссылку и если он зайдёт по ней, то у его аккаунта так же появится возможность запускать смартап до его публикации в каталоге.
**Дополнительная информация**: Для чего ? Например: Как тестировать мультиплеер если запустить можно только с одного аккаунта ? Есть мысли попробовать такое исполнить.

P.S. Под "мультиплеер" я подразумеваю не несколько человек перед одним sberbox в одной комнате, а совершенно разных и незнакомых друг с другом людей.

**Comment by ffDowen** [comment]
Добавили такую возможность. [Описание.](https://developer.sberdevices.ru/docs/ru/methodology/testing/smartapp_beta_testing_invitation)

**Comment by subnetsRU** [comment]
Ага, уже протестировали. Всё работает. СПАСИБО !
