### ISSUE TITLE
Блок «Ввод числа» в некоторых случаях не выдает запасное сообщение об ошибке.

### ISSUE THREAD

**Issue by Sergeycul** [sberdevices/salute-issues#116]
ГРАФ. Если в апе используется блок «Ввод числа» и сказать в ап не число, а например «много» или другое слово без численного значения, то не выводится запасное сообщение об ошибке из этого блока.

**Comment by Genenko-Svetlana** [comment]
Срок реализации - 31.03.2021. Пока тикет закрываем и переносим в отложенные.

**Comment by Genenko-Svetlana** [comment]
Возвращаем в работу.

**Comment by Genenko-Svetlana** [comment]
@Sergeycul исправлено, проверяйте, пожалуйста
