### ISSUE TITLE
Какие данные о пользователе нужны вашим смартапам?

### ISSUE THREAD

**Issue by oblomil** [sberdevices/salute-issues#117]
Как и обещали, исследуем тему персональных данных. Ответьте, пожалуйста, на два вопроса в комментариях:

1. Какие обобщенные, не персонифицированные данные пригодились бы для вашего смартапа?
2. Какие интересы или предпочтения пользователей пригодились бы для вашего смартапа?

**Comment by Sergeycul** [comment]
1. Естественно, какой ассистент выбран, чтобы делать под «ТЫ/ВЫ»; сколько ранее уже сыграл раз игрок в ап; текущее время захода в ап.
2. Игрок мужчина/женщина; возраст; какая у пользователя популярная рубрика каталога по апам;  устройство, с которого играет пользователь и платформа; разрешение экрана и в идеале ориентация экрана.

**Comment by snyuryev** [comment]
Таймзона (вроде бы уже есть)
Город
Страна (если будут пользователи из других стран)
Пол
Возраст
Имя (не полное ФИО, а хотя бы имя - всегда приятнее когда приложение обращается по имени)

**Comment by subnetsRU** [comment]
* город
* пол
* возраст

Желательно, чтобы поля "пол" и "возраст" вычислялись в онлайне, т.е. зависели от того кто именно сейчас общается с ассистентом, а не просто брались из данных аккаунта.

**Comment by oblomil** [comment]
Всем спасибо, опрос закрываем.
