### ISSUE TITLE
Синтез слова "все"

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#118]
**Где нашелся баг**: во всех ассистентах
**Описание проблемы**: Ассистенты произносят "все" как "всЁ"
**Проблема воспроизводится у других пользователей?** Да.
**Дополнительная информация**: Текст для TTS: "Либо можно заменить вопрос, если не хочется угадывать в
се варианты ответов."

**Comment by RulevAnton** [comment]
Бага ТТС, завёл TTSQA-1420, после НГ должно попасть в один из первых релизов.

**Comment by Genenko-Svetlana** [comment]
Срок 31.01.2021

**Comment by subnetsRU** [comment]
А может есть какой-то лайфхак с ssml ?

**Comment by RulevAnton** [comment]
такая фишка будет в сл. релизе в январе

**Comment by RulevAnton** [comment]
но такой лафхак будет только у нас внутри, будет легче фиксить эти баги.

**Comment by RulevAnton** [comment]
Исправлено, устеновлено в прод.
