### ISSUE TITLE
Полнота каталога

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#119]
Тут обнаружился баг в каталоге (сказали уже исправлен) и попутно выяснилось, похоже, что войдя в конкретную категорию каталога (например "игры") оказывается каталог отображается не полным и сделано это специально.

Хочу спросить, так ли это ? А как же тогда посмотреть весь каталог ?

**Comment by Avalpetrova** [comment]
Нет, не так. На странице категории отображаются все смартапы из данной категории. На данный момент часть не отображается и это баг. В ближайшее время будет хотфикс.

**Comment by subnetsRU** [comment]
Ясно. Тогда просьба сменить метку с "question" на "bug" и ждём фикса.

**Comment by subnetsRU** [comment]
А уже понятны какие-то сроки когда должен выйти фикс ?

**Comment by subnetsRU** [comment]
А ответ будет ?

**Comment by subnetsRU** [comment]
Выяснил в телеграм. Всё исправлено.
