### ISSUE TITLE
Очень маленький timeout для chatapp смартапов на сбербокс.

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#12]
Текущий таймаут на сбербокс 40 секунд.
Если вы не взаимодействуете со смартапом дольше этого времени, то сбербокс возвращается на главный экран.
Если ответ от смартапа идёт дольше чем это время (_например зачитываются правила игры_), то приставка уже на главном экране, а зачитывание текста продолжается.

Необходимо существенно увеличить таймаут. 
Ведь получается, что у человека нет времени не то, чтобы просто отвлечься на что-то и вернуться к смартапу, но и толком подумать на ответом, например в логической игре.
Смартап будет принудительно завершен.

**Comment by Genenko-Svetlana** [comment]
Таймаут увеличен до 90 сек. 
Планируем делать фичу, чтобы навык сам мог переопределить для себя параметр бездействия.

**Comment by subnetsRU** [comment]
Спасибо. Вечером проверю.

**Comment by subnetsRU** [comment]
Протестировал.
На моём сбербокс всё те же 40к секунд.
Подскажите, это надо ждать апдейта прошивки сбербокса ? Или это ещё реализовано, но не выпущено в продакшн ?

**Comment by Genenko-Svetlana** [comment]
Разработчики подтвердили, что это уже реализовано. Сможете мне выслать видео в Telegram?

**Comment by subnetsRU** [comment]
Да, конечно, сейчас отправлю.

**Comment by Genenko-Svetlana** [comment]
Задачу вновь открыла. Ждем решения после 10.11

**Comment by talagaev** [comment]
у меня в 1.65 уже все ок)

**Comment by subnetsRU** [comment]
1.65 я так понимаю версия прошивки бокса.

Буду дома гляну какая у меня и проверю.

**Comment by Genenko-Svetlana** [comment]
Проверьте, пожалуйста, ждем обратную связь

**Comment by subnetsRU** [comment]
У меня всё по прежнему, т.к. прошивка бокса 1.63.11
Соответственно вопрос: а когда 1.65 дойдёт до простых смертных ?

**Comment by talagaev** [comment]
на след неделе начнет раскатываться

**Comment by subnetsRU** [comment]
@talagaev, сегодня уже четверг, но до меня обнова всё ещё не долетела.

Скажите, поменялись планы ? Или обнова разливается, но до меня просто ещё очередь не дошла ?

**Comment by talagaev** [comment]
@subnetsRU  проверьте, у вас обновилась прошивка до 1.65?

**Comment by subnetsRU** [comment]
Через пару часов буду дома - посмотрю.

**Comment by subnetsRU** [comment]
Жена оказалась дома, посмотрела. Да, обновилась до 1.65.21.

А это только меня накатили или всех будут ? Т.к. в чате пишут, что у них старая.

**Comment by talagaev** [comment]
открыли на всех, как правило, ночью девайсы сами обновляются постепенно

**Comment by subnetsRU** [comment]
Проверил. Работает. Спасибо.

**Comment by Genenko-Svetlana** [comment]
Увеличим в 1.75 до 150 сек

**Comment by subnetsRU** [comment]
Тут вопрос не совсем так уже поставлен ведь. Речь шла про то, что смартап может переопределить таймаут.

Но это уже другой тикет: https://github.com/sberdevices/salute-issues/issues/31
