### ISSUE TITLE
Увеличить максимальное количество знаков в поле Инструкции для тестирования

### ISSUE THREAD

**Issue by snyuryev** [sberdevices/salute-issues#120]
**Где пригодится фича**: smartapp студия
**Описание фичи**: поможет предоставлять полную информацию о приложении для модераторов
**Дополнительная информация**: сейчас лимит 2000 символов

**Comment by xoxulin** [comment]
Сколько нужно символов для комфортного описания инструкции?

**Comment by Ibragimow** [comment]
Прогресс будет тут: https://sbtatlas.sigma.sbrf.ru/jira/browse/SMSADT-3014

**Comment by snyuryev** [comment]
@xoxulin может быть увеличить до 5000 знаков? 

(у меня было в последний раз чуть меньше 3000 знаков - и это просто описание голосовых команд и экранов в приложении)

**Comment by Genenko-Svetlana** [comment]
@xoxulin

**Comment by Genenko-Svetlana** [comment]
@snyuryev Увеличено максимальное количество знаков поля “Инструкции для тестирования” до 4000 символов

**Comment by snyuryev** [comment]
спасибо!
