### ISSUE TITLE
В приложении Сбер Салют нет возможности запустить черновик канвас апп

### ISSUE THREAD

**Issue by snyuryev** [sberdevices/salute-issues#121]
**Где нашелся баг**: приложение Сбер Салют
**Описание проблемы**:  нет возможности запустить черновик канвас апп
**Проблема воспроизводится у других пользователей?** не знаю
**Дополнительная информация**: при запуске слышно ответ ассистента, но канвас апп не открывается

платформа iOS, версия 20.12.2002
опубликованное приложение запускается (или черновик опубликованного приложения)

**Comment by Genenko-Svetlana** [comment]
@snyuryev  Сергей, добрый день!
Нужна фактура: шаги для воспроизведения проблемы, скрины, видео.
Спасибо.

**Comment by Genenko-Svetlana** [comment]
Завели баг. Срок реализации - 31.01.2021
Можно использовать следующее решение: Передать данные в смартап на старте. Без данных пока не работает в iOS.
Если отправить smart_app_data , то ап запустится.

**Comment by Genenko-Svetlana** [comment]
@snyuryev Сергей, добрый день! Попробуйте убрать smart_app_data при запуске смартапа.

**Comment by snyuryev** [comment]
@Genenko-Svetlana Пока без изменений. Без smart_app_data в первом респонсе приложение на iOS не запускается.

**Comment by Genenko-Svetlana** [comment]
Уточнение по сроку реализации - февраль, 2021

**Comment by talagaev** [comment]
фикс в 21.3.1

**Comment by Genenko-Svetlana** [comment]
Когда эта версия выйдет в пром?

**Comment by Genenko-Svetlana** [comment]
@snyuryev  исправление попало в релиз 21.2.1. Проверьте, пожалуйста.

**Comment by snyuryev** [comment]
@Genenko-Svetlana все работает! спасибо!
