### ISSUE TITLE
Не работают глобальные интенты при вводе числа

### ISSUE THREAD

**Issue by danchistyakov** [sberdevices/salute-issues#123]
**Где нашелся баг**: в ассистенте;
**Описание проблемы**: не работают глобальные интенты при вводе числа;
**Проблема воспроизводится у других пользователей?** не знаю;
**Дополнительная информация**: высвечивается текст, который говорит о неправильном диапазоне ответа.

**Comment by Genenko-Svetlana** [comment]
Срок исправления - 30.04.2021. Пока тикет закрываем и переносим в отложенные.

**Comment by Genenko-Svetlana** [comment]
Возвращаем в работу

**Comment by Genenko-Svetlana** [comment]
@danchistyakov исправлено, проверяйте, пожалуйста
