### ISSUE TITLE
[studio] Добавить иконки поверхностей, на которых опубликован смартап

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#125]
**Где пригодится фича**: в studio
**Описание фичи**: Предлагаю добавить, на экране опубликованных смартапов, информацию на каких поверхностях опубликован смартап.
**Дополнительная информация**: Вот примерно так:
![studio](https://user-images.githubusercontent.com/18159237/102984937-68d4a080-451f-11eb-98ac-bc918ceb3acb.png)
SB - SberBox
SP - SberPortal
СО - Сбербанк Онлайн
СС - Сбер Салют

Можно буквы на иконки девайсов и приложений заменить. Если опубликован на этой поверхности, то появляется иконка этой поверхности. Так не надо будет каждый раз проваливаться внутрь, чтобы узнать эту информацию.

**Comment by Ilchenk** [comment]
Добрый день!

Новый дизайн карточки смартапа будет реализован в 1 квартале 2021 года. Пока временно закрываем тикет и переносим в отложенные.

**Comment by Genenko-Svetlana** [comment]
Возвращаем в работу.

**Comment by Genenko-Svetlana** [comment]
@filomat уточни срок, пжл.

**Comment by Genenko-Svetlana** [comment]
Перенос срока на 3-4 квартал 2021.
Тикет временно закрываем и переносим в отложенные задачи.

**Comment by Genenko-Svetlana** [comment]
Сейчас появляется всё больше и больше поверхностей и проекты - это не только смартапы. Разместить все поверхности красиво не получится.
Поэтому, как вариант, будем смотреть в сторону отображения категорий “Устройства с экраном” и “Устройства без экрана”.

Пока откладываем задачу.
