### ISSUE TITLE
[SberPortal] Добавить возможность использовать жесты

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#127]
**Где пригодится фича**: в SberPortal
**Описание фичи**: Дать API к получению и управлению жестами для canvas app.
**Дополнительная информация**: Как сейчас получить жест пользователя ? Как обучить своим жестам ? Например жест смахивание вправо или влево. Ну и так далее.

То есть представим себе Beat Dancer, но вместо игры на заднем фоне canvas app, который так же может реагировать на жесты пользователя. Много чего можно намутить таким функционалом.

Хотелось бы понимания ваших планов на этот счёт.

**Comment by NikolayPakhomov** [comment]
Добрый день!

Такой функционал и его описание планируем реализовать в 1 квартале 2021 года. Тикет временно закрываем и переносим в отложенные.

**Comment by subnetsRU** [comment]
Очень надеюсь, что под "такой функционал" мы понимаем одно и тоже.

А так, первый квартал это здорово ! Буду ждать.

**Comment by awinogradov** [comment]
Точно одно. Управление жестами будет приходить событиями через AssistantClient

**Comment by subnetsRU** [comment]
Хотелось бы не только получать жесты, которым обучен сберпортал, но и своим.

Например сведение рук и их разведение смартап мог бы сам забиндить как увеличение и уменьшение (картинки/графика/и т.д.)

**Comment by awinogradov** [comment]
Это сильно другое и сильно сложнее. Ибо распознавание построено на обучаемых моделях. Набор доступных жестов будет расти. Но добавления кастомных из смартапа мы пока не рассматриваем.

**Comment by subnetsRU** [comment]
Да, я прекрасно понимаю, что это всё не просто. Потому и удивился сроку 1 квартал 2021 и решил уточнить.

Теперь понимаю, что это срок получения пальца вверх/вниз, Vиктори и ладонь. Хорошо конечно, но мало :)

Хотелось бы почувствовать себя "железным человеком", который управляет компьютером руками. Уменьшает, увеличивает, смахивает и пролистывает. Уверен, что именно так и будет в скором будущем "в каждом утюге".

**Comment by awinogradov** [comment]
И заюзать Джой как Джарвиса, понимаю тебя)

**Comment by subnetsRU** [comment]
Ага, в точку !

**Comment by Genenko-Svetlana** [comment]
Возвращаем в работу.

**Comment by subnetsRU** [comment]
> Такой функционал и его описание планируем реализовать в 1 квартале 2021 года.

Всё идёт по плану ? Просто уже появился запрос на смартап с использованием жестов.

**Comment by Genenko-Svetlana** [comment]
@subnetsRU сроки сдвигаются на 2-3 квартал 2021 :-(

**Comment by Genenko-Svetlana** [comment]
Тикет временно закрываем и переносим в отложенные задачи.

**Comment by Genenko-Svetlana** [comment]
3 квартал 2021

**Comment by Genenko-Svetlana** [comment]
Перенос срока реализации на 4 квартал 2021

**Comment by Genenko-Svetlana** [comment]
Перенос на 4 квартал 2022 года. Пока переносим в отложенные задачи
