### ISSUE TITLE
Добавить timezone пользователя в JSON

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#13]
В смартапах хотелось бы получать timezone пользователя, чтобы, как пример, правильно с ним здороваться.
Сейчас получается смартап говорит "Доброе утро", а у пользователя уже "Добрый вечер".

**Comment by christinadomanskaya** [comment]
В работе. Ожидаемый срок - через неделю.

**Comment by subnetsRU** [comment]
Не поверил своим глазам, но стало приходить:
```
        "meta": {
            "current_app": [],
            "time": {
                "timestamp": 1605729366890,
                "timezone_id": "Europe\/Moscow",
                "timezone_offset_sec": 10800
            }
        },
```
Это уже "прибито гвоздиками" или ещё может поменяться ? Т.е. можно начинать использовать ?
И ещё вопрос, а чего `timestamp` такой длинный ?
А в RUN_APP `time`отсутствует, только в MESSAGE_TO_SKILL почему-то.

**Comment by Lytkini** [comment]
Объект `meta.time` описан в документации:
https://developer.sberdevices.ru/docs/ru/developer_tools/amp/smartappapi_description_and_guide.md#содержимое-payload-для-сообщения-с-типом-message-to-skill

**Comment by subnetsRU** [comment]
Большое спасибо, то что надо.
