### ISSUE TITLE
В канвас апп запущенных в приложении Сбер Салют iOS не приходит AssistantCharacterType

### ISSUE THREAD

**Issue by snyuryev** [sberdevices/salute-issues#130]
**Где нашелся баг**: Сбер Салют iOS
**Описание проблемы**: Не приходит AssistantCharacterType
**Проблема воспроизводится у других пользователей?**  не знаю.
**Дополнительная информация**: Сбер Салют iOS 20.12.3002
AssistantCharacterType приходит локально и на сбербокс

**Comment by Turanchoks** [comment]
@snyuryev Привет! Подскажи, не приходит в appInitialData? Сейчас в ios не дублируются данные в onData

**Comment by snyuryev** [comment]
@Turanchoks привет! пока не проверял что в appInitialData, использовал только onData.
Проверю - вернусь с ответом

**Comment by snyuryev** [comment]
да, все приходит.
только надо на событии onStart вызывать getInitialData()

**Comment by sasha-tlt** [comment]
@snyuryev, в версии assistant-client@2.7.0 все платформы работают одинаково - нужно использовать getInitialData() для получения текущего персонажа и других инициализационных команд; дублирование команд исправлено. Данное решение позволяет получать инициализационные команды не дожидаясь события 'start'.

**Comment by Genenko-Svetlana** [comment]
@snyuryev  подтвердите, пжл, выполнение.

**Comment by snyuryev** [comment]
да, через getInitialData() работает
