### ISSUE TITLE
Апп прошел модерацию, но в прод выехала старая версия?

### ISSUE THREAD

**Issue by gotzmann** [sberdevices/salute-issues#131]
**Где нашелся баг**: похоже на баг в системе деплоя

**Описание проблемы**: мой чат-апп прошел модерацию, но при тестировании прод-версии различными пользователями, им отвечает какая-то старая версия аппа, а не новая (которая прошла модерацию)

**Проблема воспроизводится у других пользователей?** Да, при тестировании чат-аппа через приложение Салют

**Дополнительная информация**: идентификатор приложения SBER_NLP_2-81743430. Если пользователь задает непонятный вопрос, апп должен ответить "Последний вопрос не очень ясен" (так прописано в актуальной версии сценария, прошедшего модерацию). Вместо этого отвечает "Не понял этот вопрос" (так было в старых версиях, не прошедших модерацию).

**Comment by Genenko-Svetlana** [comment]
@gotzmann Сергей, добрый день! Несколько уточняющих вопросов:
1. О каком навыке идет речь?
2. Идентификатор приложения SBER_NLP_2-81743430 - что это за идентификатор?

**Comment by Genenko-Svetlana** [comment]
Срок реализации - 31.12.2020

**Comment by eprigarov** [comment]
@gotzmann Сергей, добрый день. 
Изучали сегодня проблему. Наиболее вероятный результат: После того как навык прошёл модерацию Вы не нажали кнопку "Опубликовать" в Кабинете Разработчика. Из-за этого новая версия навыка не была опубликована. По этой причине Вы наблюдаете в ПРОМе старую версию навыка.
Пока других причин для подобного поведения мы не можем найти.

**Comment by Genenko-Svetlana** [comment]
@gotzmann проверьте, пожалуйста.

**Comment by Genenko-Svetlana** [comment]
@gotzmann  в связи с отсутствием комментариев тикет закрываем.
