### ISSUE TITLE
[canvas] Убрать градиент вверху и внизу экрана в мобильном приложении Салют.

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#132]
В [ТГ обсудили](https://t.me/smartapp_studio/9647), а тикет так и не создали... Исправляю этот просчёт.

Желательно удалить градиент в мобильном приложении вверху экрана (это на android, а на ios его нет) и внизу экрана (это есть и на android, и на ios). Так как это мешает читать текст, а так же и без того маленький экран становится ещё меньше.

**Comment by Ibragimow** [comment]
Обсуждаем тут: https://sbtatlas.sigma.sbrf.ru/jira/browse/SDDESIGN-1430

**Comment by Genenko-Svetlana** [comment]
Скорректирован срок реализации - 3 квартал 2021.
Тикет временно закрываем и переносим в отложенные задачи.

**Comment by Genenko-Svetlana** [comment]
Новая версия Салют вышла 08.10. Проверяйте, пожалуйста.

**Comment by subnetsRU** [comment]
Стало заметно лучше. 

Вверху его нет совсем - очень хорошо, а внизу чутка всё же есть.
![image](https://user-images.githubusercontent.com/18159237/136755835-f35fb3c7-e83e-4cda-bea2-1a0cee4041b8.png)
Но наверно это уже не критично.

**Comment by Genenko-Svetlana** [comment]
Не критично ) 
@subnetsRU спасибо, тикет закрываю.
