### ISSUE TITLE
[canvas] В Сбер Салют iOS не доходит smart_app_data при первом запуске.

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#133]
**Где нашелся баг**: Сбер Салют iOS
**Описание проблемы**: Пользователь запускает canvas апп. Апп отправляет smart_app_data, в котором есть текст для вывода на экран, но до пользователя smart_app_data не доходит, т.к. текста у него на экране просто нет. Только со вторым сообщением, если нажать кнопку (саджест), smart_app_data начинает доезжать и всё идёт как надо.
**Проблема воспроизводится у других пользователей?** Да.
**Дополнительная информация**: 

На андройде этой проблемы нет. Вот скрин первого запуска аппа:
![image](https://user-images.githubusercontent.com/18159237/104191286-5ff43200-542e-11eb-97d8-29ae2bd928ea.png)

А на:
```
        "device": {
            "platformType": "IOS",
            "platformVersion": "14.3",
            "surface": "COMPANION",
            "surfaceVersion": "20.12.3100",
```
проблема есть. Вот скрин первого запуска аппа:
![image](https://user-images.githubusercontent.com/18159237/104191104-1c99c380-542e-11eb-8384-1f44bbe0c492.png)

Очень похоже, что связано с тикетом #130.

P.S. Если это важно, то в кач-ве assistant-client используется https://unpkg.com/@sberdevices/assistant-client@2.4.0/umd/assistant.min.js

**Comment by snyuryev** [comment]
Столкнулся с аналогичной проблемой.

**Comment by Genenko-Svetlana** [comment]
@Turanchoks

**Comment by Genenko-Svetlana** [comment]
Команды, которые приходят на открытии смартаппа помещаются в поле appInitialData , его можно дернуть из getInitialData AssistantClientSDK https://github.com/sberdevices/assistant-client#getinitialdata-assistantcommands,
все последующие команды для работающего смартаппа приходят в onData , метод также есть AssistantClientSDK https://github.com/sberdevices/assistant-client#ondata-cb-data-assistantcharactercommand--assist[…]antsmartapperror--assistantsmartappcommand---void
На Андроиде команды на старте дублируются из appInitialData в onData , поэтому там не стрельнуло

**Comment by snyuryev** [comment]
@Genenko-Svetlana стоит ожидать что на iOS будет аналогичное поведение - добавлено дублирование данных в onData?

**Comment by Genenko-Svetlana** [comment]
Мы в AssistantClient будем отфильтровывать эти сообщения из onData. Нивелируем эту разницу на уровне AssistantClient

**Comment by subnetsRU** [comment]
Действительно есть такое дело:
![image](https://user-images.githubusercontent.com/18159237/104299086-d1d38680-54d5-11eb-90ea-5ba4ff51dbea.png)

Спасибо.

Но присоединяюсь к вопросу Сергея. Очень желательно, чтобы как в армии - принцип единообразие :)

**Comment by subnetsRU** [comment]
А можете поделиться как правильно использовать getInitialData ?

Проблема в том, что это ф-ция:
```
assistant.getInitialData
ƒ (){return window.appInitialData}
```
Вызываем:
```
var assistant = assistant.createAssistant({ getState: () => state });
var initialData = assistant.getInitialData();
console.debug('initialData.len',initialData.length);
```
console.debug напечатает 0, т.к. в  initialData пустота. Массивом с данными он станет чуть позже (чему равен этот "позже" неведомо). Я так понимаю данные туда доезжают по мере поступления. 

Мне нужно, чтобы как только там появится "smart_app_data" сделать что-то типа emit.event `assistant.on('data'...` чтобы всё быль единообразно и для андройда и для айфона.

P.S. А пока ничего умнее я не придумал:
```
        var waitInitData = function(){
            console.debug('initialData',typeof initialData,initialData);
            if (typeof initialData === "object"){
                if (initialData.length > 0){
                    console.log('obj',initialData.length);
                    for (let i=0; i < initialData.length; i++){
                        console.log('initialData[i]',initialData[i]);
                    }
                    if (initialData.length < 3){
                             initTimer = setTimeout(waitInitData,100);
                    }
                }else{
                    initTimer = setTimeout(waitInitData,100);
                }
            }else{
                initTimer = setTimeout(waitInitData,100);
            }
        }
        var initialData = assistant.getInitialData();
        var initTimer = setTimeout(waitInitData,1000);
        setTimeout(function(){clearTimeout(initTimer);},4000);
```
Так да, работает:
```
initialData object []
index.html?devel=true:134 initialData object []
index.html?devel=true:134 initialData object []
index.html?devel=true:134 initialData object []
index.html?devel=true:134 initialData object []
index.html?devel=true:134 initialData object []
index.html?devel=true:134 initialData object []
index.html?devel=true:134 initialData object []
index.html?devel=true:134 initialData object []
index.html?devel=true:134 initialData object []
index.html?devel=true:134 initialData object []
index.html?devel=true:134 initialData object []
index.html?devel=true:134 initialData object [{…}]
index.html?devel=true:138 obj 1
index.html?devel=true:140 initialData[i] {type: "insets", insets: {…}}
index.html?devel=true:134 initialData object [{…}]
index.html?devel=true:138 obj 1
index.html?devel=true:140 initialData[i] {type: "insets", insets: {…}}
index.html?devel=true:134 initialData object [{…}]
index.html?devel=true:138 obj 1
index.html?devel=true:140 initialData[i] {type: "insets", insets: {…}}
index.html?devel=true:134 initialData object [{…}]
index.html?devel=true:138 obj 1
index.html?devel=true:140 initialData[i] {type: "insets", insets: {…}}
index.html?devel=true:134 initialData object [{…}]
index.html?devel=true:138 obj 1
index.html?devel=true:140 initialData[i] {type: "insets", insets: {…}}
index.html?devel=true:134 initialData object [{…}]
index.html?devel=true:138 obj 1
index.html?devel=true:140 initialData[i] {type: "insets", insets: {…}}
index.html?devel=true:134 initialData object [{…}]
index.html?devel=true:138 obj 1
index.html?devel=true:140 initialData[i] {type: "insets", insets: {…}}
index.html?devel=true:134 initialData object [{…}]
index.html?devel=true:138 obj 1
index.html?devel=true:140 initialData[i] {type: "insets", insets: {…}}
index.html?devel=true:138 obj 3
index.html?devel=true:140 initialData[i] {type: "insets", insets: {…}}
index.html?devel=true:140 initialData[i] {type: "character", character: {…}}
index.html?devel=true:140 initialData[i] {type: "smart_app_data", smart_app_data: {…}, sdkMeta: {…}}
```
Но как по мне это какой-то дичайший костыль.

**Comment by snyuryev** [comment]
отмечу еще что на Сбербоксе и Сберпортале работает отлично через onData, как и на андроид - отличается только iOS.

**Comment by Turanchoks** [comment]
@subnetsRU @snyuryev Ребята, привет!
Мы проверили, и appInitialData должна появляться до выполнения и парсинга. Можете прислать пример странички простой, с которой не работает? 🙏

**Comment by subnetsRU** [comment]
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>test</title>
    <script crossorigin src="https://unpkg.com/react@17/umd/react.production.min.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js"></script>
    <script src="https://unpkg.com/@sberdevices/assistant-client@2.6.0/umd/assistant.min.js"></script>
</head>
<body>
<div id="root">
</div>
<script type="text/javascript">
var token = 'TOKEN HERE';
var initPhrase = 'запусти ХХХХ';
var state = { };
var assistant = assistant.createSmartappDebugger({ getState: () => state, token, initPhrase })
var initialData = assistant.getInitialData();
console.debug('initialData.len',initialData.length);
assistant.on('data', (command) => {
 console.info('got command',command);
});
</script>
</body>
</html>
```

**Comment by Turanchoks** [comment]
@subnetsRU Вы ведь на девайсе тестируете не с createSmartappDebugger? Он подходит только для локальной разработки.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>test</title>
    <script
      crossorigin
      src="https://unpkg.com/react@17/umd/react.production.min.js"
    ></script>
    <script
      crossorigin
      src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js"
    ></script>
    <script src="https://unpkg.com/@sberdevices/assistant-client@2.6.0/umd/assistant.min.js"></script>
  </head>
  <body>
    <div id="root"></div>
    <script type="text/javascript">
      var a = assistant.createAssistant({ getState: () => {} });
      var initialData = a.getInitialData();
      console.debug("initialData from assistant.getInitialData", initialData);
      a.on("data", (command) => {
        console.info("got command", command);
      });
    </script>
  </body>
</html>
```

вот такой код на нашем канвасе на айфоне в консоль выводит заполненный массив с initialData.

И лучше не переобъявлять глобальную переменную с ассистентом :)

**Comment by subnetsRU** [comment]
>Вы ведь на девайсе тестируете не с createSmartappDebugger?

Конечно нет. На девайсе запускается assistant.createAssistant.

>вот такой код на нашем канвасе на айфоне в консоль выводит заполненный массив с initialData

Так я и не говорю, что он не выводит. [Он выводит](https://github.com/sberdevices/salute-issues/issues/133#issuecomment-758544691), но данные в initialData появляются не сразу, а постепенно, что я и описал [тут](https://github.com/sberdevices/salute-issues/issues/133#issuecomment-758623083). Этот нюанс вылез как раз при попытке использовать то, что типа должно быть в initialData.

Хорошо, добавьте вот такой код и посмотрите в консоль:
```
var initTimer = setInterval(function(){console.debug('initialData',initialData);},100);
setTimeout(function(){clearTimeout(initTimer);},4000);
```
![2021-01-14_10-29-04](https://user-images.githubusercontent.com/18159237/104558294-a5457900-5653-11eb-916c-cfab705e544b.png)

>И лучше не переобъявлять глобальную переменную с ассистентом :)

Ну я не выдумывал и использовал [этот пример](https://github.com/sberdevices/assistant-client/blob/main/examples/umd-example/index.html):
```
var assistant = assistant.createSmartappDebugger({ getState: () => state, token, initPhrase });
```

**Comment by Turanchoks** [comment]
@subnetsRU Спасибо за ответ! В нашем примере поправим, это мы, конечно, фигню написали.
То, что заполняется не сразу – проблема с текущей прошивкой на андройде. Судя по тому, что скриншот из хрома, я полагаю, что все же вы смотрите не iOS. В андройде это скоро поправится

**Comment by subnetsRU** [comment]
На андройде как раз проблем нет, проблема именно на iOS. Вы опечатались ?

Да, я смотрю в браузере на компе, т.к. удобнее разбираться. Суть в том, что когда я добавил обработку initialData, то на iOS ничего не изменилось. Вот я и полез разбираться и обнаружил, то о чём писал выше.

На iOS заработало только тогда когда я применил [этот костыль](https://github.com/sberdevices/salute-issues/issues/133#issuecomment-758623083).

**Comment by Turanchoks** [comment]
Да, костыль ваш абсолютно понятен, у нас даже висит PR в assistant-client, подобное сделать для поддержки обратной совместимости, только для андройда :). Мы тестили на нашем аппе и ваш пример на iOS и appInitialData инджектится верно.

Я не понял, как и что конкретно вы смотрите через хром? Это апп, запущенный где?

**Comment by subnetsRU** [comment]
В адройде как раз всё верно работает. Благодаря [этому](https://github.com/sberdevices/salute-issues/issues/133#issuecomment-758527271):
>На Андроиде команды на старте дублируются из appInitialData в onData

и на нём срабатывает `a.on('data', (command)...` и всё замечательно, т.к. отрабатывается сразу же как появились данные в InitialData. Вот надо сделать тоже самое, но для iOS.

>Это апп, запущенный где?

Это тестовая среда. Апп запущенный в браузере, который соединен с платформой через assistant.createSmartappDebugger.

**Comment by snyuryev** [comment]
@Turanchoks я бы еще раз хотел сказать, что не только на андроиде дублируется onData, но и на сбербоксе, портале и локально при отладке в браузере (везде кроме iOS). Нет планов сделать дублирование из appInitialData в onData для iOS?

**Comment by Turanchoks** [comment]
@snyuryev Андроид везде один – на сбербоксе, портале и мобилах. Дублирование в onData – это наша техническая ошибка, iOS делался позже и ее воспроизводить не стал. 

Архитектурно правильно использовать appInitialData – он доступен до инициализации вашего приложения, поэтому можно сразу отрисовывать то, что нужно. Локально с appInitialData сейчас тоже действительно косяк, потому что ассистент локально запускается в том же контексте, что и приложение. Поэтому нельзя никак это сделать локально так же, как на нативных платформах. Строго говоря, единственное место, где сейчас работает верно – это iOS. Я на днях подумаю и вернусь с решением, как мы это будем решать.

**Comment by snyuryev** [comment]
@Turanchoks хорошо, спасибо.

**Comment by sasha-tlt** [comment]
@subnetsRU, в версии assistant-client@2.7.0 все платформы работают одинаково - нужно использовать getInitialData() для получения текущего персонажа и других инициализационных команд; дублирование команд исправлено. Данное решение позволяет получать инициализационные команды не дожидаясь события 'start'.

**Comment by subnetsRU** [comment]
`getInitialData()` сразу вернёт данные ? [такого поведения](https://github.com/sberdevices/salute-issues/issues/133#issuecomment-759976696) больше быть не должно ?

**Comment by sasha-tlt** [comment]
> `getInitialData()` сразу вернёт данные ? [такого поведения](https://github.com/sberdevices/salute-issues/issues/133#issuecomment-759976696) больше быть не должно ?

Если ничего не вернет - придет в on('data').  В будущем такое поведение будет исправлено и команды всегда будут в initialData

**Comment by Genenko-Svetlana** [comment]
@subnetsRU можно закрывать?
