### ISSUE TITLE
[canvas] Отсутствует виртуальная клавиатура

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#134]
**Где нашелся баг**: Салют
**Описание проблемы**: При запуске canvas иконка виртуальной клавиатуры с панели ассистента исчезает и клавиатура становится недоступной.
**Проблема воспроизводится у других пользователей?** да
**Дополнительная информация**: Например на сберпортале иконка виртуальной клавиатуры внутри canvas доступна и работает.

**Comment by Genenko-Svetlana** [comment]
Сознательно убрали. 
Если добавить клавиатуру в канвас, то по нажатию она выедет и у пользователя появится возможность написать "в никуда" свой текстовый запрос, а он даже его не увидит, т.к. чата нет же на экране. 

В SberPortal - другая история, там оказалась больше потребность у пользователей ввести что-то в клавиатуре - например, при включении музыки редкого исполнителя, где asr не распознает.
А в моб канвасе - важно в контесте ввода, например, адреса, давать клавиатуру. а не просто на экране с выбором попкорна.

**Comment by subnetsRU** [comment]
Если честно не совсем понял.

Открываем в Салют чат с ассистентом. Тыкаем в клавиатуру, видим:
![image](https://user-images.githubusercontent.com/18159237/104302913-6e982300-54da-11eb-8b49-99ea4d07d6f5.png)
Да, клавиатура съела часть экрана (выехала поверх диалога с ассистентом), но и что с того ? Ведь всё что я введу отправится в ассистента. Точно так же как я бы сказал это голосом.

Открываем chat app. Тыкаем в клавиатуру, видим тоже самое:
![image](https://user-images.githubusercontent.com/18159237/104303317-ff6efe80-54da-11eb-8996-01830b0ca71a.png)
Всё что я введу отправится в chat app. Точно так же как я бы сказал это голосом.

Тогда чем это отличается для canvas app ? 
Причём тут "в никуда" если точно так же надо отправить введенный текст в canvas app, который и выполнит некие действия. Как же это можно считать "в никуда" если будет реакция ? И не понимаю какая разница как ввели инфу (голосом или с клавы), когда и сейчас никакого "чата" в канвасе нет (хотя канвас канвасу рознь).

Может сделать это настраиваемым параметром и давать возможность вызывать клавиатуру отдельно ?

**Comment by Genenko-Svetlana** [comment]
Мы подразумеваем, что канвас должен быть построен таким образом, чтобы у пользователя была возможность осуществить действие голосом либо тапом по экрану. Т.е. ему не надо писать, например, выбери пункт 1, а он может выбрать его сам касанием по этому пункту.
Если же в канвасе умышленно содержится текстовое поле ввода, например, нужно ввести адрес доставки или еще что-то, то при нажатии на текстовое поле клавиатура поднимется и можно будет ввести текст.
С чат аппами по другому. Там общение построено на диалоге, поэтому клавиатура будет доступна.
Опишите кейс, когда необходима клавиатура в канвасе?

**Comment by subnetsRU** [comment]
Я в canvas реализовал многопользовательский чат. И одним из первых вопросов, когда туда пришли модераторы, был "а как печатать с клавиатуры?". Типа голосового ввода недостаточно. Отсюда и родился мой вопрос. Ведь в портале клава есть, а в  Салюте нет.

**Comment by Genenko-Svetlana** [comment]
Взяли задачу в бэклог. Сроки уточняю

**Comment by subnetsRU** [comment]
А может и не понадобится.

Я тут обнаружил, что если в html  вывести `<input type="text">`, то при тыке (фокусе) на этом поле и мобильник и сбербокс открывают таки клавиатуру. И если добавить отслеживание 'keydown', то есть возможность отследить нажатие `enter`.
![kb1](https://user-images.githubusercontent.com/18159237/104588486-7f32cf80-5679-11eb-8cbc-ff6104cff2b1.png)

А вот с отслеживанием нажатия букв и т.п. не получается. Всё время один и тот же символ печатает, что на мобиле, что на сбербоксе. 
![kb2](https://user-images.githubusercontent.com/18159237/104588504-8528b080-5679-11eb-852c-cc17f5f00704.png)

Ну да мне enter пока достаточно.

**Comment by Genenko-Svetlana** [comment]
@subnetsRU Дмитрий, можно тикет закрыть и перенести в отложенные? Пока не планируется доработка.

**Comment by subnetsRU** [comment]
Да можно.
