### ISSUE TITLE
[canvas] Какие условия запуска скринсейвера на сбербокс ?

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#136]
В догонку к тикету #135

Вопрос в том, а можно ли сейчас как-то побороть запуск скринсейвера на сбербокс ?

Если бы знать по каким условиям он запускается, то может быть уже сейчас можно придумать что-то, что позволит использовать [такого плана](https://t.me/smartapp_studio/10764) аппы.

**Comment by subnetsRU** [comment]
Попробовал гонять между front и back ping pong каждые 3 минуты. Не помогло... :(

**Comment by subnetsRU** [comment]
Про тикет не забыли ? Хотелось бы получить ответ. Апп уже опубликован и хотелось бы попробовать сделать жизнь пользователя ещё чуточку лучше.

**Comment by Genenko-Svetlana** [comment]
@subnetsRU  не забыли ))) обсуждаем

**Comment by Ibragimow** [comment]
@subnetsRU , разобрались: запуск скринсейвера на канвасах сейчас отменить все-таки нельзя. @talagaev в #135 отписался, что работу канвасов без таймаута планируем рассмотреть в Q3 2021, а это как раз и должно решить в т. ч. текущий вопрос. Об успехах, конечно, сообщим.
Спасибо за предложение и извините, что так долго отвечаем.

**Comment by Ibragimow** [comment]
Для истории: должен закрыться вместе с #135 , метим в Q3-Q4 2021.

**Comment by subnetsRU** [comment]
Вопрос был в другом. Об условиях запуска скринсейвера.

А вы ответили так как будто никакие действия не остановят запуск скринсейвера.

**Comment by Ibragimow** [comment]
@subnetsRU извините, если ответил только на половину вопроса. Но верхнеуровнево, по условиям: скринсейвер запускается в случае бездействия пользователя в течении 15 мин (если не выбрано другое значение в настройках).
