### ISSUE TITLE
[canvas] Ответ от смартапа делает ассистента немым

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#137]
**Где нашелся баг**: в ассистенте на sberbox, sberportal
**Описание проблемы**: ассистент замолкает и больше ничего не говорит
**Проблема воспроизводится у других пользователей?** скорее да, чем нет
**Дополнительная информация**: Искал решение как побороть запуск скринсейвера на сбербокс (#136).

Подумал, что возможно периодический ping pong между front и back поможет отложить запуск скринсейвера.

Ессно, что при этом ассистент не должен ничего произносить в ответ на ping. Если совсем ничего не отвечать на ping с front, то приходит 500-ый ответ с smart_app_error (который присылает платформа), что не хорошо. Решил, отправить ответ только с smart_app_data.

Отправка ping c front:
```
{"messageId":1610704281598126000,"sessionId":"eca208a6-742f-4c03-9e60-6aebd4a4c751","messageName":"SERVER_ACTION","payload":{"applicationId":"38761533-52c6-44fb-ab7e-e4e41bb7ba4c","appversionId":"38475749-9740-4ac0-ac68-f18d3a7f52a6","projectName":"2bd38d3a-5d4e-4264-925c-19b354781cf6","device":{"platformType":"android","platformVersion":"9","surface":"STARGATE","surfaceVersion":"1.67.35","features":{"appTypes":["APK","WEB_APP","DIALOG"]},"capabilities":{"mic":{"available":true},"screen":{"available":true},"speak":{"available":true}},"deviceId":"365239535001000010362105","deviceManufacturer":"SberDevices","deviceModel":"stargate","additionalInfo":[]},"app_info":{"projectId":"1940543c-0df0-416a-b370-cca5a6aaaffb","applicationId":"38761533-52c6-44fb-ab7e-e4e41bb7ba4c","appversionId":"38475749-9740-4ac0-ac68-f18d3a7f52a6","systemName":null,"frontendEndpoint":"https:\/\/frontURL\/index.html","frontendType":"WEB_APP"},"new_session":false,"strategies":{"last_call":null},"character":{"id":"joy","name":"Джой","gender":"female","appeal":"no_official"},"meta":{"current_app":{"app_info":{"applicationId":"38761533-52c6-44fb-ab7e-e4e41bb7ba4c","appversionId":"38475749-9740-4ac0-ac68-f18d3a7f52a6","frontendEndpoint":"https:\/\/frontURL\/index.html","frontendType":"WEB_APP","projectId":"1940543c-0df0-416a-b370-cca5a6aaaffb"},"state":[]},"time":{"timestamp":1610704281597,"timezone_id":"Europe\/Moscow","timezone_offset_sec":10800}},"server_action":{"action_id":"ping"},"message":{"original_message_name":"SERVER_ACTION"}},"uuid":{"userId":"2a256fdc-321c-4844-8625-a9571cdcc619","sub":"UhaD1opXmDE+E2fbiaPDfWzGctMFzkxuI3qHtA55YEYsavfj+VmwaOIUf2HCx48LU5IS3O0KjpXvsZxMQ88fOT5a5aeT6YBtH49yVv9V2+cgx4ShX5Au\/gCna7IHCjyavjA7QjnBJQWLScrX9cZhOstDTo59E7+JRdO8+ydZFzM=","userChannel":"B2C"},"session":{"skill_id":"38761533-52c6-44fb-ab7e-e4e41bb7ba4c","user_id":"2eeece46a6d9de6c1f95c78869af1a57","application":{"application_id":"2eeece46a6d9de6c1f95c78869af1a57"},"user":{"user_id":"2eeece46a6d9de6c1f95c78869af1a57"},"new":false,"session_id":"2eeece46a6d9de6c1f95c78869af1a57-20210115","message_id":1610704281598126000},"request":{"command":"","command_original":"ping","original_utterance":"","type":"ButtonPressed","payload":"ping"},"meta":{"interfaces":{"screen":[]},"timezone":"Europe\/Moscow","timezone_offset":0}}
```
Ответ от back:
```
{"messageId":1610704281598126000,"sessionId":"eca208a6-742f-4c03-9e60-6aebd4a4c751","messageName":"ANSWER_TO_USER","uuid":{"userId":"2a256fdc-321c-4844-8625-a9571cdcc619","sub":"UhaD1opXmDE+E2fbiaPDfWzGctMFzkxuI3qHtA55YEYsavfj+VmwaOIUf2HCx48LU5IS3O0KjpXvsZxMQ88fOT5a5aeT6YBtH49yVv9V2+cgx4ShX5Au\/gCna7IHCjyavjA7QjnBJQWLScrX9cZhOstDTo59E7+JRdO8+ydZFzM=","userChannel":"B2C"},"payload":{"items":[{"command":{"type":"smart_app_data","smart_app_data":"skip_response for [ping]"}}],"device":{"platformType":"android","platformVersion":"9","surface":"STARGATE","surfaceVersion":"1.67.35","features":{"appTypes":["APK","WEB_APP","DIALOG"]},"capabilities":{"mic":{"available":true},"screen":{"available":true},"speak":{"available":true}},"deviceId":"365239535001000010362105","deviceManufacturer":"SberDevices","deviceModel":"stargate","additionalInfo":[]},"auto_listening":false,"finished":false,"pronounceTextType":"application\/ssml","pronounceText":"<speak><\/speak>"}}
```
Да, я виноват в том, что допустил ответ с таким `pronounceText`, это неосознанный баг. Итогом такого ответа становится на портале и сбербокс (одинаковое поведение):
* на портале полностью исчезает голос ассистента, радио играет очень тихо ([видео демонстрация проблемы есть тут](https://t.me/sberdevices_chat/9292))
* на сбербокс при нажатии на кнопку ассистента на пульте ничего не происходит и ассистент не начинает слушать, радио играет так тихо, что сначала может показаться, что оно не запустилось вовсе.

Проблема решается только перезапуском устройства.

Если баг с `pronounceText` исправить и привести ответ к:
```
{"messageId":1610642708774,"sessionId":"06890a99-f7fa-4aee-8754-95e844917fc9","messageName":"ANSWER_TO_USER","uuid":{"userId":"webdbg_userid_2r0anksoptra7r5xnflgfq","sub":"UhaD1opXmDE+E2fbiaPDfWzGctMFzkxuI3qHtA55YEYsavfj+VmwaOIUf2HCx48LU5IS3O0KjpXvsZxMQ88fOT5a5aeT6YBtH49yVv9V2+cgx4ShX5Au\/gCna7IHCjyavjA7QjnBJQWLScrX9cZhOstDTo59E7+JRdO8+ydZFzM=","userChannel":"B2C"},"payload":{"items":[{"command":{"type":"smart_app_data","smart_app_data":"skip_response for [ping]"}}],"device":{"platformType":"WEBDBG","platformVersion":"1.0","surface":"SBERBOX","surfaceVersion":"20.09.1.3576","features":{"appTypes":["DIALOG","WEB_APP"]},"capabilities":{"screen":{"available":true,"height":649,"width":1771},"speak":{"available":true}},"deviceId":"","deviceManufacturer":"","deviceModel":"","additionalInfo":{"host_app_id":"ru.sberbank.sdakit.demo","sdk_version":"20.09.1.3576"}},"auto_listening":false,"finished":false}}
```
То проблема уже не воспроизводится.

P.S. Салют (андройд версия) этой проблем не подвержена.

**Comment by Genenko-Svetlana** [comment]
Срок реализации - 15.02.2021

**Comment by talagaev** [comment]
это тоже в Старос, но я вижу тикет уже в тестировании и будет в 1.70

**Comment by Genenko-Svetlana** [comment]
@subnetsRU  проверяйте, пожалуйста. Реализовано в 1.69.

**Comment by subnetsRU** [comment]
Смогу проверить не раньше вечера.

**Comment by subnetsRU** [comment]
Проверил. Проблема не воспроизводится.

**Comment by subnetsRU** [comment]
Всё же я поторопился. На портале проблема опять воспроизвелась.

**Comment by Genenko-Svetlana** [comment]
@subnetsRU  только на портале?

**Comment by subnetsRU** [comment]
Да. Я утром к нему, а он лавашаром "моргает", т.е. видно, что он отвечает, но при этом звука голоса нет, но остальной звук работает. Причём не как ранее, когда весь звук приглушался, а нормальная громкость всех звуков, но голоса ассистента нет.

Как и в прошлый раз - ребут вылечил проблему.

**Comment by Genenko-Svetlana** [comment]
@subnetsRU исправлено в 1.69. Можно проверять

**Comment by subnetsRU** [comment]
Так я же уже проверял на 1.69. О чём и написано чуть выше.

**Comment by Genenko-Svetlana** [comment]
@subnetsRU воспроизводится именно после того, как навык шлет пустой звук?
А можно messageId?

**Comment by subnetsRU** [comment]
Пустой не звук, а пустой текст:
```
"pronounceText": "<speak></speak>",
```
Я сейчас не дома. Дома ребенок. Попробовал воспроизвести эту ситуацию с ним, не получилось. Говорит, что слышит ответы ассистента даже после пустого ответа. Версия прошивки сейчас 1.69.**35**.

Варианта 2:
* в 1.69.**35** это действительно исправлено
* или всё же надо, чтобы потестил я сам, но сделать это смогу только завтра утром

**Comment by Genenko-Svetlana** [comment]
@subnetsRU подождём до утра )

**Comment by subnetsRU** [comment]
Проверил. Сейчас воспроизвести проблему действительно не получается.

Будем надеяться что больше и не получится. Спасибо.

**Comment by Genenko-Svetlana** [comment]
Чудесно!
