### ISSUE TITLE
[ASR] Лучшая гипотеза не на русском, а на английском языке (недельные отчёты)

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#141]
Продолжение #18 в новом формате. Тикет для еженедельных csv файлов. (как и договорились в ТГ)

[asr.log.csv.20210124.txt](https://github.com/sberdevices/salute-issues/files/5862199/asr.log.csv.20210124.txt)

**Comment by RulevAnton** [comment]
файл asr.log.csv.20210124.txt отработан

**Comment by subnetsRU** [comment]
[asr.log.csv.20210201.txt](https://github.com/sberdevices/salute-issues/files/5902218/asr.log.csv.20210201.txt)

**Comment by RulevAnton** [comment]
файл asr.log.csv.20210201.txt обработан

**Comment by subnetsRU** [comment]
[asr.log.csv.20210208.txt](https://github.com/sberdevices/salute-issues/files/5941530/asr.log.csv.20210208.txt)

**Comment by subnetsRU** [comment]
[asr.log.csv.20210215.txt](https://github.com/sberdevices/salute-issues/files/5979693/asr.log.csv.20210215.txt)

**Comment by RulevAnton** [comment]
asr.log.csv.20210208.txt и asr.log.csv.20210215.txt обработаны.

**Comment by subnetsRU** [comment]
[asr.log.csv.20210222.txt](https://github.com/sberdevices/salute-issues/files/6019950/asr.log.csv.20210222.txt)

**Comment by subnetsRU** [comment]
[asr.log.csv.20210301.txt](https://github.com/sberdevices/salute-issues/files/6059605/asr.log.csv.20210301.txt)

**Comment by subnetsRU** [comment]
[asr.log.csv.20210309.txt](https://github.com/sberdevices/salute-issues/files/6106258/asr.log.csv.20210309.txt)

**Comment by RulevAnton** [comment]
asr.log.csv.20210222.txt, asr.log.csv.20210301.txt и asr.log.csv.20210309.txt обработаны.
В будущем должно быть меньше ошибок с буквами.

**Comment by subnetsRU** [comment]
[asr.log.csv.20210315.txt](https://github.com/sberdevices/salute-issues/files/6139287/asr.log.csv.20210315.txt)

Да, ошибок по буквам стало в разы меньше, но всё же ещё есть. Этот файл тому подтверждение.

**Comment by subnetsRU** [comment]
[asr.log.csv.20210322.txt](https://github.com/sberdevices/salute-issues/files/6180603/asr.log.csv.20210322.txt)

**Comment by subnetsRU** [comment]
[asr.log.csv.20210329.txt](https://github.com/sberdevices/salute-issues/files/6220014/asr.log.csv.20210329.txt)

**Comment by subnetsRU** [comment]
[asr.log.csv.20210405.txt](https://github.com/sberdevices/salute-issues/files/6257512/asr.log.csv.20210405.txt)

**Comment by RulevAnton** [comment]
в работе

**Comment by subnetsRU** [comment]
[asr.log.csv.20210413.txt](https://github.com/sberdevices/salute-issues/files/6301673/asr.log.csv.20210413.txt)

**Comment by RulevAnton** [comment]
@subnetsRU Добрый день! Давайте пока приостановим процесс. Очень много повторяющихся проблем наблюдаю. Хочется подождать фикса в рамках данного тикета.

**Comment by subnetsRU** [comment]
Хорошо. Напиши тогда, когда надо будет продолжать.

**Comment by Genenko-Svetlana** [comment]
@subnetsRU Дмитрий, есть еще материал для работы? ))) Или всё хорошо?

**Comment by subnetsRU** [comment]
Есть. Но выше же Антон попросил приостановить процесс. Я жду сообщения про возобновление процесса.

**Comment by RulevAnton** [comment]
Коллеги, up-нул тикет по фиксу.
Посмотрел текущий файлик с 31.05 по  03.06, вижу что основное кол-во примеров связано с некорректным распознаванием из-за плохого звука или просто ошибочной русской гипотезы. Большинство реальных ошибок повторяется с теми, что в существующем тикете.
То есть проблем распознавния как таковых становится всё меньше.

Давайте подождём фикса тикета имеющегося, а этот тикет гитхаб пока закроем.

Я бы предложил - посмотреть ситуацию через месяца 3.

**Comment by Genenko-Svetlana** [comment]
@subnetsRU посмотрите, пожалуйста, остались ли проблемы?

**Comment by Genenko-Svetlana** [comment]
@subnetsRU @RulevAnton может пришло время закрыть тикет? :-)

**Comment by subnetsRU** [comment]
Ну если моя помощь в данном вопросе более не требуется, то можно и закрыть. Я не против.
