### ISSUE TITLE
[canvas] Проблема на SberPortal при попытке отобразить фото большого размера.

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#142]
**Где нашелся баг**: SberPortal
**Описание проблемы**: Если в canvas app выводить в теге `<img>` картинку большого размера (на 7 - 12 мегабайт, разрешение 4000x6000 точно проявляется), то портал сначала просто перестаёт отзываться (не откликается ни на голос, ни на нажатия на экране), а потом экран и вовсе тухнет. Через какое-то время включается, оказывается на главном экране с саджестами от canvas app, но сам canvas уже не работает.
**Проблема воспроизводится у других пользователей?** Да.
**Дополнительная информация**: Я уже передал эту информацию вашему сотруднику Дмитрию из команды разработки портала (ник в ТГ @ya_thatguy). Он снял логи и завёл внутренний тикет. Этот я завожу по согласованию с ним же.

**Comment by Genenko-Svetlana** [comment]
@subnetsRU  Дмитрий, к сожалению мы не планируем работать с данной задачей. 
С Дмитрием из команды разработки портала (ник в ТГ @ya_thatguy) этот вопрос обсудили. 

Рекомендуем использовать общепринятый подход, используемый при разработке приложений: приложение не должно надолго занимать процессор, должно минимально потреблять памяти и быть как можно более маленьким по размеру.

Так же и с картинками, которые используются в смартапе. Необходимо выбрать золотую середину между размером фото и работоспособностью девайса (они у нас классные, но их возможности не безграничны).

**Comment by subnetsRU** [comment]
Да это понятно, что я, как разработчик, постараюсь что-то придумать, чтобы этого не происходило. Но, в данном случае, мне как разработчику, хотелось бы избегать выкачивания контента пользователя на свои сервера для предварительной обработки.

Да и тикет был больше о том, что сторонний разработчик может случайно (или специально) обрушить устройство пользователя.

Ну хорошо, как скажете. Решать естественно вам.

**Comment by Genenko-Svetlana** [comment]
Спасибо за вовлеченность!
