### ISSUE TITLE
Неправильные ударения в словах

### ISSUE THREAD

**Issue by danchistyakov** [sberdevices/salute-issues#144]
**Где нашелся баг**: в ассистенте;
**Описание проблемы**: Неправильные ударения в словах
**Проблема воспроизводится у других пользователей?** да;
**Дополнительная информация**:
 - Ударения в словах типа "журят", "смежила", "косы", "добре";
 - Проблемы с произношением до сих пор встречаются: "У страха глаза велИки", "Курочка рябА"

**Comment by subnetsRU** [comment]
Так это же правится [ssml](https://developer.sberdevices.ru/docs/ru/developer_tools/ssml/overview) разметкой. Вот [про ударения](https://developer.sberdevices.ru/docs/ru/developer_tools/ssml/supported_characters):
>Знак ударения ' после гласной

**Comment by danchistyakov** [comment]
> Так это же правится [ssml](https://developer.sberdevices.ru/docs/ru/developer_tools/ssml/overview) разметкой. Вот [про ударения](https://developer.sberdevices.ru/docs/ru/developer_tools/ssml/supported_characters):
> 
> > Знак ударения ' после гласной

В http-запросах разве будет работать?

**Comment by Genenko-Svetlana** [comment]
@DCStudioProjects В Graph разметку можно изменить в блоке "Текст". Ударение можно указать с помощью символа '

https://smartapp-code.sberdevices.ru/documentation/#/docs/ru/developer_tools/ssml/overview
https://developer.sberdevices.ru/docs/ru/developer_tools/ssml/supported_characters

**Comment by RulevAnton** [comment]
по поговоркам - TTSQA-1593
по словам "журят", "смежила", "косы", "добре" нужен контекст.

**Comment by danchistyakov** [comment]
> по поговоркам - TTSQA-1593
> по словам "журят", "смежила", "косы", "добре" нужен контекст.

Коровушка-матушка! Меня бьют-**журят**, хлеба не дают, плакать не велят.
Двуглазка тоже на солнышке распеклась и на травушке разлеглась, материно приказанье забыла и глазки **смежила**.
Сёстры хотели их сбить – листья глаза засыпают, хотели сорвать – сучки **косы** расплетают.
Угостила она того сильного человека и он на ней женился, и стала она в **добре** поживать, лиха не знать.

**Comment by RulevAnton** [comment]
@DCStudioProjects Подобный тикеты с проблемным ударением можно фиксить на своей стороне проставляя ударение символом апострофа '
Как сказал выше @subnetsRU 

Так что вы можете поправить это на своей стороне, как-то так:

Коровушка-матушка! Меня бьют-**журя'т**, хлеба не дают, плакать не велят.
Двуглазка тоже на солнышке распеклась и на травушке разлеглась, материно приказанье забыла и глазки смежила. - **судя по гуглу правильно смежИла, сейчас так и говорит**
Сёстры хотели их сбить – листья глаза засыпают, хотели сорвать – сучки **ко'сы** расплетают.
Угостила она того сильного человека и он на ней женился, и стала она в **добре'** поживать, лиха не знать.

У страха глаза **велики'**
курочка **ря'ба**

Но сообщать о таких проблемах нужно, чтобы мы всё равно фиксили эти проблемные места.

Предлагаю пофиксить на своей стороне и закрывать тикет. Тикеты на своей стороне я завёл.

**Comment by danchistyakov** [comment]
> @DCStudioProjects Подобный тикеты с проблемным ударением можно фиксить на своей стороне проставляя ударение символом апострофа '
> Как сказал выше @subnetsRU
> 
> Так что вы можете поправить это на своей стороне, как-то так:
> 
> Коровушка-матушка! Меня бьют-**журя'т**, хлеба не дают, плакать не велят.
> Двуглазка тоже на солнышке распеклась и на травушке разлеглась, материно приказанье забыла и глазки смежила. - **судя по гуглу правильно смежИла, сейчас так и говорит**
> Сёстры хотели их сбить – листья глаза засыпают, хотели сорвать – сучки **ко'сы** расплетают.
> Угостила она того сильного человека и он на ней женился, и стала она в **добре'** поживать, лиха не знать.
> 
> У страха глаза **велики'**
> курочка **ря'ба**
> 
> Но сообщать о таких проблемах нужно, чтобы мы всё равно фиксили эти проблемные места.
> 
> Предлагаю пофиксить на своей стороне и закрывать тикет. Тикеты на своей стороне я завёл.

Да, но тогда портится вид ответа от ассистента и символ ' виден.

**Comment by Genenko-Svetlana** [comment]
В text - то что выводим на экран, в sint - то что будет озвучиваться (с проставленным ударением)

**Comment by danchistyakov** [comment]
> В text - то что выводим на экран, в sint - то что будет озвучиваться (с проставленным ударением)

Да, вернусь с ответом в Телеграме

**Comment by RulevAnton** [comment]
@DCStudioProjects Я так понял, что это можно сделать, давайте здесь эту тему добьём.

**Comment by danchistyakov** [comment]
> @DCStudioProjects Я так понял, что это можно сделать, давайте здесь эту тему добьём.

Давайте!

**Comment by danchistyakov** [comment]
А слова в синтезе речи перечислять через запятую или пробел просто?

**Comment by Genenko-Svetlana** [comment]
В случае с переменной, просто весь текст продублировать и проставить знаки ударения

**Comment by danchistyakov** [comment]
> В случае с переменной, просто весь текст продублировать и проставить знаки ударения

Не очень понял, мне все 20 сказок в одной строчке размечать?))

**Comment by RulevAnton** [comment]
> А слова в синтезе речи перечислять через запятую или пробел просто?

Это про поле sint ("Текст для синтеза речи")?

Вы просто разделяете любой текст (сказка или просто фраза любая) на 2 блока:
Реплика ассистента - то, что выводится на экран
Текст для синтеза речи - то, что отправляется на синтез.

То есть как пример.
Реплика ассистента: Коровушка-матушка! Меня бьют-журят, хлеба не дают, плакать не велят.
Текст для синтеза речи: Коровушка-матушка! Меня бьют-**журя'т**, хлеба не дают, плакать не велят.

**Comment by danchistyakov** [comment]
> > А слова в синтезе речи перечислять через запятую или пробел просто?
> 
> Это про поле sint ("Текст для синтеза речи")?
> 
> Вы просто разделяете любой текст (сказка или просто фраза любая) на 2 блока:
> Реплика ассистента - то, что выводится на экран
> Текст для синтеза речи - то, что отправляется на синтез.
> 
> То есть как пример.
> Реплика ассистента: Коровушка-матушка! Меня бьют-журят, хлеба не дают, плакать не велят.
> Текст для синтеза речи: Коровушка-матушка! Меня бьют-**журя'т**, хлеба не дают, плакать не велят.

Да, но у меня на 1 блок приходит 20 сказок и в зависимости от рандомно сгенерированного числа выводится соответствующая сказка. Как мне разделить несколько слов, в которых нужно проставить ударения: запятой или просто пробелом?

**Comment by RulevAnton** [comment]
Созвонились, обсудили голосом. Ждём фидбека, получилось или нет.

**Comment by danchistyakov** [comment]
> Созвонились, обсудили голосом. Ждём фидбека, получилось или нет.

Всё получилось, если будут возникать ещё некритичные проблемы с ударением буду добрасывать сюда, критичные — в другой тикет.

**Comment by Genenko-Svetlana** [comment]
@DCStudioProjects этот тикет можно зарыть?

**Comment by danchistyakov** [comment]
> @DCStudioProjects этот тикет можно зарыть?

Смотрите, как у Вас устроено, по идее — да, и в deffered или done можно закинуть, так как по-любому сюда ещё добросы будут.

**Comment by Genenko-Svetlana** [comment]
@DCStudioProjects  Лучше собрать несколько примеров и создать новый.

**Comment by danchistyakov** [comment]
> @DCStudioProjects  Лучше собрать несколько примеров и создать новый.

Ок
