### ISSUE TITLE
Собираем вопросы к митапу 11.02.2021

### ISSUE THREAD

**Issue by Genenko-Svetlana** [sberdevices/salute-issues#146]

**Comment by DenisNP** [comment]
**Собрал свои вопросы + некоторые по итогам обсуждений в чате:**

1. Почему в первом этапе премии нет 2-3 места в категории DAU? Почему нет категорий "удержание" и "ревеню"?
2. Сколько на площадке пользователей, которые запускают смартаппы? 
3. Как продвигать свои смартаппы? Прямых ссылок нет, каталога нет.
4. Когда Canvas App будут доступны в обычном приложении СберБанк Онлайн?
5. 30 дней отсчитываются с конца этапа или включены в этап? 
6. Средний DAU берётся за весь этап, даже если приложение было опубликовано в середине этапа, или только за срок существования приложения? 
7. Участвуют ли в новых этапах приложения, опубликованные за время предыдущих этапов?
8. Можно ли использовать легальную рекламу для продвижения конкурсного проекта? Можно ли публиковать посты об этом в соцсетях, приводя, таким образом, траффик?

**Comment by DenisNP** [comment]
И отдельно два сугубо технических вопроса, может мне так ответят, не на митапе.

1.
> Переносы строк в JSON-ответах смартапов запрещены.

То есть в строках нельзя передавать символ `\n`, и в целом никакой перенос работать не будет, текст сплошной?

2. 
Можно ли в поле url изображения передавать base64 код?

**Comment by subnetsRU** [comment]
1. Разбей по \n на несколько bubble.

2. Не совсем понятен вопрос. Если это о chat app, то в url не может быть ничего кроме ссылки, которая выдаётся после загрузки изображения в studio. Там ещё и его хеш надо передавать.

**Comment by subnetsRU** [comment]
Касаемо одного из возможных методов монетизации. 

Сейчас в документации в "Требования к смартапу" написано:
>В смартапе не должно быть:
> * Рекламы

Вопрос 1: Есть ли шанс, что это когда-то изменится ? Обсуждалось ли такое ? (или весь затык в том, что "деньги мимо кассы" ? :))

Вопрос 2: Речь, как я понимаю, идёт про прямую рекламу. А возможна ли скрытая (неявная) ?

Так же написано:
>Запрещенные данные и контент:
>порнография и контент сексуальной направленности;

Вопрос 1: Если с порнографией более-менее всё понятно (хотя тоже есть что спросить), то вот с "контент сексуальной направленности" не всё так однозначно точно. Хотелось бы больше конкретики о том, что попадает под понятие "сексуальная направленность".

Вопрос 2: Будут ли тут какие либо изменения после полноценной реализации "детский режим" ? (_над которым вы сейчас работаете)_

**Comment by Genenko-Svetlana** [comment]
Спасибо за участие в митапе!
На вопросы, которые не были озвучены на встрече, ответим в сообществе Телеграм в ближайшее время.

**Comment by Genenko-Svetlana** [comment]
@subnetsRU 
1. Про рекламу был ответ на митапе: во втором полугодии такая возможность появится.
Скрытая реклама запрещена.
2. Про контент сексуальной направленности вот здесь хорошо описано - https://support.google.com/youtube/answer/2802002?hl=ru.
Детский режим ничего не изменит.

**Comment by subnetsRU** [comment]
Ну про если про "чернуху" всё понятно и вопросов нет (никто ж не собирался делать ничего подобного), то по более лёгкому контенту вопросы всё равно остаются. Но раз:

>Детский режим ничего не изменит.

То наверно нет смысла их задавать, раз даже "вызвать у зрителей сексуальное возбуждение" запрещено.

Ну что сказать - печально. Получается взрослых и тут обделили... Пора идти в монастырь :)

**Comment by Genenko-Svetlana** [comment]
@subnetsRU Дмитрий, если вы говорите о навыке, который мы обсуждали, то он возможен после реализации детского режима.
Категория 18+ точно будет не доступна детям. 
Так что ждём ваш ап на модерацию, как только появится такая возможность )))

**Comment by subnetsRU** [comment]
Нет, не о том смартапе, что мы обсуждали. С ним же уже всё ясно, он ждет реализации детского режима.

Были другие мысли, чтобы создавать, как пример, игры, но только для взрослой аудитории, а не только просветительские навыки. Просто, повторюсь, что контента для взрослой аудитории в голосовых помощниках ничтожно мало. Можно по пальцам пересчитать, а для детей пруд пруди.
