### ISSUE TITLE
Лаги в Салюте в gallery_card

### ISSUE THREAD

**Issue by ygerzen** [sberdevices/salute-issues#147]
Если в Салюте в одном аппе вывести несколько галерей gallery_card с большим количеством изображений (по 28 штук) на выбор пользователю, то Салют начинает притормаживать при выводе дальнейших сообщений и при прокрутке истории сообщений.
Как вариант решения проблемы можно было бы удалять из аппа галерею после её отображения пользователю и выбора нужной картинки, но вроде такой опции нет. Предлагаю её сделать, чтобы можно было из сценария удалять показанную ранее галерею. Возможно у вас есть другое решение, тогда поделитесь им, пожалуйста.

**Comment by Genenko-Svetlana** [comment]
@ygerzen iOS?

**Comment by ygerzen** [comment]
да, iOS 14.4
Версия приложения Салюта 21.2.1007

**Comment by Genenko-Svetlana** [comment]
Срок реализации - до 30.06.21.
Пока тикет закрываем и переносим в отложенные.

**Comment by Genenko-Svetlana** [comment]
Возвращаем в работу

**Comment by talagaev** [comment]
холд до 2022

**Comment by Genenko-Svetlana** [comment]
Временно закрываем и переносим в отложенные задачи
