### ISSUE TITLE
Копирование текста в приложении Сбер Салют для ios

### ISSUE THREAD

**Issue by ygerzen** [sberdevices/salute-issues#148]
**Где пригодится фича**: в приложении Сбер Салют при тестировании аппов.
**Описание фичи**: Есть проблема в Сбер Салюте(ios), нельзя копировать текст через контекстное меню. Предлагаю добавить возможность копирования, т.к. это часто нужно при отладке аппа и для общения с тех.поддержкой.
**Дополнительная информация**: На данный момент доступна только одна опция "Сообщить о проблеме" при выборе, открывается отправка письма с данными о запросе. Приходится оттуда копировать необходимые данные и это не удобно. А если почтовый клиент не настроен, то и скопировать ничего не получится.

![image](https://user-images.githubusercontent.com/21137721/107209557-04f53100-6a14-11eb-964a-ce5269a7915d.png)

**Comment by talagaev** [comment]
@ygerzen  добавьте  учетную запись в стандарный mail агент, тогда откроется форма, где вы сможете все скопировать.

**Comment by talagaev** [comment]
#

**Comment by NikolayPakhomov** [comment]
Над возможностью копирования через Салют подумаем, но пока не планируем добавлять.
