### ISSUE TITLE
[SmartApp API, Chat App] - проблема с выходом из смартаппа

### ISSUE THREAD

**Issue by exitoso** [sberdevices/salute-issues#149]
**Где нашелся баг**: В мобильном приложении, в Сбербоксе
**Описание проблемы**: ассистенту передается json (пример во вложении) на закрытие смартаппа, ассистент принимает json, но закрытие не происходит, на экране отображается содержимое смартаппа, не происходит переход на предыдущее запущенное приложение.
**Проблема воспроизводится у других пользователей?** не знаю.
**Дополнительная информация**: 
1. Создаю suggestion, которые обеспечивает выход из смартаппа
"suggestions":{"buttons":[{"title":"Выйти","action":{"type":"server_action","server_action":{"action_id":"exit"}}}}
2. При клике на него ассистент передает на мой сервер "action_id" со значение "exit"
3. На этот случай я генерирую json: [log.txt](https://github.com/sberdevices/salute-issues/files/5953585/log.txt)
4. После этого suggestion исчезает, пользователь остаётся в моем приложение на то же шаге, выход не осуществляется.

**Comment by talagaev** [comment]
не увидел, а вы отправляете close app ?
https://developer.sberdevices.ru/docs/ru/developer_tools/amp/smartappapi_description_and_guide

**Comment by subnetsRU** [comment]
Прошу прощения, что влез, но сообщение с типом CLOSE_APP отправляет платформа, а не смартап ;)

О чём и написано в этой же доке чуть выше:
>**Ассистент передает** запросы следующих следующих типов:

**Comment by Genenko-Svetlana** [comment]
Срок реализации ориентировочно - 05.03.2021.

**Comment by SokolovVladimir** [comment]
@exitoso 
Добрый день! По твоему кейсу понятно, что пользователь нажимает на саджест.
Команда CLOSE_APP отправляется на голосовой запрос пользователя о закрытие смарт аппа. Например, "хватит", "закрой" и тд. https://developer.sberdevices.ru/docs/ru/methodology/testing/smartapp_activation
Поэтому в твоем кейсе, нужно явно в ответе передать в блоке items команду close_app, чтобы смарт апп корректно закрылся.
https://developer.sberdevices.ru/docs/ru/developer_tools/amp/smartapp_api_commands

**Comment by subnetsRU** [comment]
@SokolovVladimir, у меня не было кейса. Кейс был у автора тикета @exitoso.

В его кейсе пользователь тыкает в кнопку, сообщая его аппу о своём желании выйти. Апп видя это желание формирует JSON, согласно которому сессия должна быть завершена.

Я лишь отметил, что в после того как пользователь нажал кнопку, то его смартап явно шлет  
payload.finished = true (см. log.txt выше), что согласно [документации](https://developer.sberdevices.ru/docs/ru/developer_tools/amp/smartappapi_description_and_guide#answer-to-user) 
>true — диалог завершён, следующее сообщение пользователя поступит в другое приложение;
>false — диалог продолжается, сообщения пользователя передаются в приложение.

является признаком того, что смартап завершается. Более того у меня это так и работает и никаких close_app в items я никогда не посылал и сейчас не посылаю. finished":true достаточно, чтобы chat app закрылся.

Почему chat app автора тикета не закрывается в этом случае я не знаю.

Просто изначально я подумал, что вы про [этот CLOSE_APP](https://developer.sberdevices.ru/docs/ru/developer_tools/amp/smartappapi_description_and_guide/#close-app) говорили.

**Comment by exitoso** [comment]
С добавлением 
`
      {
          "command": {
              "type": "close_app"
          }
      }
`
проблема решилась.
Оставлю json тут для истории.
[log2.txt](https://github.com/sberdevices/salute-issues/files/6078248/log2.txt)
