### ISSUE TITLE
Добавить в команды запуска смартапа команды типа "спроси у".

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#15]
Добавить в команды запуска смартапа команды по типу:

- спроси у
- узнай у
- попроси у

Необходимые для смартапов с одним ответом и не предполагающих дальнейшего диалога с пользователем. Такой тип запуска смартапа у пользователя будет ассоциироваться с односложным ответом и автоматическим завершением смартапа.

Например: "узнай у _<НАЗВАНИЕ СМАРТАПА>_ курс доллара"
В этом случае платформа запустит _<НАЗВАНИЕ СМАРТАПА>_ и в кач-ве текста в сообщении типа "messageName":"MESSAGE_TO_SKILL" передаст в payload _original_text_ "курс доллара".

Смартап озвучит свой ответ и автоматически завершится, не заставляя пользователя произносить "хватит".

Для более точного определения, что смартап был вызван именно такой командой, можно (и хотелось бы), чтобы во входящем JSON что-то указывало на это.
Например, сейчас при _MESSAGE_TO_SKILL_ есть _"intent":"run_app"_. 
Как вариант в случае запуска смартапа подобной командой можно передать _"intent":"**run_app_once**"_, что будет явным образом указывать на то, что нужно автоматически закрыть сессию с пользователем после ответа.

**Comment by vkycniichai** [comment]
Возможность обсуждается внутри команды, ответ, ориентировочно, будет предоставлен к концу месяца.

**Comment by vkycniichai** [comment]
@subnetsRU возможность реализации фичи будет рассмотрена командой в 2021 году.
Пока тикет закрываем, если будет принято положительное решение, то заявка будет открыта повторно.

**Comment by Genenko-Svetlana** [comment]
@kuznetsovn будет реализация?

**Comment by Genenko-Svetlana** [comment]
@gaphex  посмотри, пожалуйста, задачу

**Comment by Genenko-Svetlana** [comment]
Команда запуска "спроси у" добавлена.

**Comment by Genenko-Svetlana** [comment]
@subnetsRU

**Comment by subnetsRU** [comment]
"спроси у моего синоптика погоду", "спроси у моего синоптика что за окном" - апп не запускается, выдаётся штатный прогноз погоды.

"спроси у моего синоптика как дела" - ответ "у какого именно из них?"

"спроси у мой синоптик как дела?" - ответ "всё хорошо, почему плохо?"

"спроси у 100 к 1 как дела?" - ответ "Хорошо, Аристарх. Прекрасно, Савелий!"

Увы, но не работает. Ни в одном из случаев апп так и не запустился.

**Comment by Genenko-Svetlana** [comment]
@subnetsRU можно пробовать )))
Работают фразы:
[
  "спросить у",
  "спросить",
  "спроси у",
  "спроси",
  "узнать у",
  "узнать ",
  "узнай у",
  "узнай",
  "попроси у",
  "попроси",
  "попросить у",
  "попросить"
]

**Comment by subnetsRU** [comment]
Воооот, теперь работает ! Спасибо. 

Доработал апп. Теперь если город был установлен, а апп был запущен подобной фразой, то можно просто попросить погоду и не утруждать себя фразой "хватит". Теперь станет много удобнее использовать апп.

P.S. Надо бы обновить документацию по данному поводу ;) Это реально полезная фишка.

**Comment by Genenko-Svetlana** [comment]
@oblomil @Lytkini посмотрите, пожалуйста, по документации.

**Comment by subnetsRU** [comment]
Ещё момент, эти фразы не появились в smartapp-studio в "Примеры запуска смартапа". А надо бы.

**Comment by Genenko-Svetlana** [comment]
@subnetsRU  уже в работе

**Comment by Nashev** [comment]
А как на такой вид запуска отреагировать в смартаппе, сделанном через Graph?

**Comment by Genenko-Svetlana** [comment]
В блоке js-код можно использовать вот такой код и дальше уже анализировать и направлять
`$request.rawRequest.payload.message`
