### ISSUE TITLE
SmartApp Graph - Если один блок Интенты на экране - не появляется возможность добавить еще блок

### ISSUE THREAD

**Issue by noskoviv** [sberdevices/salute-issues#150]
Если на экране присутствует только один блок интенты, то не появляется под экраном ссылка на добавление блоков.

**Comment by asmalakhov-sberdevices** [comment]
Да, эта метка будет добавлена. Появится со следующими обновлениями, планируем до 01.03.21

**Comment by Genenko-Svetlana** [comment]
Воспроизвели у себя, взяли в работу. Срок реализации - 01.03.2021

**Comment by noskoviv** [comment]
Временное решение для возможности к блоку Интенты добавить Подсказку - добавить Текстовый блок - затем добавить Подсказку, потом удалить Текстовый блок

**Comment by asmalakhov-sberdevices** [comment]
@noskoviv сделали исправление. Проверьте, пожалуйста, что теперь все корректно
fyi @Genenko-Svetlana

**Comment by noskoviv** [comment]
Все работает.
Спасибо.
