### ISSUE TITLE
SmartApp Graph - блок Интенты

### ISSUE THREAD

**Issue by noskoviv** [sberdevices/salute-issues#151]
В предыдущей версии интерфейса был особый значок на блоке Интенты - если он доступен из любой точки сценария. 
Сейчас надо зайти в режим редактирования, чтобы увидеть - глобальный интент или нет. 

http://joxi.net/zANPpzQi8v4yDm

**Comment by Genenko-Svetlana** [comment]
Да, эта метка будет добавлена. Появится со следующими обновлениями, планируем до 01.03.21

**Comment by Genenko-Svetlana** [comment]
@noskoviv проверьте выполнение, пожалуйста.

**Comment by Genenko-Svetlana** [comment]
@noskoviv  проверяйте, пожалуйста.

**Comment by noskoviv** [comment]
Иконка 🌐 на глобальном блоке интентов появляется - отлично.
