### ISSUE TITLE
Логи в смарт-студии от других приложений

### ISSUE THREAD

**Issue by ygerzen** [sberdevices/salute-issues#152]
При работе с одним приложением в смарт-студии в логах сервера отображаются логи от другого аппа. Если апп нагруженный, то логов сыпется много и это мешает отладке других приложений.
Предлагаю разделить логи и внутри аппа показывать логи только от этого аппа.

**Comment by Genenko-Svetlana** [comment]
Срок реализации - 03.03.21

**Comment by ygerzen** [comment]
ок

**Comment by Genenko-Svetlana** [comment]
Срок реализации - 31.03.21

**Comment by Genenko-Svetlana** [comment]
@ygerzen  исправили, проверяйте, пожалуйста.

**Comment by Genenko-Svetlana** [comment]
@ygerzen исправили, проверяйте, пожалуйста.

**Comment by ygerzen** [comment]
Проверил. Теперь стало лучше. Большое спасибо!
