### ISSUE TITLE
Graph - Переход от кнопок к подсказкам

### ISSUE THREAD

**Issue by noskoviv** [sberdevices/salute-issues#153]
- необходимо поменять в гайде информацию про кнопки https://developer.sberdevices.ru/docs/ru/developer_tools/flow/bots_structure/how_al_works/buttons_links
- при функционале кнопок была возможность перемещать кнопки в пределах экрана (менять местами), а сейчас в подсказках такой возможности нет

**Comment by asmalakhov-sberdevices** [comment]
Поведение: при функционале кнопок была возможность перемещать кнопки в пределах экрана (менять местами), а сейчас в подсказках такой возможности нет
Предварительно поправим до 31.03.21

**Comment by Genenko-Svetlana** [comment]
@noskoviv  исправили, проверяйте, пожалуйста.

**Comment by noskoviv** [comment]
исправили что?
саджесты перемещать пока не удается

**Comment by Genenko-Svetlana** [comment]
Да, пока не исправили. Уточняю срок

**Comment by Genenko-Svetlana** [comment]
Скорректирован срок реализации - 3 квартал 2021 (предварительно - август).
Тикет временно закрываем и переносим в отложенные задачи.

**Comment by Nashev** [comment]
А зачем это тикеты тут временно закрываются? Это как-то не правильно... Пока не сделан, должен быть открыт!

**Comment by Genenko-Svetlana** [comment]
Так удобнее. Все отложенные тикеты временно закрыты. Мы следим за сроками реализации задач. Этот тикет мы переоткроем в июле, т.к. работы по нему запланированы в 3 квартале.

**Comment by Nashev** [comment]
Это не удобно, это серьёзное нарушение ожиданий от issue tracker. Не надо так.

У вас вон проект тут ведётся, с канбаном. И есть колонка DEFFERED, держите в ней открытые заявки, и всё будет норм. А этот статус не трогайте, не вводите людей в недоумение.

**Comment by Ibragimow** [comment]
@Nashev привет! Так как доска открытая, формальные процессы предлагаю обсуждать все-таки не здесь. Го в рабочие ЛС.
Мы действительно работаем так, и статистика наша тоже настроена на выстроенные процессы. Если есть необходимость их менять, пиши - готовы к диалогу. Пока работаем, как работали. 
Спасибо!

**Comment by Nashev** [comment]
@Ibragimow, на гитхабе я не вижу ЛС, а в профиле у вас нет контактной информации. Где обсудим? В телеге я тоже @Nashev

О самой необходимости, впрочем, я вроде бы уже всё тут написал... Могу ещё разок, чуть поярче: вы списком открытых issue врёте людям о составе нерешённых проблем, держа кучу нерешённых проблем среди закрытых.

**Comment by Genenko-Svetlana** [comment]
@noskoviv Илья, расскажите, пожалуйста, более подробно о вашем предложении.

**Comment by Nashev** [comment]
Я не тот Илья, но удивлён. Какие подробности тут ещё нужны? Кнопки нужно мочь менять местами, среда разработки этого не даёт.

Думаю, тут помогли бы уточняющие вопросы

**Comment by Genenko-Svetlana** [comment]
@noskoviv исправлено, проверяйте, пожалуйста
