### ISSUE TITLE
Отображение блока СПИСОК в Smartapp Graph

### ISSUE THREAD

**Issue by noskoviv** [sberdevices/salute-issues#154]
**Где нашелся баг**: SberBox, Сбер Салют
**Описание проблемы:** заголовок и подзаголовок блока Список и заголовки и подзаголовки ячеек списка полностью не отображаются. Значение (более 25 символов) в списке ячеек сдвигает заголовок и подзаголовок.
**Проблема воспроизводится у других пользователей?** как минимум у 2х пользователей

**Дополнительная информация:** 
Верстка не корректна.
В Эмуляторе - отображается корректно.
В [документации](https://developer.sberdevices.ru/docs/ru/developer_tools/flow/bots_structure/blocks/list) описано:
_Подзаголовок — поле с текстом, который отображается под заголовком. Рекомендуемая длина подзаголовка — **менее 50 символов**._ 
Для заголовка - корректное отображение - 25 символов
Для Значений в списке ячеек - также можно ограничение в количестве символов указать.  

Скрины:
https://yadi.sk/i/SwV_0nPHbiafhQ сбер салют
https://yadi.sk/i/_8p5yb_hoSlzxA эмулятор в Smartapp Graph 
https://yadi.sk/i/406U6FUa1uPb6Q Box

**Comment by asmalakhov-sberdevices** [comment]
@noskoviv спасибо за замечание, дополним в ближайшее время в документации.

**Comment by Genenko-Svetlana** [comment]
@noskoviv Поправили документацию: 
https://developer.sberdevices.ru/docs/ru/developer_tools/flow/bots_structure/blocks/card
https://developer.sberdevices.ru/docs/ru/developer_tools/flow/bots_structure/blocks/list
Если всё ок, то можно закрыть тикет :)

**Comment by noskoviv** [comment]
Спасибо. Все 👍.
