### ISSUE TITLE
Отображение < 2 кнопок в эмуляторе

### ISSUE THREAD

**Issue by Daniil7davidov** [sberdevices/salute-issues#158]
Не отображается больше двух кнопок в эмуляторе: http://joxi.ru/vAWzVqLTOwvQD2 
Если у меня больше 10-15 кнопок?
Как быть?

**Comment by Genenko-Svetlana** [comment]
Ориентировочный срок реализации - 22.03.21

**Comment by Genenko-Svetlana** [comment]
@Daniil7davidov Проверяйте, если всё ок - закройте, пожалуйста, задачу.

**Comment by Genenko-Svetlana** [comment]
Срок реализации до 31.03.21

**Comment by Genenko-Svetlana** [comment]
@Daniil7davidov проверяйте, пожалуйста. Реализовано.

**Comment by Genenko-Svetlana** [comment]
@Daniil7davidov проверяйте, пожалуйста. Реализовано.
