### ISSUE TITLE
Не работает команда log() в Code

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#159]
**Где нашелся баг**: Code
**Описание проблемы**: Не работает команда log() в Code
**Проблема воспроизводится у других пользователей?** да

**Comment by asmalakhov-sberdevices** [comment]
@and7ey подскажи, пожалуйста, сейчас даже если использовать $jsapi.log()
даже в этом варианте у вас не работает?

**Comment by and7ey** [comment]
Так работает, спасибо! (где ж вы раньше были? :)

https://developer.sberdevices.ru/docs/ru/developer_tools/ide/log/server_logs
https://developer.sberdevices.ru/docs/ru/developer_tools/ide/JS_API/built_in_functions/log(message)
- тут надо тогда поправить, в примере, например, `log` указано без `$jsapi.`

**Comment by Genenko-Svetlana** [comment]
@Lytkini Илья, посмотри, пожалуйста. Нужно поправить пример.

**Comment by Genenko-Svetlana** [comment]
@and7ey Добрый день! 
Пример исправлен тут: https://developer.sberdevices.ru/docs/ru/developer_tools/ide/JS_API/built_in_functions/log(message)

Вопрос решен? Если, да - то можно закрыть тикет :)

**Comment by and7ey** [comment]
Решен, закрываем. Спасибо.
