### ISSUE TITLE
Мультизагрузка файлов в Смарт-студии в Контент

### ISSUE THREAD

**Issue by ygerzen** [sberdevices/salute-issues#160]
**Где пригодится фича**: в Смарт-студии
**Описание фичи**: сейчас когда нужно загрузить в Контент Смарт-студи много картинок, то приходится их загружать поштучно. Это много лишних однотипных действий! Предлагаю сделать загрузку всех выбранных файлов, а не только одного.
**Дополнительная информация**: при копировании хешей из Контента, приходится вручную закрывать уведомления от предыдущих копирований, т.к. они перекрывают ссылку на хеш.

**Comment by asmalakhov-sberdevices** [comment]
Добавили в бэклог. Планируем сделать до 31.03.

**Comment by Genenko-Svetlana** [comment]
Корректировка срока реализации - до 31.05.21

**Comment by Genenko-Svetlana** [comment]
@ygerzen  реализовано
