### ISSUE TITLE
Ссылка на описание блока КОД в Smartapp Graph

### ISSUE THREAD

**Issue by noskoviv** [sberdevices/salute-issues#161]
**Где нашелся баг**: Smartapp Graph
**Описание проблемы**: битая ссылка на описание (на документацию).
Проблема воспроизводится у других пользователей? -

Дополнительная информация:
https://yadi.sk/i/fEIB7qgeuGF49w
Ссылка сейчас: https://smartapp-code.sberdevices.ru/documentation/docs/ru/developer_tools/flow/bots_structure/blocks/jscode
Должна быть: https://developer.sberdevices.ru/docs/ru/developer_tools/flow/bots_structure/blocks/jscode

**Comment by Genenko-Svetlana** [comment]
Срок реализации - 11.03.21

**Comment by Genenko-Svetlana** [comment]
@noskoviv  реализовано, проверьте, пожалуйста

**Comment by noskoviv** [comment]
поправлено.
спасибо
