### ISSUE TITLE
Новое тип события «переход по ссылке»

### ISSUE THREAD

**Issue by ygerzen** [sberdevices/salute-issues#162]
**Где пригодится фича**: везде, где есть возможность отправить пользователя по ссылке
**Описание фичи**: идея в том, что предлагаю пользователю перейти по ссылке из смартапа, мы теряем с пользователем связь, когда он возвращается обратно в смартап. При наличии нового типа события "переход по ссылке" можно будет как-то реагировать на событие и тем самым улучшить пользовательский опыт и сценарии. 
**Дополнительная информация**: например, можно на событие "переход по ссылке" делать разные реакции: выход из аппа; вывод сообщения/саджестов; предлагать посмотреть другие ссылки и т.п.

**Comment by talagaev** [comment]
Не понимаю, зачем по переходу по ссылке выводить саджесты. 
кейс:
1 Пользоввателю предлагается перейти по ссылке 
2 пользователь переходит по ссылке
зачем ему видеть саджесты перед уходом?
