### ISSUE TITLE
Необходимы правки в документации

### ISSUE THREAD

**Issue by noskoviv** [sberdevices/salute-issues#165]
Кнопок нет - есть саджесты (подсказки) 

Заменить документацию с учетом функционала - пересмотреть документацию (сменить картинки).

ИСТОЧНИК
https://developer.sberdevices.ru/docs/ru/developer_tools/flow/bots_structure/how_al_works/buttons_links

**Comment by Genenko-Svetlana** [comment]
Срок реализации - 12.03.21

**Comment by Genenko-Svetlana** [comment]
@noskoviv  проверьте, пожалуйста.

**Comment by Genenko-Svetlana** [comment]
@noskoviv проверьте, пожалуйста.

**Comment by noskoviv** [comment]
спасибо
