### ISSUE TITLE
Конвертация аудио и картинок на стороне Studio

### ISSUE THREAD

**Issue by iqgamesru** [sberdevices/salute-issues#166]
При загрузке аудио и картинок нужно конвертировать все в определенный формат, что доставляет неудобства и отнимает время. Было бы очень хорошо, если бы Студия сама конвертировала контент, хотя-бы в рамках одного формата. Например, у меня есть WAV файл, но он не подходит по частоте сэмплов, приходится WAV конвертировать в WAV и менять частоту. Хотелось бы этого избежать. Но в идеале, конечно, конвертировать и другие форматы.

**Comment by Genenko-Svetlana** [comment]
Сложная и достаточно трудоемкая реализация, при этом потребность закрывается множеством имеющихся внешних продуктов. Например, инструменты рода ffmpeg, позволяющие, в том числе, работать с аудио-форматами и их ресемплированием.
В беклог на 21 год, не планируется
