### ISSUE TITLE
Проблемы с синтезом речи для озвучивания буквы

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#17]
Примеры TTS с совсем плохо звучащих букв:
```
<speak>Буква <break time="200ms" />«в».</speak>
<speak>Буква <break time="200ms" />«б».</speak>
<speak>Буква <break time="200ms" />«г».</speak>
<speak>Буква <break time="200ms" />«д».</speak>
<speak>Буква <break time="200ms" />«е».</speak>
<speak>Буква <break time="200ms" />«ж».</speak>
<speak>Буква <break time="200ms" />«з».</speak>
<speak>Буква <break time="200ms" />«л».</speak>
<speak>Буква <break time="200ms" />«м».</speak>
<speak>Буква <break time="200ms" />«т».</speak>
<speak>Буква <break time="200ms" />«ы».</speak>
<speak>Буква <break time="100ms" />«я».</speak>
```

**Comment by RulevAnton** [comment]
1. Почти все буквы фиксятся с помощью ssml разметки с помощью тега spell-out, который проговаривает слова по буквам по типу:
<speak>Букву <break time="200ms" /> 
<say-as interpret-as="spell-out"> в </say-as>
<break time="100ms" /> уже называли. Её нет в этом слове. Нужна новая версия.</speak>
Даже Ъ и ь раскрывает :slightly_smiling_face:
2. В основном остаются проблемы с буквами:
е
ё
и
й
ы

**Comment by RulevAnton** [comment]
Для оставшихся букв можно использовать такое обходное решение:
1. "е"
<speak>Букву <break time="200ms" /> 
<say-as interpret-as="spell-out"> ее </say-as>
<break time="100ms" /> уже называли. </speak>

2. "ё"
<speak>Букву <break time="200ms" /> 
<say-as interpret-as="spell-out"> йо </say-as>
<break time="100ms" /> уже называли. </speak>

3. "и" - вроде и так норм звучит, но можно подтюнить так:
<speak>Букву <break time="200ms" /> 
<say-as interpret-as="spell-out"> ии </say-as>
<break time="100ms" /> уже называли. </speak>

4. "й"
<speak>Букву <break time="200ms" /> 
<say-as interpret-as="spell-out"> ий </say-as>
<break time="100ms" /> уже называли. </speak>
или 
<speak>Букву <break time="200ms" /> 
<say-as interpret-as="spell-out"> ии </say-as> краткое
<break time="100ms" /> уже называли. </speak>

5. "ы"
<speak>Букву <break time="200ms" /> 
<say-as interpret-as="spell-out"> ыы </say-as>
<break time="100ms" /> уже называли. </speak>

**Comment by vkycniichai** [comment]
@subnetsRU уточните, помогли ли рекомендации, приведенные выше?

**Comment by subnetsRU** [comment]
Ну с такой разметкой стало получше, конечно, но не идеально.
Те же "е"и "и" у Джой звучат именно как две буквы.

Вообщем если вас устраивает такое произношение букв, то давайте я оставлю приведённую вами ssml разметку.

**Comment by RulevAnton** [comment]
@subnetsRU распознавание отдельных букв будет улучшаться со временем, а пока можно пользоваться этим обходным решением.

Попробовал букву "е" для Джой:
`<speak>Букву <break time="200ms" /> 
<say-as interpret-as="spell-out"> ее </say-as>
<break time="100ms" /> уже называли. </speak>`

У меня звучит вот так:

[Uploading 3b86f1df-b5d8-4e6e-af79-65b214b1f331.wav…]()

**Comment by subnetsRU** [comment]
Мой контакт в телеге @VirusNet, но смысла слать запись есть только в том случае если у вас какая-то другая Джой.
Если она штатная, то собственно звучит и у вас и у меня она одинаково.
И для моего слуха "ее" звучит как две буквы. Протестил на жене - она говорит что слышит одну.

**Comment by subnetsRU** [comment]
Там что-то совсем поломалось у Джой.

https://t.me/smartapp_studio/7076

**Comment by RulevAnton** [comment]
ага, наблюдаем, бага есть TTSQA-1226, Будем стараться исправить к след релизу. Ориентир через неделю-две.

**Comment by RulevAnton** [comment]
Исправление поедет на прод сегодня в ночь.

**Comment by subnetsRU** [comment]
Похоже исправилось, т.к. повторить багу сходу не получилось. Надеюсь, что и не получится.
