### ISSUE TITLE
Ассистент читает текст с задержкой.

### ISSUE THREAD

**Issue by iqgamesru** [sberdevices/salute-issues#170]
Если поменять способ взаимодействия с ассистентом с голоса на саджесты, то очень часто появляется текст следующего сценария, а ассистент молчит. Голос появляется спустя какое-то время, около 10 секунд.

Воспроизводится так: прерываем реплику ассистента саждестом на более менее длинном тексте. Воспроизводится почти всегда в приложении салют и сбербоксе.

**Comment by talagaev** [comment]
@sdtestersd  проверьте пжл

**Comment by iqgamesru** [comment]
Все еще воспроизводится, вот запись экрана на примере игры "Музыкальный перевод": https://disk.yandex.ru/i/Nl_APPtyJvZXIA

Прерываем реплику ассистента саджестом, появляется новый сценарий и тишина, через несколько секунд начинается речь.

**Comment by sdtestersd** [comment]
Дефект завели, воспроизводится в салюте и на иос и на андроид

**Comment by Genenko-Svetlana** [comment]
Срок реализации - ориентировочно 30.04.21

**Comment by Genenko-Svetlana** [comment]
@sdtestersd проверьте, пожалуйста

**Comment by sdtestersd** [comment]
В текущем проме не воспроизводится

**Comment by Genenko-Svetlana** [comment]
@sdtestersd проверьте, пожалуйста

**Comment by talagaev** [comment]
фиксы уже в майских релизах 

https://sbtatlas.sigma.sbrf.ru/jira/browse/ATHENADEV-4881 https://sbtatlas.sigma.sbrf.ru/jira/browse/ATHENADEV-4614
