### ISSUE TITLE
В салюте нельзя оплатить привязанной картой

### ISSUE THREAD

**Issue by iqgamesru** [sberdevices/salute-issues#171]
В платёжном сценарии в приложении "Салют" нельзя оплатить привязанной картой, приходится каждый раз вводить данные карты. В профиле карта привязана, в сбербоксе работает нормально.

**Comment by Genenko-Svetlana** [comment]
Да, на iOS будет реализовано до 31.03.21

**Comment by Genenko-Svetlana** [comment]
@iqgamesru проверьте, пожалуйста, уже должно работать.

**Comment by iqgamesru** [comment]
Заработало, спасибо!
