### ISSUE TITLE
Не открывается платежный сценарий на ios

### ISSUE THREAD

**Issue by iqgamesru** [sberdevices/salute-issues#172]
Не получается совершить покупку при помощи iphone. Не открывается канвас платежного сценария, хотя само приложение запускается, можно взаимодействовать голосом, но нет картинки. 
Наблюдается на iOS 14.3, другие не проверял.

**Comment by Genenko-Svetlana** [comment]
Да, на iOS будет реализовано до 31.03.21

**Comment by Genenko-Svetlana** [comment]
@iqgamesru  проверьте, пожалуйста, уже должно работать.

**Comment by iqgamesru** [comment]
Да, сейчас работает.
