### ISSUE TITLE
Не работает авторизация по sber id в платежном сценарии в Салюте

### ISSUE THREAD

**Issue by iqgamesru** [sberdevices/salute-issues#173]
При попытке авторизоваться по сбер id в платежном канвасе в приложении Салют, после подтверждения входа в сбол всегда получаю ошибку: "Не удалось завершить вход по Сбер id". 

А так же при попытке выбрать оплату sber pay сразу получаю ошибку:

 "При загрузке веб-страницы sberpay://invoicing/v2?bankInvoiceId=5dbd99bbc8814cfebe46807634b5eaca&orderNumber=6e8dd630-a331-7196-8a5e-a862022ad738 произошла ошибка по следующим причинам:

net::ERR_UNKNOWN_URL_SCHEME"

**Comment by Genenko-Svetlana** [comment]
@iqgamesru добрый день! Добавьте, пожалуйста, подробности (скрины, видео).

**Comment by iqgamesru** [comment]
Добрый день!
Видео во вложении.
Комментарий: сначала я нажимаю на кнопку "Оплатить Sber Pay", получаю ошибку. Далее пробую войти по sber id, но после подтверждения опять получаю ошибку. Это повторяется всегда, не получается оплатить вообще никак, кроме ввода данных карты.

https://user-images.githubusercontent.com/78853384/110373808-f9bc1200-8060-11eb-9b5b-8708f8365705.mp4

**Comment by Genenko-Svetlana** [comment]
@iqgamesru проверьте, пожалуйста, сохраняется ли проблема?

**Comment by Genenko-Svetlana** [comment]
@iqgamesru проверьте, пожалуйста, сохраняется ли проблема?

**Comment by iqgamesru** [comment]
Проблема вчера была устранена, спасибо большое, все работает сейчас!
