### ISSUE TITLE
Добавить прямые ссылки на смартаппы

### ISSUE THREAD

**Issue by DenisNP** [sberdevices/salute-issues#174]
**Где пригодится фича**: 
1. В тестировании, давать другим ссылку на свой смартап
2. В рекламе и продвижении смартапов
3. В продвижение Салюта среди пользователей Сбера, т.к. не все о нём знают и пробовали пользоваться

**Описание фичи**: 
Дать возможность создавать прямые ссылки на смартапп, как минимум в СБОЛ (потому что он уже и так у всех установлен). Нажатие на ссылку должно открывать СБОЛ и вызывать сразу Салют с запущенным смартапом.

**Дополнительная информация**: 
Почти наверняка подобная схема уже и так поддержана у вас в приложениях, достаточно предоставить документацию к ней. В худшем случае подойдут даже ссылки со схемой приложения, например `sber://...`, но лучше конечно чтобы это были ссылки для внешнего интернета.

В совсем идеальном сценарии в ссылке ещё и передавать какую-то команду для смартапа.

**Comment by Genenko-Svetlana** [comment]
Планируем подобные доработки во 2 кв. 2021.
Пока тикет временно закрываем и переносим в отложенные задачи.

**Comment by Genenko-Svetlana** [comment]
Возвращаем в работу

**Comment by talagaev** [comment]
мы такой инструмент предоставили коллегами из смартмаркета

**Comment by DenisNP** [comment]
@talagaev а можно ссылку на документацию по ссылкам?

**Comment by waxerdima** [comment]
@DenisNP например так [companionapp://navigation?pageId=assistant&text=запусти кофемания](url)

**Comment by DenisNP** [comment]
@waxerdima не подходит, потому что при отсутствии установленного Салюта (а это у большинства людей) у таких ссылок нет фолбэка на установку. Тогда лучше [вот такую](https://catalog.smartmarket.sber.ru/apps/6d76832f-8878-414e-bb5a-4c30a8e425a1/) ссылку давать.
