### ISSUE TITLE
Загрузка картинок в сценарий динамически не работает на SberPortale и на SberBox 

### ISSUE THREAD

**Issue by noskoviv** [sberdevices/salute-issues#175]
ОПИСАНИЕ
Реализация через Graph (через блок JS код) или Code (через script).
https://developer.sberdevices.ru/docs/ru/developer_tools/ide/bot_answers/message_types/#image

script:
       $response.replies = $response.replies || [];
       $response.replies.push({
         type: "image",
         imageUrl: $session.imageurl,
         hash: $session.imagehash,
       })

или

image: {{$session.imageurl}} || hash = {{$session.hash}}

imageurl и hash - загружаем из гугл таблицы, которые первоначально получаем при размещении изображений в разделе КОНТЕНТ

СУТЬ ПРОБЛЕМЫ
**По динамическим значениям урл и хэш не отображаются изображения в SberBox и SberPortal.**
Через раздел ТЕСТИРОВАНИЯ в SmartApp Studio и в приложении САЛЮТ динамически подгружаемые картинки отображаются.

**Comment by asmalakhov-sberdevices** [comment]
В примере была лишняя запятая после $session.imagehash 
вариант в script сейчас работает
```
        script: 
           $response.replies = $response.replies || [];
           $response.replies.push({
             type: "image",
             imageUrl: $session.imageurl,
             hash: $session.imagehash
            })
```

Вариант отправки динамически через тэг image сейчас пока сломан, будем исправлять. Ориентировочно до конца марта возьмем в работу и исправим работу тэга.

**Comment by Genenko-Svetlana** [comment]
@asmalakhov-sberdevices  Антон, спасибо.
Срок реализации - до 31.03.21.

**Comment by waxerdima** [comment]
Добрый день, работа по данному вопросу ведется, срок исполнения конец 2021.

**Comment by Genenko-Svetlana** [comment]
@noskoviv исправлено, проверяйте, пожалуйста
