### ISSUE TITLE
Кол-во уникальных пользователей на графиках Graph и Code - разное

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#182]
**Где нашелся баг**: Graph и Code
**Описание проблемы**: Кол-во уникальных пользователей на графиках Graph и Code - разное
**Проблема воспроизводится у других пользователей?** не знаю
**Дополнительная информация**: примеры высланы https://t.me/ketkin7 в телеграм

**Comment by Genenko-Svetlana** [comment]
Срок реализации - 02.04.2021

**Comment by Genenko-Svetlana** [comment]
@and7ey проверьте, пожалуйста.

**Comment by and7ey** [comment]
Проверил. Не совпадает. Сравнивал статистику за вчера и за сегодня.

**Comment by Genenko-Svetlana** [comment]
Внедрение отложено на 06.04.21

**Comment by Genenko-Svetlana** [comment]
@and7ey проверьте, пожалуйста.

**Comment by Genenko-Svetlana** [comment]
@and7ey проверьте, пожалуйста.
