### ISSUE TITLE
Сбербокс и отображение каталога

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#19]
1. На главном экране "запусти каталог" очень много места съедается просто так.
Даже на большом экране
![catalog_1](https://user-images.githubusercontent.com/18159237/97555039-aa960e80-19e8-11eb-951e-e4ecec04c8a6.png)
Для навыков очень мало места и приходится много листать.

2. При нажатии "вниз" с экрана п.1 мы попадаем не на экран с разделами каталога, а в список умений сбербокса:
![catalog_2](https://user-images.githubusercontent.com/18159237/97555308-06609780-19e9-11eb-88bf-d437ce697e0f.png)
Что не только странно, но и довольно неожиданное место для отображения этого дела, т.к. мы же в разделе "каталог", а не "справка".
Чтобы наконец добраться до раздела с каталогом нужно ещё раз нажать "вниз".

Предлагается подумать над этим.

**Comment by Genenko-Svetlana** [comment]
В новой версии каталога планируется поднять блок с категориями наверх, добавить новые подборки на главную, часть из них будет редакторскими, часть будет собираться автоматически

**Comment by Avalpetrova** [comment]
Привет! Согласна с тем, что первый экран малоинформативен. Мы это учитываем при разработке нового дизайна. В следующей версии это не поправится, но в будущих точно. По поводу экрана с категориями, мы его поднимем в следующей версии каталога. Что касается "списка умений сбербокса", все приложения в каталоге это расширение умений ассистента и сбербокса. И этот экран задумывался как дополнительное обучение пользователя голосовому запуску приложений. Сейчас мы собираем фидбэк и проверяем различные гипотезы, касающиеся этого экрана. Возможно, он переедет в другое место. 
Спасибо за комменты, все по делу!
