### ISSUE TITLE
Не работает pull изменений из репозитория

### ISSUE THREAD

**Issue by Valkinaz** [sberdevices/salute-issues#190]
**Где нашелся баг**: Smartapp-Code
**Описание проблемы**: Не получается подлить новый код из репозитория
**Проблема воспроизводится у других пользователей?** не знаю
**Дополнительная информация**: 
`{"error":"editorbe.repository.error.invalid_remote","message":"External repository is not available. Make sure the repository URL is correct","args":{"message":"Invalid remote: origin","class":"org.eclipse.jgit.api.errors.InvalidRemoteException"}}`
https://i.imgur.com/OSNiJho.jpeg
URL репозитория верный, еще в пятницу все работало

**Comment by Valkinaz** [comment]
Скачивание архива проекта или загрузка архива тоже не работает
`<ErrorResponse>
<error>Не удалось выполнить запрос. Возникла внутренняя ошибка.</error>
</ErrorResponse>`

**Comment by waxerdima** [comment]
@Valkinaz двухфакторную авторизация в гитхабе не включали?

**Comment by Valkinaz** [comment]
Нет, выключена.
По изначальной проблеме: заработало минут 10-15 назад.

**Comment by Genenko-Svetlana** [comment]
@Valkinaz Попробуйте, пожалуйста, завести новый проект, но с тем же репозиторием и теми же данными для авторизации.
После таких действий все должно заработать )

**Comment by Valkinaz** [comment]
@Genenko-Svetlana так уже заработало, я писал в комментарии выше. Пока больше не повторялось.

**Comment by Genenko-Svetlana** [comment]
Чудесно. Закрываю задачу
