### ISSUE TITLE
Сделать ссылку на доступ к аналитике смартапов

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#192]
**Где пригодится фича**: https://smartapp-studio.sberdevices.ru/
**Описание фичи**: Нужно сделать по ссылке выше для каждого смартапа ссылку на переход в аналитику.
**Дополнительная информация**: Сейчас процесс отслеживания аналитики очень не удобен. Надо заходить отдельно в каждый смартап, куда в нем идти - зависит от того как он реализован (у Графа одна логика, у Кода - другая). Нужно вспоминать, что почему-то раздел Аналитика находится в Разработке. Итого - несколько кликов чтобы добраться до аналитики вместо одного.

**Comment by Genenko-Svetlana** [comment]
Есть в планах. Срок реализации - 3 квартал 2021.
Тикет временно закрываем и переносим в отложенные задачи.

**Comment by Genenko-Svetlana** [comment]
@and7ey доработки по аналитике произведены

**Comment by and7ey** [comment]
Напишите, пожалуйста, что изменили. Я улучшений не нашел :(.

**Comment by filomat** [comment]
Появился новый раздел с аналитикой по смартапу независимо от способа реализации сценарного бекенда смартапа.
Новый раздел доступен сразу из проекта "SmartApp" в его боковой панели.
Для новых пользователей, ещё не посещавших новый раздел, он подсвечен зеленой точкой =)

**Comment by and7ey** [comment]
Спасибо. Тогда это не покрывает вопрос, который задан в этом issue. Допустим, у вас два смартапа и нужно посмотреть статистику по ним двоим. Сколько шагов (кликов) нужно сделать, чтобы увидеть статистику? 
Нужно решение, которое позволит из аналитики одного смартапа сразу переходить в аналитику другого. Или вынести ссылку на аналитику на https://smartapp-studio.sberdevices.ru/ (как указано в issue).

**Comment by xoxulin** [comment]
https://developers.sber.ru/docs/ru/salute/studio/smartapp/metrics - метрики смартапов теперь в одном интерфейсе. Старые ссылки в issue больше не являются целевыми и редиректят на новый адрес. Аналитика предоставляется  теперь по всем типам смартапов и всем типам сценарного бекенда. Ранее аналитика была доступна только внутри сценариев Graph и  Code.
