### ISSUE TITLE
Удаление проектов в smartapp-code

### ISSUE THREAD

**Issue by noskoviv** [sberdevices/salute-issues#196]
**Отсутствует** функционал удаления проектов в https://smartapp-code.sberdevices.ru/
Автоматически созданы были несколько проектов, которые не отображаются через https://smartapp-studio.sberdevices.ru/ 
Надо удалить эти проекты, так как у них совпадают имена и не понятно с каким работаешь.

**Comment by Genenko-Svetlana** [comment]
Планируем реализовать во втором квартале 2021

**Comment by noskoviv** [comment]
спасибо - работает
