### ISSUE TITLE
[Smartapp Code/Brain] Проблема разбора лемм

### ISSUE THREAD

**Issue by DenisNP** [sberdevices/salute-issues#198]
### Где нашелся баг: 
Проект **Smartapp Code**, который использует **Smartapp Brain** для морфологического анализа.

### Описание проблемы:
**Код Code:**
```js
theme: /

    state:
        q!: * ~ярче *
        a: Вы сказали словоформу слова Ярче
        
    state:
        q!: * ~больше *
        a: Вы сказали словоформу слова Больше

    state: Fallback
        event!: noMatch
        a: Не понял
```

**Фактический диалог:**

>_Пользователь:_ ярче	
>_Бот:_ Не понял
>
>_Пользователь:_ больше	
>_Бот:_ Вы сказали словоформу слова Больше

**Ожидаемый результат:**
С обоими словами разбор ведёт себя одинаково: либо оба проходят, либо оба нет

### Дополнительно
```js
theme: /

    state:
        q!: * ~яркий *
        a: Вы сказали словоформу слова Яркий
        
    state:
        q!: * ~большой *
        a: Вы сказали словоформу слова Большой

    state: Fallback
        event!: noMatch
        a: Не понял
```

>_Пользователь:_ ярче	
>_Бот:_ Не понял
>
>_Пользователь:_ больше	
>_Бот:_ Не понял

**Ожидание:**
_Больше_, _ярче_ это не только наречия, но и формы прилагательных. Зализняк считает, что должно срабатывать во втором случае тоже.

**Comment by IKRodygina** [comment]
Параметр **tokenizerEngine** в настройках NLU - токенизатор, который будет выполнять токенизацию и лемматизацию текста.

Изменить токенизатор в проекте можно в **_Настройки проекта_** / _**Настройки NLU**_ / _**Расширенные настройки NLU**_:
https://developer.sberdevices.ru/docs/ru/developer_tools/ide/NLU_core/advanced_classifer_settings

Возможные значения параметра **tokenizerEngine**:

- **udpipe** -- используется по умолчанию
- **mystem** -- используется для миграции проектов с паттернов на CAILA
- **morphsrus** -- используется для миграции проектов с паттернов на CAILA


1)  При установленном **tokenizerEngine** = **morphsrus** при:
```python
    
theme: /

    state: 
        q!: * ~ярче *
        a: Вы сказали словоформу слова Ярче
        
    state: 
        q!: * ~больше *
        a: Вы сказали словоформу слова Больше

    state: Fallback
        event!: noMatch
        a: Не понял
```
не проходят оба варианта (как в ожидаемом результате):

```
Пользователь: ярче
Бот: Не понял

Пользователь: больше
Бот: Не понял
```

2) При установленном **tokenizerEngine** = **udpipe** или **mystem** при:
```python
    
theme: /

    state: 
        q!: * ~яркий *
        a: Вы сказали словоформу слова Яркий
        
    state: 
        q!: * ~большой *
        a: Вы сказали словоформу слова Большой

    state: Fallback
        event!: noMatch
        a: Не понял
```
не проходят оба варианта (как в ожидаемом результате):

```
Пользователь: ярче
Бот: Не понял

Пользователь: больше
Бот: Не понял
```

**Comment by Genenko-Svetlana** [comment]
@DenisNP посмотрите, пожалуйста, рекомендации выше

**Comment by Genenko-Svetlana** [comment]
@DenisNP посмотрите, пожалуйста, рекомендации выше

**Comment by DenisNP** [comment]
Да, так работает. Но это половина решения: поведение теперь предсказуемое, но предсказуемо неправильное. Почему на `~ярче` не пропускает слово _ярче_ ?

**Comment by Genenko-Svetlana** [comment]
@IKRodygina

**Comment by Genenko-Svetlana** [comment]
@IKRodygina посмотрите доп. комментарий разработчика, пожалуйста.

**Comment by Genenko-Svetlana** [comment]
@asmalakhov-sberdevices

**Comment by Genenko-Svetlana** [comment]
Взяли в бэклог. Срок реализации - до 31.12.2021
Тикет временно закрываем и переносим задачу в отложенные.
