### ISSUE TITLE
[Smartapp Code] Обновить версию JavaScript

### ISSUE THREAD

**Issue by DenisNP** [sberdevices/salute-issues#199]
**Где пригодится фича**: 
Всем разработчикам, которые делают приложения на Smartapp Code

**Описание фичи**:
Обновите, пожалуйста, версию JavaScript в вашем интерпретаторе, чтобы использовать `let/const` и разные удобные фишки, такие как `spread operator`, а может даже промисы и `async/await`.

**Важный дополнительный плюс:** можно будет подключать современные библиотеки без транспиляции.

**Comment by Genenko-Svetlana** [comment]
@DenisNP в ближайшее время реализация не планируется.
Тикет временно закрываем и переносим в отложенные задачи.
