### ISSUE TITLE
[Smartapp Studio] Проблема сброса валидации Активационных имен в панели вывода на Модерацию

### ISSUE THREAD

**Issue by xoxulin** [sberdevices/salute-issues#20]
"Флаг" ошибки в активационном имени не сбрасывается.
* Жмём "+Добавить имя"
* Вводим название со спецсимволом и получаем ошибку, что приводит к появлению иконки "внимание" перед "Активационные имена" и отключением кнопки "отправить на модерацию"
* редактируем или удаляем строку с ошибкой в имени
* иконка "внимание" и кнопка "отправить на модерацию" так и остаются
* ок, переходим какой нить другой раздел и возвращаемся обратно
* иконка "внимание" и кнопка "отправить на модерацию" так и остаются

помогает только релоад всей страницы

**Comment by subnetsRU** [comment]
Видео с этой проблемой: https://t.me/smartapp_studio/3187

**Comment by filomat** [comment]
Исправили

**Comment by subnetsRU** [comment]
Подтверждаю. Повторить баг не удалось. Сейчас статус корректно сбрасывается.

**Comment by xoxulin** [comment]
@subnetsRU закрываю проблему
