### ISSUE TITLE
[Smartapp Code] Команда smart_app_data не работает при получении события с фронта

### ISSUE THREAD

**Issue by DenisNP** [sberdevices/salute-issues#200]
### Где нашелся баг:
**Smartapp Code**, хотя возможно это баг **Assistant Client**

### Описание проблемы:
Canvas-приложение, бэкенд на **Code**. Я отправляю данные на фронт с помощью добавление элемента в массив `context.response.replies`, у которого `type = 'raw'`. Дальше я использую команду `smart_app_data`.

Этот код выполняется на бэкенде в среде **Code**:
```js
/**
 * Функция получает в ответе элемент из массива replies с type = 'raw'
 * а если такого нет, то создаёт его и возвращает
 */
function getRawBody() {
    var context = $jsapi.context();
    context.response = context.response || {};
    context.response.replies = context.response.replies || [];
    
    for (var i = 0; i < context.response.replies.length; i++) {
        var reply = context.response.replies[i];
        if (reply.type === 'raw') {
            reply.body = reply.body || {};
            reply.body.items = reply.body.items || {};
            return reply.body;
        }
    }
    
    // элемента с типом 'raw' нет вообще, добавим его
    var rawReply = {
        type: 'raw',
        body: { items: [] },
    };
    context.response.replies.push(rawReply);
    
    return rawReply.body;
}

/**
 * Функция отправляет данные на фронт в Assistant Client
 */ 
function sendToFront(action, data){
    var command = {
        type: "smart_app_data",
        action: action,
        data: data
    };
    
    getRawBody().items.push({ command: command });
}
```

А вот так идёт отправка команды. Посмотрите на узел `Data`, там есть реакция и на голосовую фразу, и на нажатие кнопку на фронте:
```js
require: functions.js

theme: /

    state: Enter
        q!: $regexp</start>
        a: Привет!
        
    state: Data
        q!: * отправ* [мне] данные *
        event!: button_pressed
        a: Отправляю на фронт
        script:
            sendToFront('message_from_backend', {});

    state: Fallback
        event!: noMatch
        a: Не понимаю.
```

**Ожидаемая реакция:**
Во всех случаях смартапп отвечает голосом "Отправляю на фронт", а в событие `assistant.on('data', ...)` приходит команда `message_from_backend`.

**Фактическая реакция:**
Во всех случаях смартапп отвечает голосом "Отправляю на фронт"! То есть команда доходит всегда, узел `state: Data` вызывается всегда. Но

* если говорить голосом: фронтенд получает команду `message_from_backend`.
* если вызвать этот узел событием с фронта: фронтенд **НЕ** получает команду `message_from_backend`, колбэк `assistant.on('data', ...)` не триггерится.

**С фронта событие вызывается так:**
```js
assistant.sendData({ action: { action_id: 'button_pressed', payload: { } } }, () => {});
```

<details>
<summary>Лог ответа при вводе голосом</summary>

>Send webhook response:{ "messageId" : 1618490225880, "sessionId" : "bcce2693-f7e7-3bcc-8cc0-6db512a2a862", "messageName" : "ANSWER_TO_USER", "uuid" : { "userChannel" : "B2C", "sub" : "Nu7OZfnv0JeIq8QPT01F0VHkW6D4sOgRZvoEH+RMoI9sxYnCclAevFA9+AssEs1pAnJhXdIW8y8dX+V2FZmHo13vUumhw+EOY08zqc1joHugMLHLI+dipB39L/JGw320urFXbrwhzZGF5VCQX/rjx5rOr/LSoWwihLU7I6d4Ni0=", "userId" : "webdbg_userid_knwdbrfcw6k3isyjazkdoi" }, "payload" : { "applicationId" : "4ec49505-6588-47c8-b7fe-2d0d0f0a783a", "appversionId" : "9523ea44-9f34-4c4f-9e1e-d4f912471f62", "projectName" : "dfa6174c-2ddf-460d-b081-357283ec65c6", "original_intent" : "p2p", "intent_meta" : { }, "device" : { "platformType" : "WEBDBG", "platformVersion" : "1.0", "surface" : "SBERBOX", "surfaceVersion" : "2.11.8", "features" : { "appTypes" : [ "DIALOG", "WEB_APP" ] }, "capabilities" : { "screen" : { "available" : true, "height" : 862, "width" : 1391 }, "speak" : { "available" : true } }, "deviceId" : "", "deviceManufacturer" : "", "deviceModel" : "", "additionalInfo" : { "host_app_id" : "ru.sberbank.sdakit.demo", "sdk_version" : "20.09.1.3576" } }, "app_info" : { "projectId" : "e5fd0e60-eb9e-4b46-a733-d54e21e463fe", "applicationId" : "4ec49505-6588-47c8-b7fe-2d0d0f0a783a", "appversionId" : "9523ea44-9f34-4c4f-9e1e-d4f912471f62", "systemName" : null, "frontendEndpoint" : "https://mfsigns.justanother.app", "frontendType" : "WEB_APP" }, "selected_item" : { }, "strategies" : { "last_call" : null }, "asr" : { }, "client_profile" : "***", "pronounceText" : "Отправляю на фронт", "items" : [ { "bubble" : { "text" : "Отправляю на фронт" } }, { "command" : { "type" : "smart_app_data", "action" : "message_from_backend", "data" : { } } } ], "auto_listening" : true }}

</details>

<details>
<summary>Лог ответа при получении события</summary>

>Send webhook response:{ "messageId" : 1618490426841, "sessionId" : "ba0a8152-08da-32c6-8237-538e0a370b4b", "messageName" : "ANSWER_TO_USER", "uuid" : { "userChannel" : "B2C", "sub" : "Nu7OZfnv0JeIq8QPT01F0VHkW6D4sOgRZvoEH+RMoI9sxYnCclAevFA9+AssEs1pAnJhXdIW8y8dX+V2FZmHo13vUumhw+EOY08zqc1joHugMLHLI+dipB39L/JGw320urFXbrwhzZGF5VCQX/rjx5rOr/LSoWwihLU7I6d4Ni0=", "userId" : "webdbg_userid_knwdbrfcw6k3isyjazkdoi" }, "payload" : { "applicationId" : "4ec49505-6588-47c8-b7fe-2d0d0f0a783a", "appversionId" : "9523ea44-9f34-4c4f-9e1e-d4f912471f62", "projectName" : "dfa6174c-2ddf-460d-b081-357283ec65c6", "device" : { "platformType" : "WEBDBG", "platformVersion" : "1.0", "surface" : "SBERBOX", "surfaceVersion" : "2.11.8", "features" : { "appTypes" : [ "DIALOG", "WEB_APP" ] }, "capabilities" : { "screen" : { "available" : true, "height" : 862, "width" : 1391 }, "speak" : { "available" : true } }, "deviceId" : "", "deviceManufacturer" : "", "deviceModel" : "", "additionalInfo" : { "host_app_id" : "ru.sberbank.sdakit.demo", "sdk_version" : "20.09.1.3576" } }, "app_info" : { "projectId" : "e5fd0e60-eb9e-4b46-a733-d54e21e463fe", "applicationId" : "4ec49505-6588-47c8-b7fe-2d0d0f0a783a", "appversionId" : "9523ea44-9f34-4c4f-9e1e-d4f912471f62", "systemName" : null, "frontendEndpoint" : "https://mfsigns.justanother.app", "frontendType" : "WEB_APP" }, "strategies" : { "last_call" : null }, "server_action" : { "action_id" : "button_pressed", "payload" : { } }, "client_profile" : "***", "pronounceText" : "Отправляю на фронт", "items" : [ { "bubble" : { "text" : "Отправляю на фронт" } }, { "command" : { "type" : "smart_app_data", "action" : "message_from_backend", "data" : { } } } ], "auto_listening" : true }}

</details>

Видно что здесь команда тоже есть, но в клиент она не приходит.

**Comment by Genenko-Svetlana** [comment]
Попробуйте так:  { type: 'smart_app_data', smart_app_data: { "action" : "message_from_backend", "data" : { } } }

**Comment by DenisNP** [comment]
@Genenko-Svetlana не помогло, всё так же: голосом есть, событием нет.

**Comment by Genenko-Svetlana** [comment]
Рядом с { type: 'smart_app_data' } , должно быть поле smart_app_data , куда нужно складывать данные

**Comment by DenisNP** [comment]
@Genenko-Svetlana описанную проблему этот подход не решает, увы.

**Comment by subnetsRU** [comment]
Уверен ?

Должно быть так:
```
function sendToFront(action, data){
    var command = {
        type: "smart_app_data",
        smart_app_data: {
               action: action,
               data: data
        }
    };
    
    getRawBody().items.push({ command: command });
}
```
На API точно работает.

**Comment by Genenko-Svetlana** [comment]
В sendData убрать второй аргумент, т.к это подписка на ответ и в общую подписку этот ответ не попадает https://github.com/sberdevices/assistant-client#senddata-action-assistantserveraction-requestid-[…]rtapperror--assistantsmartappcommand--void---void

**Comment by DenisNP** [comment]
@subnetsRU так и у меня работает если голосом говорить. Прочитай топик то :) Не работает только при разборе точно такой же команды событием с фронта. Голосом работает.

**Comment by DenisNP** [comment]
@Genenko-Svetlana помогло спасибо! Документация не слишком понятная в этом месте, я думал, что речь идёт о каком-то уведомлении о получении, а оказывается речь о любом ответе который сформирует бэкенд.

Думаю, можно закрывать.

**Comment by Genenko-Svetlana** [comment]
Хорошо ) Постараемся сделать документацию понятнее
