### ISSUE TITLE
Поле top_text.max_lines в media_gallery_item

### ISSUE THREAD

**Issue by Valkinaz** [sberdevices/salute-issues#201]
**Где нашелся баг**: Сберпортал, Сбербокс
**Описание проблемы**: Значение количества строк в json структуре media_gallery_item для поля top_text не работает
**Проблема воспроизводится у других пользователей?** Да
**Дополнительная информация**: 
Отображение в приложении (iPhone): https://i.imgur.com/HK89bgv.jpg
Отображение в Сбербоксе: https://i.imgur.com/arCZ1Gn.jpeg
Отображение в Сберпортале: https://i.imgur.com/J8KKrlE.jpg

**Comment by Valkinaz** [comment]
И, кстати, не знаю, заводить ли отдельным багом или сюда же? На скриншотах видно, что почему-то изображения не отображаются в карточках. Опять же: в мобильном приложении ок, а на девайсах нет

**Comment by Genenko-Svetlana** [comment]
Проверяем

**Comment by Genenko-Svetlana** [comment]
Планируется исправление в версии 1.71.
Ориентировочно 21.05.21

**Comment by Tamagocha** [comment]
@Genenko-Svetlana  какие готовности по задаче? когда сможете вылить?

**Comment by Genenko-Svetlana** [comment]
Уточняю новый срок, т.к. был перенос

**Comment by Valkinaz** [comment]
Какая-нибудь есть информация?

**Comment by Genenko-Svetlana** [comment]
Пока нет. Версия 1.71 для Сберпортала еще не вышла

**Comment by Valkinaz** [comment]
Есть какие-нибудь новости?

**Comment by Genenko-Svetlana** [comment]
Да, сегодня выяснили, что срок снова перенесен на 01.07.21

**Comment by talagaev** [comment]
фиксы уже в 1.71

**Comment by Valkinaz** [comment]
@talagaev портал у меня все еще 1.70, проверить не могу. Обновление 1 июля только придет?

**Comment by Genenko-Svetlana** [comment]
Пока версия 1.71 не вышла в пром (((

**Comment by Genenko-Svetlana** [comment]
09.07.21 выйдет сразу 1.72

**Comment by Valkinaz** [comment]
@Genenko-Svetlana у меня портал все еще 1.70.52. Обновление уже вышло? Если да, то может подскажите как его заставить обновиться?

**Comment by IgorEgorin** [comment]
Баг всё еще воспроизводится.
Текущая версия 1.70.52

**Comment by Genenko-Svetlana** [comment]
Версия 1.72 вышла в пром сегодня ночью

**Comment by Valkinaz** [comment]
Спасибо, все ок теперь

**Comment by Genenko-Svetlana** [comment]
Ура!
