### ISSUE TITLE
Доступ на тестирование для группы

### ISSUE THREAD

**Issue by ygerzen** [sberdevices/salute-issues#202]
Предлагаю в Смарт-студии, в разделе выдачи доступов тестировщикам сделать фичу с созданием/выбором группы тестировщиков. Чтобы можно было раз создать и потом во всех смартапах выбирать группу постоянных тестировщиков. Это сократит время на добавление постоянных тестировщиков, исключит однотипную операцию при создании новых смартапов.
![image](https://user-images.githubusercontent.com/21137721/116512509-d3805900-a8d0-11eb-9868-f348f2c047b8.png)

**Comment by Genenko-Svetlana** [comment]
@ygerzen  Именно в такой формулировке - не планируем.
Но в текущем году будет реализовано много важных изменений, которые облегчат командную работу.
Следите за нашими новостями!
