### ISSUE TITLE
Несоответствие отображения текста в карточках при тестировании в Smart Graph и в Сбер Салют

### ISSUE THREAD

**Issue by EugeneMesh** [sberdevices/salute-issues#205]
**Где нашелся баг**: Smart Graph / Сбер Салют
**Описание проблемы**: Один и тот же текст в карточках при тестировании в Smart Graph и в Сбер Салют отображается по-разному. в Smart Graph есть word wrap, а в Сбер Салют его почему-то нет.
![image](https://user-images.githubusercontent.com/82206087/117790136-1e4b8a80-b25a-11eb-886f-c084dbc2f62f.png)
![image](https://user-images.githubusercontent.com/82206087/117790290-420ed080-b25a-11eb-9813-df150df3be37.png)

**Проблема воспроизводится у других пользователей?**: не знаю.
**Дополнительная информация**: Сбер Салют установлен в iPhone SE, iOS 14.4.2

**Comment by NikolayPakhomov** [comment]
Добрый день! У карточек есть ограничения, описанные тут: https://developer.sberdevices.ru/docs/ru/developer_tools/flow/bots_structure/blocks/card 
Сбер Салют отображает информацию на базе этих ограничений.

**Comment by NikolayPakhomov** [comment]
Добрый день! Отображение карточек в Сбер Салют отличается от того, что вы видите в эмуляторе. В приложении они отображаются согласно правилам: https://developer.sberdevices.ru/docs/ru/developer_tools/flow/bots_structure/blocks/card

**Comment by EugeneMesh** [comment]
@NikolayPakhomov Добрый день!
Спасибо за быстрый ответ! Эту статью я читал.
Если сможете сделать в Сбер Салют перенос текста в карточках, как в эмуляторе - будет круто.

**Comment by NikolayPakhomov** [comment]
@EugeneMesh отображение карточки, созданной через блок "Карточка" в Graph, задумывалось без переноса текста. Вы можете посмотреть в сторону других карточек: https://developer.sberdevices.ru/docs/ru/developer_tools/amp/smartapp_interface_elements#card
Их можно добавлять через блок JS-код. Карточка gallery_card будет выглядеть примерно так:
```
var reply = {
    type: "raw",
    body: {
    "card": {
        "type": "gallery_card",
        "items": [
            {
                "type": "media_gallery_item",
                "image": {
                    "url": "https://thumbs.dfs.ivi.ru/storage31/contents/8/e/010ea0147875e28b91ef1ff01cd042.jpg",
                    "size": {
                        "width": "medium",
                        "aspect_ratio": 1.42
                    }
                },
                "margins": {
                    "top": "4x",
                    "left": "6x",
                    "right": "6x",
                    "bottom": "5x"
                },
                "bottom_text": {
                    "text": "2019 г. ‧ Комедия/Драма",
                    "typeface": "caption",
                    "text_color": "secondary",
                    "max_lines": 1,
                    "margins": {
                        "top": "2x"
                    }
                },
                "top_text": {
                    "text": "Однажды в Голливуде",
                    "typeface": "footnote1",
                    "text_color": "default",
                    "max_lines": 2
                }
            }
        ]
    }
}
};
$response.replies = $response.replies || [];
$response.replies.push(reply);
```

**Comment by NikolayPakhomov** [comment]
@EugeneMesh добрый день! Удалось попробовать другие карточки? Могу закрыть тикет?

**Comment by EugeneMesh** [comment]
@NikolayPakhomov  Добрый день!
Николай, идея супер - попробовал. Но проект в Smart Graph не собрался. Что делаю: создаю пустой Chat App, добавляю один блок JS Code, туда копирую пример Gallery Card из документации, нажимаю зеленую кнопку "Запустить", получаю ошибку сценария. 
В логах вот это:
src/main.sc:6:22 Expected ; but found :                "card": {                      ^DEPLOY FAILED!

что-то не так делаю?

**Comment by NikolayPakhomov** [comment]
@EugeneMesh Доброе утро! Пример в документации написан для API, чтобы это работало в Graph, нужно добавить данные Gallery Card из примера (https://developer.sberdevices.ru/docs/ru/developer_tools/amp/smartapp_interface_elements#gallery-card) в поле body из примера, который выше присылал. Если возникнут сложности, предлагаю написать в нашем чате в телеграмм:  https://t.me/smartmarket_community
