### ISSUE TITLE
В SmartApp Graph интенты снабдить встренными подсказками

### ISSUE THREAD

**Issue by Nashev** [sberdevices/salute-issues#206]
Я заметил, что когда делаю в SmartApp интенты, мне хочется чтоб пользователь видел, что он может сказать, и мог при желании ещё и тыкнуть мышкой. Для этого в каждом блоке с интентами делаю подсказки, соответствующие ключевым интентам. То есть, у меня в каждом экране с пачкой интентов оказывается ещё и пачка подсказок, фактически частично дублирующих эти интенты и переходы с них. Пока у меня это касается интентов, обеспечивающих только переход на другой экран и не обеспечивающих ввод данных в переменные. 

И вот возникла идея: Для таких интентов, мне думается, было бы удобно у одного из примеров иметь возможность иметь включаемый признак "отображать как подсказку", чтоб соответствующую подсказку не приходилось добавлять в экран отдельным блоком с отдельным переходом.

**Comment by NikolayPakhomov** [comment]
Добрый день! Интересная идея, обязательно рассмотрим и подумаем над реализацией. Тикет временно переношу в "Отложенные".
