### ISSUE TITLE
Возможность с главного экрана открыть Graph-проект в Code 

### ISSUE THREAD

**Issue by Nashev** [sberdevices/salute-issues#208]
Возможность открыть Graph-проект в Code надо б вывести и на главный экран https://developers.sber.ru/studio/workspaces/smartapps (в выпадашку по троеточию у проекта), а не только предлагать на не имеющей прямого входа с лендингов страничке https://smartapp-code.sberdevices.ru/service/code/

**Comment by xoxulin** [comment]
Как временную меру добавим уже в июне, а позже (июль) скорее всего все проекты Smartapp / Code / Graph станут раздельными проектами (разными карточками в списке проектов). Следите за обновлениями!

**Comment by Genenko-Svetlana** [comment]
Срок реализации 3 квартал 2021

**Comment by Genenko-Svetlana** [comment]
@Nashev реализовано, проверяйте, пожалуйста.
