### ISSUE TITLE
В Graph блоке Текст не надо считать троеточие частью идентификатора переменной

### ISSUE THREAD

**Issue by Nashev** [sberdevices/salute-issues#209]
Я добавил тектовый блок с текстом "Ок, будем делать $todo…", и нарываюсь на ошибку 
```
Описание: /jsapi/reactions.js:21:16 SyntaxError: <function>:3:21 Expected ) but found error
((__t=($session.todo…))==null?'':__t)+
```
Заметьте, тут даже не три точки, а именно символ троеточия! Его-то зачем частью идентификатора считать?

Я по началу три обычных точки вписал, и нарвался на `((__t=($session.todo..))==null?'':__t)+`, с трудом нашёл про какой это блок. Думал, символ троеточия меня спасёт, но упс. Но в принципе, и три отдельных точки в таких ситуациях надо бы тоже уметь исключать из имени.

**Comment by Genenko-Svetlana** [comment]
Предварительно запланировали на 3 квартал 2021

**Comment by Genenko-Svetlana** [comment]
@Nashev спасибо за предложение. Взяли задачу в бэклог, но в ближайшее время не планируем к реализации.
