### ISSUE TITLE
[Graph] Блоки Ввод текста и Ввод числа - нет разметки для речи

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#21]
В этих блоках нельзя задать как произносить (голосом) указанный текст. Итого текст "укажите свой ID" читается как "укажите свой ид" и ничего с этим поделать нельзя.

**Comment by asmalakhov-sberdevices** [comment]
@and7ey Возьмем в проработку этот вопрос. 
Как решение сейчас, можно использовать Блок ввод текста + интенты
Добавить Текст с разметкой и блок интент. В интенте создать "собственный интент" и заполнить его как $NUMBER::number
Тут number это название переменной, в которую сохранится ввода пользователя. После :: можно указать любое название. переменной. В сценарии переменная будет доступна через $number как и все остальные.

**Comment by and7ey** [comment]
Антон, не очень понял предлагаемое решение.

> Как решение сейчас, можно использовать Блок ввод текста + интенты 

Тут имелось в виду Блок текст + интенты? (не блок ВВОД текста)

`$NUMBER::number` это ведь ввод числа? А у меня ввод текста.

**Comment by asmalakhov-sberdevices** [comment]
@and7ey да, опечатался выше. Имел ввиду Тут имелось в виду Блок текст + блок интент.
Для ввода текста можно добавить в интент `$TEXT::text` - он будет сохранять любой текст

Но задачу занесем себе в бэклог, спасибо!

**Comment by Genenko-Svetlana** [comment]
Срок реализации 31.03.2021

**Comment by Genenko-Svetlana** [comment]
Возвращаем в работу.

**Comment by Genenko-Svetlana** [comment]
@and7ey проверьте, пожалуйста
@Sergeycul
