### ISSUE TITLE
Уведомлени на email об изменении статуса приложения

### ISSUE THREAD

**Issue by dbf256** [sberdevices/salute-issues#213]
**Где пригодится фича**: SmartMarket studio
**Описание фичи**: сейчас отсутсвуют какие-либо уведомления о статусе приложений. Чтобы проверить статус модерации приходится постоянно заходить на сайт. Если апп останавливается из-за проблем, об этом вообще не узнаешь, пока случайно не решишь зайти проверить свои приложения.
**Дополнительная информация**: какие-то детали, которые могут помочь в реализации фичи.

**Comment by Genenko-Svetlana** [comment]
У нас есть подобная задача #41

**Comment by dbf256** [comment]
Согласен, дубликат.

**Comment by Genenko-Svetlana** [comment]
Тогда закрываем )
По #41 срок реализации 2 квартал 2021
