### ISSUE TITLE
Передавать на бэкенд навигационные фразы (Назад, Продолжить итд)

### ISSUE THREAD

**Issue by DenisNP** [sberdevices/salute-issues#214]
### Описание фичи: 
Сейчас на Сбербокс (и, полагаю, на других устройствах кроме телефона) голосовые команды "Вперёд", "Вниз", "Вверх" вызывают навигационное событие в `assistantClient`, и при этом не приходят на бэкенд смартапа. Голосовая команда "Назад" не вызывает событие (!) и не приходит на бэкенд (вероятно, они триггерит `History API`, но у меня не было возможности проверить).

Предлагаю сделать настройку, либо навсегда включить **передачу этих команд на бэкенд** как обычных голосовых команд. Можно совместно с событиями. Можно в объекте запроса это слово помечать как навигационную команду. Но передавать.

### Где пригодится фича:

Сходу два сценария:

**1. Тонкий клиент и управление навигацией через бэкенд**
Я использую паттерн "состояние" и реактивный фреймворк на фронтенде, чтобы бэкенд мог управлять в том числе состояние отрисовки. Поэтому бэкенд должен получать навигационные команды в том числе. Сейчас приходится с клиента их отправлять даже когда произнесено голосом.

**2. Игра в слова**
В некоторых играх важно понимать какое именно слово произнёс пользователь. Сейчас на Сбербоксе понять разницу между "Вперёд" и "Продолжить" невозможно.

**Comment by DenisNP** [comment]
А, увидел что похожее есть #16
Если совсем дубликат, то закрывайте.

**Comment by NikolayPakhomov** [comment]
Добрый день! Да, дубликат, эту задачу закрою
