### ISSUE TITLE
Идея: передача данных гироскопа смартаппам. 

### ISSUE THREAD

**Issue by i200cm3** [sberdevices/salute-issues#215]
Где пригодится фича: от мышки на экране SberBox и ТВ до спортивных танцевальных игр типа just Dance Now

Описание фичи:

телефон коннектится к поверхностям по bluetooth, приложение Салют передает данные гироскопа, и разработчики получают данные с ассистента сообщениями

**Comment by Genenko-Svetlana** [comment]
Крутая идея. Спасибо.
Постараемся реализовать в 1-2 квартале 2022 года.
Временно закрываем тикет и переносим задачу в отложенные.
