### ISSUE TITLE
Возможность самостоятельно выбирать поверхности

### ISSUE THREAD

**Issue by DenisNP** [sberdevices/salute-issues#216]
### Описание фичи: 
Возможность при настройке смартапа самостоятельно ставить галочки, на каких поверхностях должен работать смартап. А не просить модерацию, как это сейчас происходит.
> Снятие галочки с поверхности должно отключать необходимость залить превью для этой поверхности!

### Где пригодится фича: 
**1. Постепенный выпуск приложения**
Допустим, я сначала сверстал приложение для телефонов, хочу его выпустить, показать людям, протестировать. А потом доделываю версию для больших экранов.

**2. Невозможность отладки на всех поверхностях**
У многих разработчиков уже есть Сбербокс, хотя не у всех. Мало у кого есть СберПортал. На этих поверхностях могут возникать особенности, которые разработчик сам не сможет посмотреть и отладить.

**3. Специфика приложения**
Некоторые приложения по своей специфике нужны только для смартфонов (например, приложение для использования на улице или в магазине), либо наоборот не подходят для смартфонов (игра которой нужен большой экран).

**Comment by NikolayPakhomov** [comment]
Добрый день! Планируем сделать такую возможность в 4 квартале этого года. Временно переношу тикет в "Отложенные".

**Comment by Genenko-Svetlana** [comment]
@DenisNP реализовано
