### ISSUE TITLE
Возможность использовать интенты и ресурсы в приложениях на Smartapp API

### ISSUE THREAD

**Issue by DenisNP** [sberdevices/salute-issues#217]
### Описание фичи
В проекты, сделанные с использованием `Smartapp API`, необходимо добавить вкладки с _интентами_, _сущностями_, а также _изображениями_ и _звуками_.

### Где пригодится фича
Разработчики приложений на `Smartapp API` очевидно уже используют у себя кастомные картинки и звуки, просто создают для этого фейковое соседнее приложение. Что касается интентов — раз эта функция в системе уже есть, почему не дать её всем?

**Comment by NikolayPakhomov** [comment]
Добрый день! Мы работаем над расширением функционала SmartApp API. Некоторые доработки из вашего списка выпустим ориентировочно до конца месяца.

**Comment by subnetsRU** [comment]
>до конца месяца

А какого месяца? :)

**Comment by vitalets** [comment]
@NikolayPakhomov
Николай, привет!
А не подскажешь, когда планируете выкатить интенты для Smartapp API?

**Comment by NikolayPakhomov** [comment]
Добрый день! К сожалению, сейчас не можем сказать срок выкатки интентов, но мы будем иметь в виду ваш интерес к ним, пока переносим тикет в "Отложенные"
