### ISSUE TITLE
[Assistant Client] Нужна реализация в виде script

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#22]
Для снижения уровня вхождения в разработку Canvas App, нужно сделать решения для подключения ассистента просто через <script>.

**Comment by awinogradov** [comment]
https://github.com/sberdevices/assistant-client/issues/24

**Comment by sasha-tlt** [comment]
@and7ey, в версии 2.1.0 добавили [возможность подключения ассистента через <script>](https://github.com/sberdevices/assistant-client#%D0%B0%D0%BB%D1%8C%D1%82%D0%B5%D1%80%D0%BD%D0%B0%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D0%B5-%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5)

**Comment by ffDowen** [comment]
В версии 2.1.0 добавили возможность подключения ассистента через <script>. Данный тикет закрываем, в случае возникновения вопросов просим создать новый.
