### ISSUE TITLE
Добавить в описание платформ признак о возможности управлять только голосом

### ISSUE THREAD

**Issue by DenisNP** [sberdevices/salute-issues#221]
### Описание фичи
Сейчас в описании платформы, которая приходит с запросом, есть поля `screen`, `mic`, `speak`, показывающие, есть ли у платформы экран, может ли оно говорить и слушать.

Предлагаю добавить признак `handsfree`, который показывает, что устройство можно активировать без рук, а только командой __Салют__. Сейчас это возможно на СберПортал и, как я понимаю, СберБокс Топ.

### Где пригодится фича
1. На устройствах, где активация только голосом невозможна, есть смысл ставить `autoListening = true`, чтобы не заставлять человека тыкать в экран. Но если возможна активация голосом, то удобнее дать человеку поразмыслить над ответом и не напрягать его ожидающей анимацией ассистента.
2. Бывают сценарии, когда работа без рук необходима для приложения, и оно должно полностью поменять своё поведение при отсутствии такой возможности. Например, приложение для занятий йогой.

**Comment by waxerdima** [comment]
А почему это по surface не определять?

**Comment by DenisNP** [comment]
Сейчас определяю по surface, но поверхностей становится всё больше, а функции на них меняются. Ненадёжно.

**Comment by Genenko-Svetlana** [comment]
@waxerdima

**Comment by Ibragimow** [comment]
По результатам внутреннего обсуждения решили пока фичу не реализовывать, в бэклог не включать.
Спасибо за идею!
