### ISSUE TITLE
некорректно распознает фразу «включи greekway

### ISSUE THREAD

**Issue by nikulin-oleg** [sberdevices/salute-issues#225]
**Где нашелся баг**: в ассистенте
**Описание проблемы**: ассистент некорректно распознает фразу «включи greekway», меняет на «включи greenway», соответственно запускается не то что мне нужно.
**Проблема воспроизводится у других пользователей?** да
**Дополнительная информация**: смартап Greek Way

**Comment by RulevAnton** [comment]
@nikulin-oleg добрый день!
исправлено на проме.

исправление нужно для приложения сбербанк онлайн? или только для сбербокс, портала ..?

**Comment by Genenko-Svetlana** [comment]
@nikulin-oleg проверьте, пожалуйста. Исправлено.

**Comment by nikulin-oleg** [comment]
> @nikulin-oleg добрый день!
> исправлено на проме.
> 
> исправление нужно для приложения сбербанк онлайн? или только для сбербокс, портала ..?
Да, везде нужно

**Comment by nikulin-oleg** [comment]
> @nikulin-oleg проверьте, пожалуйста. Исправлено.

спасибо! работает
