### ISSUE TITLE
Нужен пример пустого приложение CanvasApp, где есть как plasma ui, так и assistant

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#226]
https://t.me/smartmarket_community/24421

**Comment by awinogradov** [comment]
https://github.com/sberdevices/salutejs/tree/master/examples/todo

**Comment by and7ey** [comment]
Спасибо. Как исключить salutejs и вообще, все, что связано с функциональностью todo в этом?

**Comment by awinogradov** [comment]
Не смотреть сюда https://github.com/sberdevices/salutejs/tree/master/examples/todo/src/scenario
И удалить это https://github.com/sberdevices/salutejs/blob/master/examples/todo/src/store/index.ts#L9-L44

Стаб для CanvasApp скоро появится в виде отдельного репозитория
