### ISSUE TITLE
Webhook в Code на самую последнюю версию

### ISSUE THREAD

**Issue by alexdremov** [sberdevices/salute-issues#227]
**Где пригодится фича**
Во время тестирования приложения с внешним смартапом в Smart App Code постоянно приходится копировать – вставлять Webhook при обновлении версии 
**Описание фичи**
Сделать в Smart App Code Webhook-alias на самую последнюю опубликованную версию смартапа
**Дополнительная информация**
Этакий proxy который перенаправляет запросы на последнюю версию смартапа

**Comment by waxerdima** [comment]
Добрый день, сейчас в студии такое поведение уже есть, вы можете выбрать не SmartApp API а Code и указать нужный навык и сборку, которую использовать.
<img width="511" alt="Снимок экрана 2021-08-05 в 13 11 34" src="https://user-images.githubusercontent.com/1477455/128333243-ceb9383c-ae1d-4686-824f-b1f7dee68a58.png">

**Comment by alexdremov** [comment]
Да, issue был открыт до этого обновления
Спасибо
