### ISSUE TITLE
Исправление орфографии

### ISSUE THREAD

**Issue by alexdremov** [sberdevices/salute-issues#229]
**Где нашелся баг**
App Studio Code – корректор орфографии только все ломает. Примеры прилагаю

**Описание проблемы**
Вместо исправления ошибочных слов он исправляет верные слова на бред.
В текущей реализации эта фича совершенно не пригодна к использованию

**Проблема воспроизводится у других пользователей?**: **да**
**Дополнительная информация**

<a href="https://imgbb.com/"><img src="https://i.ibb.co/pfjFGny/Screenshot-2021-07-05-at-15-53-55.png" alt="Screenshot-2021-07-05-at-15-53-55" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/5hmpdJc/Screenshot-2021-07-05-at-15-53-16.png" alt="Screenshot-2021-07-05-at-15-53-16" border="0"></a>

**Comment by waxerdima** [comment]
Исправление орфографии работает согласно документации https://developer.sberdevices.ru/docs/ru/developer_tools/ide/platform_ux/nlu_core_caila/spellcheck если вам не нравится предложенные варианты вы можете выбрать "Не исправлять".
