### ISSUE TITLE
Имя смартапа в Code остается старым

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#23]
Имя смартапа в Code остается старым, если проект переименовать в Studio

**Comment by asmalakhov-sberdevices** [comment]
Добавили задачу в бэклог.

**Comment by Genenko-Svetlana** [comment]
Срок реализации 26.02.2021

**Comment by Genenko-Svetlana** [comment]
Изменился срок реализации - до 31.05.21. Тикет временно закрываем и переносим в отложенные задачи.

**Comment by Genenko-Svetlana** [comment]
Возвращаем в работу

**Comment by Genenko-Svetlana** [comment]
@and7ey проверьте, пожалуйста.
