### ISSUE TITLE
Bubble{ text } в тестовом виджете Smart App Code

### ISSUE THREAD

**Issue by alexdremov** [sberdevices/salute-issues#230]
**Где нашелся баг**

В Smart App Code

**Описание проблемы**

Не отображается raw ответ вида 
```
...
items:[{
            bubble: {
                text: textOut
            }
        }]
...
```
**Проблема воспроизводится у других пользователей?**

App Studio один у всех, должно воспроизводиться

**Дополнительная информация**

Долго дебажил через виджет так как отправлял текстовые запросы в формате raw по документации, но они не отображались. **Протестировал на SberBox – все отображаются.**

**Comment by Genenko-Svetlana** [comment]
А он и не должен отображаться. Да и простой текст можно без всяких raw показать.
(https://developer.sberdevices.ru/docs/ru/developer_tools/ide/JS_API/variables/response)

**Comment by Genenko-Svetlana** [comment]
![Uploading Снимок экрана 2021-07-07 в 16.53.24.png…]()

**Comment by alexdremov** [comment]
> А он и не должен отображаться. Да и простой текст можно без всяких raw показать.
> (https://developer.sberdevices.ru/docs/ru/developer_tools/ide/JS_API/variables/response)

Окей, но такое раздвоение тестового режима и production – bad practice

**Comment by Genenko-Svetlana** [comment]
Спасибо, за предложение.
У нас тестирование не заканчивается на виджете. Необходимо еще на устройствах проверить, а там эти данные будут.
