### ISSUE TITLE
Функция inflect склоняет только одно слово

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#232]
**Где нашелся баг**: Code
**Описание проблемы**: inflect("Железная штука", "accs") возвращает "железная штуку", а нужно возвращать "Железную штуку". И не трогать регистр.
**Проблема воспроизводится у других пользователей?** Думаю, да.

**Comment by waxerdima** [comment]
https://developer.sberdevices.ru/docs/ru/developer_tools/ide/JS_API/built_in_services/nlp/inflect как написано в документации:

> Склоняет **слово** в требуемый формат.

**Comment by and7ey** [comment]
Нужно использовать 
```
inflect("Железная", "accs")
inflect("штука", "accs")
```
? Давайте тогда в feature request переведем этот issue.
Ну и с регистром точно баг. В документации не вижу, что регистр меняется.

**Comment by waxerdima** [comment]
Не переведем.
```js
capitalize("Железная штука".split(' ').map(function(item) { return inflect(item, 'accs'); }).join(' '));
```
