### ISSUE TITLE
[SmartApp API] В урле вебхука отрезаются get-параметры

### ISSUE THREAD

**Issue by vitalets** [sberdevices/salute-issues#235]
**Где нашелся баг**: 
в инструментах

**Описание проблемы**: 
При отправке запросов в урле вебхука отрезаются get-параметры.
Например, я в настройках смартапа задал вебхук `https://webhook.site/fae6580f-da8d-4aeb-83fe-ac0ce43f0d35?foo=42`
А запросы приходят на `https://webhook.site/fae6580f-da8d-4aeb-83fe-ac0ce43f0d35` (без `foo`)
Из-за этого есть некоторые неудобства на бекенде. 

**Проблема воспроизводится у других пользователей?** 
не знаю.

Возможно ли сделать, чтобы запросы приходили ровно на тот вебхук, который указан в настройках смартапа?

**Comment by waxerdima** [comment]
Добрый день, только что проверил вот такой вебхук https://85a3c463adf60778d640d01ba55e7125.m.pipedream.net?foo=42 и получил значение 
<img width="147" alt="Снимок экрана 2021-07-13 в 18 14 48" src="https://user-images.githubusercontent.com/1477455/125477823-c76f0462-e4ef-43bc-86dc-4e8f45c083ed.png">

**Comment by vitalets** [comment]
> Добрый день, только что проверил вот такой вебхук https://85a3c463adf60778d640d01ba55e7125.m.pipedream.net?foo=42 и получил значение
> <img alt="Снимок экрана 2021-07-13 в 18 14 48" width="147" src="https://user-images.githubusercontent.com/1477455/125477823-c76f0462-e4ef-43bc-86dc-4e8f45c083ed.png">

Привет! А можешь плз проверить через https://webhook.site ?

**Comment by Genenko-Svetlana** [comment]
@waxerdima

**Comment by waxerdima** [comment]
Зачем мне проверять на https://webhook.site?

**Comment by vitalets** [comment]
> Зачем мне проверять на https://webhook.site?

Потому что это шаги воспроизведения бага.

Можно и локально проверить:
1. Запустить локальный сервер на порту 8080: `npx http-server`
2. Создать туннель: `ngrok http 8080`
3. Проверить локальным запросом с гет-параметрами: `curl -X POST 'https://a2ba5616558f.ngrok.io/some-path/?foo=42'`. В логах сервера гет-параметр есть:
   ```
   [2021-08-07T07:58:19.074Z]  "POST /some-path/?foo=42" "curl/7.64.1"
   [2021-08-07T07:58:19.079Z]  "POST /some-path/?foo=42" Error (404): "Not found"
   ```
4. Взять тот же урл и вставить в поле вебхук в студии:
   ![image](https://user-images.githubusercontent.com/1473072/128593133-be0a1033-681e-4d5d-a4af-fbda1a8786f2.png)
5. Перейти на вкладку тестирование, чтобы пришел запрос от сбера. В логах сервера видим пост запрос без гет параметров:
   ![image](https://user-images.githubusercontent.com/1473072/128593341-016f20c0-9a14-4a33-8eaa-a4895fa04de2.png)
6. А если не указывать `some-path`, то к запросу дописывается путь `/app-connector/`:
  ![image](https://user-images.githubusercontent.com/1473072/128883389-409bd3f8-724c-4ebe-9238-7fb2791793db.png)
7. Для проверки вставил тот же вебхук в Алису и Марусю, везде запросы приходят с параметрами:
  ![image](https://user-images.githubusercontent.com/1473072/129522816-209a6969-6f2a-477e-a6a8-ce209d334be1.png)

**Comment by vitalets** [comment]
@waxerdima @skobets Ребята, посмотрите в чем тут дело?

**Comment by waxerdima** [comment]
Я проверил локально, у меня все передается
<img width="548" alt="Снимок экрана 2021-08-16 в 14 44 15" src="https://user-images.githubusercontent.com/1477455/129558513-a50720ea-ae67-4332-ad60-028c8b4c95b3.png">
<img width="180" alt="Снимок экрана 2021-08-16 в 14 44 29" src="https://user-images.githubusercontent.com/1477455/129558547-3a6e7c6b-db86-4028-8c77-86b0814caa9d.png">

**Comment by vitalets** [comment]
> Я проверил локально, у меня все передается

Так, ну и какие варианты решения?) Надо прикинуть, какой фактор мы не учитываем.
Как минимум предлагаю попросить ребят из чата проверить.

**Comment by vitalets** [comment]
Обсудили с Сергеем, проблема действительно есть, в ближайшее время должны пофиксить.
Почему у Димы не воспроизводится - загадка :)

**Comment by vitalets** [comment]
Все заработало, спасибо!
![image](https://user-images.githubusercontent.com/1473072/132481599-9b0e25b4-fc09-44af-89f8-4a63badf1d20.png)

Таск можно закрывать.
