### ISSUE TITLE
В истории SmartMarket Studio время отображается в каком-то неизвестном часовом поясе

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#238]
**Где нашелся баг**: SmartMarket Studio
**Описание проблемы**: время в неизвестном часовом поясе в Истории, очень неудобно пользоваться
тут - https://developers.sber.ru/studio/workspaces/<>/smartapp/projects/<>/draft/history
**Проблема воспроизводится у других пользователей?** не знаю.

**Comment by Genenko-Svetlana** [comment]
Взяли задачу в работу. Срок реализации - 01.08.2021

**Comment by Genenko-Svetlana** [comment]
@and7ey исправили, проверьте, пожалуйста

**Comment by and7ey** [comment]
что-то у меня в истории теперь совсем пусто

**Comment by Genenko-Svetlana** [comment]
Навык не публиковали в ближайшее время?

**Comment by and7ey** [comment]
Публиковал 4 дня назад.
