### ISSUE TITLE
Миграция проекта из Graph в Code

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#24]
https://t.me/smartapp_studio/3482 обсуждение здесь и ниже

**Comment by asmalakhov-sberdevices** [comment]
Возможность открыть проект Graph в Code сейчас доступна, для этого нужно зайти в Code по прямой ссылке https://smartapp-code.sberdevices.ru/ и найти нужный проект в списке проектов. 

Для тестирования Canvas app необходимо использовать  [SberDevices Assistant](https://smartapp-code.sberdevices.ru/documentation/#/docs/ru/developer_tools/sdk/overview) 

Уведомления о тестировании добавим в задаче https://github.com/sberdevices/salute-issues/issues/6

**Comment by and7ey** [comment]
Этот тикет не о том, как открыть проект Graph в Code. А об удобной миграции.
В переписке в ТГ я писал - сейчас надо руками создать новый проект в Code, потом туда импортировать то, что было создано в Graph. Нужно задавать новое название. А еще стартовый node задавать руками. Вместо того, чтобы нажать одну кнопку "Мигрировать".

**Comment by asmalakhov-sberdevices** [comment]
@and7ey 
Речь идет о том, чтобы не редактировать текущий проект Graph, а открыть его в Code как отдельный проект?
Можете подробнее описать кейс, почему именно такой вариант нужен больше.

**Comment by Genenko-Svetlana** [comment]
@skobets @asmalakhov-sberdevices  Посмотрите комментарий выше, пожалуйста.

**Comment by Genenko-Svetlana** [comment]
@skobets @asmalakhov-sberdevices Посмотрите комментарий выше, пожалуйста.

**Comment by Genenko-Svetlana** [comment]
@and7ey
Речь идет о том, чтобы не редактировать текущий проект Graph, а открыть его в Code как отдельный проект?
Можете подробнее описать кейс, почему именно такой вариант нужен больше.

**Comment by Genenko-Svetlana** [comment]
@and7ey

**Comment by Genenko-Svetlana** [comment]
@and7ey  в связи с отсутствием комментариев тикет закрываем.
