### ISSUE TITLE
Не отображать слова, которые пользователь произносит ассистенту

### ISSUE THREAD

**Issue by IgorEgorin** [sberdevices/salute-issues#241]
**Где пригодится фича**: В ассистенте
**Описание фичи**: 
Не отображать слова, которые пользователь произносит ассистенту.
Выводить на экран только готовую фразу.
**Дополнительная информация**: 
Зачем печатать,то что говорит пользователь ассистенту?
Ведь он все равно не может на это повлиять (изменить слова).
Может не отображать, то что пишется под диктовку, а сразу выводить готовый результат на экран?

**Comment by Genenko-Svetlana** [comment]
Спасибо за комментарий.
Это сделано специально, для того, чтобы пользователи видели, как распознается их речь.

**Comment by subnetsRU** [comment]
+1 убирать нельзя.

**Comment by Valkinaz** [comment]
Я думаю стоило связать это с тикетом о том, что очень быстро пропадают кнопки-подсказки. Ассистент ведь начинает слушать, а пропадают саджесты для того, чтобы выводить распознаваемый текст. Поэтому встает вопрос о том, что полезнее: видеть саджесты или видеть распознаваемый текст. На последний пользователь по факту никак не может повлиять, если ассистент неправильно что-то распознал, то это не исправить, сообщение отправится в том же виде. Пользователь не может как при обычном наборе текста нажать бекспейс или переместить каретку, чтобы исправить что-то перед отправкой текста. Поэтому и возникает закономерный вопрос: а зачем вообще выводить этот текст, тем более если это мешает работе другого функционала (саджестам).

**Comment by IgorEgorin** [comment]
Ссылка на тикет про "очень быстро пропадают кнопки-подсказки" https://github.com/sberdevices/salute-issues/issues/240
