### ISSUE TITLE
Листать карусель фразами "Пролистни вправо" или "Пролистни влево"

### ISSUE THREAD

**Issue by IgorEgorin** [sberdevices/salute-issues#242]
**Где пригодится фича**: в ассистенте
**Описание фичи**: 
Предлагаю такую фичу: После отображения карусели, пролистывать её фразами "Пролистни вправо" или "Пролистни влево"
**Дополнительная информация**:
За пример возьму поиск вакансии на Работа.Ру
После выдачи вакансии было бы удобно листать карточки вакансии голосом, произнеся фразу "Пролистни вправо" или "Пролистни влево" (Вместо того чтобы делать это пальцем).
Можно ли так сделать в будущем?
![image](https://user-images.githubusercontent.com/24498645/127323090-f910de37-ffde-452f-bae9-0021e81f1d2e.png)

**Comment by waxerdima** [comment]
Добрый день, а почему вы сами это не реализуете в вашем канвас приложении?

**Comment by IgorEgorin** [comment]
@Valkinaz

**Comment by Valkinaz** [comment]
@waxerdima это не канвас, это чатапп, сделанный в Code

**Comment by waxerdima** [comment]
Тогда расскажите, что за карусель вы используете в чатаппе?

**Comment by Valkinaz** [comment]
```
"items": [
    {
        "card": {
            "type": "gallery_card",
            "items": []
        }
    }
]
```

**Comment by Genenko-Svetlana** [comment]
В чатапх голосовая навигация по элементам чата (карточки и баблы) действительно не поддержана. И в ближайших планах этой задачи нет. А тесты показывают, что пользователям в похожих кейсах проще управлять пультом или тачем.
