### ISSUE TITLE
Статистика по всем своим смартапам в одном месте

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#243]
**Где пригодится фича**: Code и Graph
**Описание фичи**: сейчас, чтобы посмотреть статистику использования смартапов, нужно заходить в каждый проект отдельно. Это долго и неудобно. Было бы здорово, если бы 
1) статистику по всем апам можно было бы смотреть в одном месте,
2) она бы приходила, например, раз в неделю, на email.

В идеале добавить бы еще открытые данные для сравнения с конкурентами - например, место приложения в каталоге (см. бот https://t.me/yadialogsbot для Алисы).  
**Дополнительная информация**: Если ресурсов на это нет, то можно продумать вариант с созданием АПИ для доступа к статистике. Например, сделать какой-то авторизационный токен для доступа к https://developers.sber.ru/api/graph/restapi/logs/id-moego-smartappa/uniqueClients?dateFrom=1626987600000&dateTo=1627678799999

**Comment by NikolayPakhomov** [comment]
Добрый день! Спасибо за интересные предложения, обязательно учтем. Мы планируем доработки в части статистики. Целимся на следующий год, поэтому пока тикет переношу в отложенные.
