### ISSUE TITLE
Добавить возможность зацикливать аудио в Graph

### ISSUE THREAD

**Issue by sergeyzhirkov** [sberdevices/salute-issues#246]
Фича пригодится при разработке смартапа на графе.
Иногда нужно включить музыку в фоновом режиме, и чтобы она не отключалась (зациклить какой-то фоновый звук).
Сейчас приходится делать несколько экранов и в каждый добавлять одинаковую звуковую дорожку, что конечно не удобно и общая звуковая дорожка конечна. При этом в ресурсах проекта сохраняется только один звуковой файл, то есть граф понимает что это один и тот же звук, но инструментами разработки зациклить для повторения его не даёт.

**Comment by Genenko-Svetlana** [comment]
Данный функционал не планируется к реализации. Рекомендуем выбрать канвас приложение, а не чатап.
