### ISSUE TITLE
Добавить таймер для блока "переход" в Graph

### ISSUE THREAD

**Issue by sergeyzhirkov** [sberdevices/salute-issues#247]
Фича пригодится при использовании блока переход в графе.
Есть несколько последовательных экранов с блоками перехода от одного к следующему. Нужно чтобы они открывались с небольшой задержкой, а не все сразу летели на экран.
Нужно чтобы была возможность показывать пользователю информацию (текст например) дозировано, устанавливая временной интервал (например, 3 секунды). Без интентов (голосового ввода) со стороны пользователя.

**Comment by Genenko-Svetlana** [comment]
Данный функционал не планируется к реализации. Асинхронной работы протокола нет. Соответственно без запроса к нам мы не можем отправить ответ.
Рекомендуем выбрать канвас приложение, а не чатап.
