### ISSUE TITLE
Показывать в разделе аналитики какой тип ассистента (персонажа) был выбран при использовании смартапа

### ISSUE THREAD

**Issue by sergeyzhirkov** [sberdevices/salute-issues#248]
Фича пригодится в разделе аналитики SmartMarket Studio
Эта информация может помочь при продумывании диалогов для сценария смартапа (возможно игры). Чтобы представлять, какой тип ассистента чаще всего выбран при использовании твоего смартапа. Конечно в смартапе предусматривается отдельная ветка диалога для каждого типа персонажа (Сбер, Афина, Джой), но у них разная скорость речи и хотелось бы понимать - в целом придумывать сценарий для чатапа более активный или пассивный.

**Comment by Genenko-Svetlana** [comment]
Спасибо за предложение!
Возьмем задачу в бэклог, но с низким приоритетом. 
Если будут еще запросы от пользователей по этой задаче, то приоритет повысим.
Пока тикет временно закрываем и переносим задачу в отложенные.
