### ISSUE TITLE
Сервис конвертации google-таблиц не работает с id 

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#249]
**Где нашелся баг**: https://smartapp-code.sberdevices.ru/tools/api/csv2json
**Описание проблемы**: https://smartapp-code.sberdevices.ru/tools/api/csv2json?id=xxxx возвращает ошибку - 
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sat Aug 14 19:24:01 UTC 2021
There was an unexpected error (type=Bad Request, status=400).
Required String parameter 'url' is not present
```
Требуется параметр url, хотя судя по документации нужен url **или** id.
**Проблема воспроизводится у других пользователей?** не знаю
**Дополнительная информация**: Whitelabel Error Page тоже бы неплохо поправить :)

**Comment by waxerdima** [comment]
Спасибо за сигнал, но мы в курсе и уже работает над исправлением, на следующей недели планируем выпустить исправление.

**Comment by and7ey** [comment]
Несколько пугает, что такое важный сервис может несколько дней не работать :(

**Comment by waxerdima** [comment]
Я понимаю ваше негодование, но это сторонний сервис и мы не можем гарантировать, что он не поменяет API. Вы можете напрямую использовать последнее API google таблиц в своих приложениях прямо сейчас или дождаться исправления нашего сервиса tools. Извиняемся за неудобства.

**Comment by and7ey** [comment]
Глядя на URL сервиса кажется, что он все-таки ваш, а не сторонний :).
Использовать API Google-таблиц в Graph, думаю, не выйдет. А если выйдет, то зачем вы в документации пишете про сервис csv2json, если есть простой способ обойтись без него? :)

**Comment by waxerdima** [comment]
Сервис tools наш, но использует он сторонне (API google таблиц). Вы свободно можете использовать в том числе и в графе API google. Если интересует, как то приходите в чат поддержки в телеграмм, я там вам отвечу. Сервис tools создан для упрощения работы с внешними данными, но из-за изменения внешнего API временно не работает и мы прилагаем все усилия для его восстановления, но надо немного подождать.

**Comment by Genenko-Svetlana** [comment]
@and7ey Исправили. Проверьте, пожалуйста.

**Comment by and7ey** [comment]
По-прежнему требует url, хотя передано id.

**Comment by waxerdima** [comment]
А зачем вам сейчас этот сервис?

**Comment by and7ey** [comment]
Светлана попросила проверить - я проверил :).
Мне этот сервис не нужен, мне нужен googlesheet2json.

**Comment by Genenko-Svetlana** [comment]
Сейчас с гугл таблиц нельзя получить csv. Соответственно, этим методом никто воспользоваться не сможет. 
Мы внесем изменения в документацию:
вместо -  https://developer.sberdevices.ru/docs/ru/developer_tools/flow/publication_channels/google_tables/csv_to_json
будет - https://developer.sberdevices.ru/docs/ru/developer_tools/flow/bots_structure/blocks/using_variable_in_url
