### ISSUE TITLE
[Assistant Client] Не показывает текстовые ответы

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#25]
Нужно отображать текстовые ответы от бэка на фронте и предусмотреть возможность отключать голос. Тестировать фронт с голосом - долго.

**Comment by sasha-tlt** [comment]
Добавили такую возможность в @sberdevices/assistant-client@1.1.0. Достаточно в  `createSmartappDebugger` добавить параметр [settings](https://github.com/sberdevices/assistant-client/blob/main/README.md#AssistantSettings). Например, `createSmartappDebugger({ ..., settings: { dubbing: false } };`
