### ISSUE TITLE
Сервис чтения Google-таблиц возвращает 404

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#250]
**Где нашелся баг**: https://smartapp-code.sberdevices.ru/tools/api/googlesheet2json
**Описание проблемы**: https://smartapp-code.sberdevices.ru/tools/api/googlesheet2json?sheet=2&id=xxx возвращает 404
**Проблема воспроизводится у других пользователей?** не знаю.
**Дополнительная информация**: https://tools.aimylogic.com/api/googlesheet2json?id=xxx, кстати, отрабатывает корректно (таким образом, проблем с публикацией самой таблицы нет)

**Comment by waxerdima** [comment]
Спасибо за сигнал, но мы в курсе и уже работает над исправлением, на следующей недели планируем выпустить исправление.

**Comment by Genenko-Svetlana** [comment]
@and7ey Исправили. Проверьте, пожалуйста.

**Comment by and7ey** [comment]
Работает! Спасибо!
