### ISSUE TITLE
Не закреплять жестко обращение на "ты/вы" за персонажами

### ISSUE THREAD

**Issue by vitalets** [sberdevices/salute-issues#252]
**Где пригодится фича**: 
в ассистенте, в приложении.

**Описание фичи**: 
Сейчас по правилам платформы Сбер и Афина обязаны всегда обращаться к пользователю на "вы", а Джой - всегда на "ты". Понятно, какая мотивация была у этого решения на старте, но сейчас кажется что такое жесткое правило чаще доставляет неудобства и разработчикам и пользователям.

Несколько цитат из чата:

> Люди же так не общаются: Вася со всеми на ты, а Петя со всеми на вы) Мы по этикету изначально обращаемся уважительно на вы. А если общение предполагает более неформальный контекст, то можно сразу предложить перейти на ты. Вот так и нужно в навыках я думаю.

> Мне вот например очень нравится голос Джой, но мне неприятно, что она мне постоянно "тыкает". Поэтому я с ней не общаюсь))

> У меня точно так же, но с Афиной. Голос нравится, а вот "выкание" не нравится. Потому использую Джой.

> Фишкой действительно было бы, чтобы пользователь мог выбрать любой голос, который ему нравится и так же выбирать стиль общения.
Т.е. фишка это когда персонаж полностью настраиваемый.

> а есть исследования, что детям не нравится, что к ним обращаются на Вы? Мне вот нравилось. когда ко мне обращался один учитель на Вы в школе.

_Предложение_: 
Сделать текущее правило обращения на ты/вы рекомендательным (дефолтным), но не обязательным. Если навык в своем сценарии уточнил у пользователя, как к нему лучше обращаться - то он может обращаться так, как хочет пользователь. И этот момент проверять на модерации.

Еще вариант: при онбординге сама платформа уточняет у пользователя, как он хочет чтобы к нему обращался ассистент. И уже это значение отправлять в навыки в поле `character.appeal`.

**Дополнительная информация**:
В будущем наверняка появится возможность определять диапазон возраста пользователя по голосу. 
И если например в навык впервые заходит пользователь условно 40+, то даже для Джой кажется гораздо правильнее не "тыкать", а обратиться на "вы" и уточнить формат общения.

**Comment by subnetsRU** [comment]
Во-первых, плюсуюсь к тикету.

Во-вторых, правильным бы было запросить именно возможность менять official для любого голоса в системе. Ну например:
```
П - пользователь, А - ассистент
П: Позови Джой.
А: Привет! Это Джой. Единственная и неповторимая.
П: Обращайся ко мне на Вы!
А: Хорошо, я Вас слушаю.
```
Всё что нужно будет сделать, чтобы несмотря на character.id Джой установить флаг `character.appeal = official`.
```
П - пользователь, А - ассистент
П: Позови Афину.
А: Здравствуйте! Афина активирована и готова Вам помочь.
П: Обращайся ко мне на ты!
А: Хорошо, я тебя слушаю.
```
Всё что нужно будет сделать, чтобы не смотря на character.id Афины установить флаг `character.appeal = no_official`.

Таким образом это меняется не на конкретный апп, а на всю систему. А в своём аппе это можно реализовать и без помощи Сбера.

**Comment by Genenko-Svetlana** [comment]
Не планируем изменения. Это основополагающие требования - https://developers.sber.ru/docs/ru/basics/about_assistant
