### ISSUE TITLE
Упрощенный способ работы с smart_app_data

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#253]
**Где пригодится фича**: Code
**Описание фичи**: сейчас, чтобы передать что-то из Code на фронт (Canvas App), необходимо городить конструкцию из `$context.response.replies.push`. Если же ранее уже формировались ответы (например, pronounceText был сформирован частично ранее в других стейтах), то конструкция вообще становится сложной. Почему бы не разработать библиотеку, которая брала бы это все на себе, а разработчик лишь `smart_app_data` передавал?

**Comment by Genenko-Svetlana** [comment]
Можно использовать вот такие функции на js и подключить в сценарии:

`function reply(body, response) {
    var replyData = {
        type: "raw",
        body: body
    };    
    response.replies = response.replies || [];
    response.replies.push(replyData);
}

function sendAction(action, context) {
    var command = {
        type: "smart_app_data",
        action: action
    };
    return reply({items: [{command: command}]}, context.response);
}

// Использовать
// sendAction({type: 'INIT', payload: {}}, $context);`

**Comment by and7ey** [comment]
Это будет работать не совсем корректно.
Сделайте несколько state'ов с тегом `a:`, например, и безусловным переходом между ними. В последнем используйте `reply`. В итоге будет озвучено значение `pronounceText` только из последнего `replies`.

Ну и самое главное. Очевидно, что отправка `smart_app_data` - самая необходимая функция при разработке CanvasApp на Code. Зачем **каждому** разработчику прописывать в своем коде функции, что вы указали? Это должно поддерживаться на уровне платформы.

**Comment by Genenko-Svetlana** [comment]
Изменений  в ближайшее время не планируем
