### ISSUE TITLE
Инструмент для создания превью

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#255]
**Где пригодится фича**: везде
**Описание фичи**: сейчас делать превью - это боль. Выставить нужные размеры, скрыть ненужные элементы (или они нужные?), сделать скрины с телефона и обрезать лишнее (почему в браузере отображается не так, как на телефоне при том же разрешении?)
**Дополнительная информация**: можно как addon к Chrome

**Comment by waxerdima** [comment]
А чем не устраивает встроенный механизм в Сhrome, который делает скриншеты? Вот тут есть инструкция как им пользоваться https://lifehacker.ru/kak-sdelat-skrinshot-v-chrome/

**Comment by and7ey** [comment]
Через него, конечно же, и делаю. Но результат отличается от того, что будет на реальном устройстве.
Например, в assistant client есть строка, которая отображает `text`, она отражается поверх кнопок-подсказок (на реальном устройстве такого нет).

**Comment by Genenko-Svetlana** [comment]
Планируем создать подробную инструкцию по снятию скриншотов с помощью АДБ к середине сентября

**Comment by and7ey** [comment]
Вот последний комментарий модератора к моему превью - 
`Панель ассистента на превью не соответсвует действительности https://developer.sberdevices.ru/docs/ru/platform_services/moderation/catalogue#оформление-превью; `

но я превью как раз через assistant client делаю((

**Comment by and7ey** [comment]
В копилку того, что assistant client отражает панель не так, как реальные устройства - 
1) https://t.me/smartmarket_community/28954
2) https://t.me/smartmarket_community/28609

**Comment by Genenko-Svetlana** [comment]
Обогатили документацию по созданию превью: https://developers.sber.ru/docs/ru/studio/smartapp/preview

**Comment by subnetsRU** [comment]
Забыли указать, что панели ассистента на скриншотах быть не должно, т.к. модераторы такое бракуют.

**Comment by Genenko-Svetlana** [comment]
Спасибо!
