### ISSUE TITLE
Внутренняя ошибка сервиса при сборке проекта - Сборка во время модерации запрещена

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#256]
**Где нашелся баг**: Code
**Описание проблемы**: Текст сообщения - Внутренняя ошибка сервиса при сборке проекта
**Проблема воспроизводится у других пользователей?** не знаю
**Дополнительная информация**: В консоли более правильный текст - ```{"error":"Сборка во время модерации запрещена"}```. Его и надо показывать пользователю.

**Comment by and7ey** [comment]
<img width="1439" alt="Снимок экрана 2021-08-24 в 15 03 58" src="https://user-images.githubusercontent.com/900474/130613911-a97ceb6b-ff05-43e7-a43a-ad6fe6049cec.png">

**Comment by elkyspeed** [comment]
@and7ey, у вас смартап в этот момент был уже на модерации? У меня такое сообщение вылезало именно в этот момент. После нажатия кнопочки "Вернуть в разработку" - сообщение пропало.

**Comment by and7ey** [comment]
@elkyspeed да, был на модерации.

**Comment by Genenko-Svetlana** [comment]
@and7ey поправили, проверьте, пожалуйста

**Comment by and7ey** [comment]
Все работает корректно, спасибо.
