### ISSUE TITLE
SmartMarket Studio падает с ошибкой "Что-то пошло не так..."

### ISSUE THREAD

**Issue by elkyspeed** [sberdevices/salute-issues#257]
При тестировании в Эмуляторе Студия падает с ошибкой:
![image](https://user-images.githubusercontent.com/89537895/130829585-f5bd7f9b-8653-4a24-b19f-e77a10f53fb9.png)

Установлено, что ошибка происходит при примении эмоции ассистента zainteresovannost
В момент падения в консоли разработчика ошибка:
![image](https://user-images.githubusercontent.com/89537895/130828847-0a4fb942-ea69-464f-9d4b-73ed1879586f.png)
Пробовал под другим ассистентом - ошибка та же.

**Comment by Genenko-Svetlana** [comment]
Спасибо за сигнал. Обновим эмулятор до 03.09.21

**Comment by Genenko-Svetlana** [comment]
@elkyspeed обновили эмулятор. Проверяйте, пожалуйста!

**Comment by Genenko-Svetlana** [comment]
@elkyspeed обновили эмулятор. Проверяйте, пожалуйста!
