### ISSUE TITLE
Скрытие данных в Code

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#258]
**Где нашелся баг**: Code скрывает "персональные данные" в Диалогах, в логе за звездочками
**Описание проблемы**: суть в том, что это не персональные данные - "в**** пух" (винни пух), "в 1*** году", "Т*** из Про**********" (Трое из Простоквашино), "Пе**** набор" (первый набор), "Том и Дж****" (Том и Джерри). Думаю, надо пересмотреть алгоритм идентификации Персональных данных. Либо вообще его отключить и оставить лишь для тех смартапов/профилей, где разрешено использование SmartProfile.
**Проблема воспроизводится у других пользователей?** думаю, да

**Comment by waxerdima** [comment]
Маскирование данных, требование по защите персональных данных, в ближайшее время не планируем изменений.
