### ISSUE TITLE
Некорректное указание state в Диалогах

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#261]
**Где нашелся баг**: Code
**Описание проблемы**: вижу в диалогах ошибку и указание на конкретный стейт - 
<img width="1165" alt="Снимок экрана 2021-08-27 в 16 32 42" src="https://user-images.githubusercontent.com/900474/131259716-6ed95133-87c0-40af-921d-db607b0a5169.png">
но в этом стейте нет обращения к `.a`. Обращение к `.a` есть в следующем стейте, но, как выяснилось, ошибка и не тут, а еще дальше. Ответ формируется в нескольких стейтах.
**Дополнительная информация**: нужно в текст сообщения об ошибке добавить строку где она возникает. Ну и поправить стейты, если это возможно.
P.S. реализация вот этой фичи - https://github.com/sberdevices/salute-issues/issues/72#issuecomment-773861708 - сэкономила бы мне кучу часов, когда я разбирался в этой проблеме :)

**Comment by waxerdima** [comment]
Класс — это название стейта, в котором началась обработка сообщения клиента, а не там где произошла ошибка.

**Comment by and7ey** [comment]
Это контринтуитивно. И самое главное - никак не помогает найти проблему. Логику надо поменять.

**Comment by Genenko-Svetlana** [comment]
Спасибо за предложение. Взяли задачу в бэклог, но не планируем к реализации в ближайшее время.
