### ISSUE TITLE
Подсветка комментариев в Code

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#262]
**Где нашелся баг**: редактор Code
**Описание проблемы**: редактор Code подсвечивает комментарий серым, если он обозначен символом #.  Но это работает и в теге скрипт! А в теге скрипт правильный символ комментария - //. Более того, компиляция с "комментарием", обозначенным #, успешно проходит. 
**Проблема воспроизводится у других пользователей?** не знаю.
**Дополнительная информация**: надо поправить логику подсветки.

**Comment by Genenko-Svetlana** [comment]
Спасибо за предложение. Взяли задачу в бэклог, в ближайшее время не планируем к реализации.
