### ISSUE TITLE
Несоответствие документации в описании формата ответа обработки платежей

### ISSUE THREAD

**Issue by awinogradov** [sberdevices/salute-issues#269]
[Документация здесь](https://developers.sber.ru/docs/ru/smartservices/smartpay/processing/smartpay-api#%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82-%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%B0) не соответствует реальному ответу:

``` js
error_description: [
    {
      keyword: 'format',
      dataPath: '.requestData.reqBody.invoice.purchaser.email',
      schemaPath: '#/properties/requestData/properties/reqBody/properties/invoice/properties/purchaser/properties/email/format',
      params: [Object],
      message: 'should match format "email"'
    }
  ],
``` 

Relates to https://github.com/sberdevices/salutejs/issues/228

**Comment by Genenko-Svetlana** [comment]
В документации описано верно, но нашли баг на проме. Завели задачу.
