### ISSUE TITLE
Каталог показывает, что chat app "18+", хотя это не так

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#27]
При открытии каталога на Сбербокс, например раздела игры, у многих отображается, что игра "18+", хотя это не так.
В настройках в Studio указаны иные настройки возрастного ограничения.

**Comment by subnetsRU** [comment]
Да, факт, что теперь не у всех игр 18+, но и не то, что указано в настройках в Studio.
Например "крути барабан" и "сто к одному" в Studio указано "0+", а в каталоге висит как "6+".
Почему ?

**Comment by VsevolodKiselev** [comment]
Исправили
