### ISSUE TITLE
Неизвестные теги "ломают" tts

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#270]
**Где нашелся баг**: api, поле `pronounceText`
**Описание проблемы**: если в поле `pronounceText` передать неизвестные теги, то произношение текста не работает. Причем работает это как-то странно - если передать один неизвестный тег, то не произносится только первый bubble. Если передать два неизвестных тега, то не произносятся оба bubble'a. Пример - https://pastebin.com/HwwprEGm (ссылка живет 1 неделю).
**Проблема воспроизводится у других пользователей?** не знаю.
**Дополнительная информация**: неизвестные теги нужны, если делаешь кросс-платформенный навык.

**Comment by Ilchenk** [comment]
@and7ey вы некорректно передаете xml структуру.
Вот так проходит. Тут закрыл тег для 1ого speaker audio и добавил кавычки для второго speaker audio.

<speak><audio text=\"sm-sounds-game-8-bit-coin-1\"/><speaker audio=\"alice-sounds-game-8-bit-coin-1.opus\"/><speaker audio="marusia-sounds/game-8-bit-coin-1"/>Начинаем отличную игру. Я называю по слову из каждой строчки известной песни. Задача игрока — отгадать эту песню. \\n\\nЯ буду вести подсчёт очков. Подробнее об этом рассказывается в помощи.</speak> 

https://www.xmlvalidation.com/
можно использовать xml валидаторы для проверки

**Comment by and7ey** [comment]
Понял, спасибо!
Было бы здорово, если бы вы возвращали ошибку на такой запрос.

**Comment by NikolayPakhomov** [comment]
Такого функционала не планируем, но мы подумаем, как можно улучшить работу с SSML, спасибо за отзыв.
