### ISSUE TITLE
Тег с аудио на странице загрузки аудио

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#271]
**Где пригодится фича**: Code
**Описание фичи**: на страничке загрузки аудио - Контент в Code - выдаются URL, hash загруженного файла. Но для аудио они не нужны. Нужен тег вида `<audio text="sm:/1234/4567/audio/12345KtWQun6lcYj.wav"/>`, а его нет. Приходится руками копировать URL и забирать путь оттуда - очень неудобно.
**Дополнительная информация**: какие-то детали, которые могут помочь в реализации фичи.

**Comment by NikolayPakhomov** [comment]
Добрый день! Спасибо за предложение, обязательно подумаем над реализацией. Со сроками вернемся, как только они будут известны. Тикет временно переносим в отложенные.
