### ISSUE TITLE
Сборка проекта в Code в любой момент

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#273]
**Где пригодится фича**: Code
**Описание фичи**: в настоящий момент во время модерации проекта, его нельзя собирать:
<img width="399" alt="Снимок экрана 2021-11-24 в 11 13 56" src="https://user-images.githubusercontent.com/900474/143256039-5620f232-a237-4bf0-9068-d7fa1c2f0849.png">
+ если я правильно понимаю как это работает, любая модификация проекта в Code, требует его повторной модерации.
Это выглядит странно, потому что у тех, кто делает бэк на Code, получается, меньше возможностей/прав, по сравнению с теми, кто использует SmartAPI и может менять код в любой момент. 
Предлагаю убрать все ограничения и давать собирать и модифицировать код на Code в любой момент, и чтобы изменения отражались без повторной модерации.

**Comment by waxerdima** [comment]
Добрый день, вы можете используя Сode или Graph для написания сценария перейти на схему когда вы в SmartApp указываете Webhook смартапа SmartApp API и в качестве Внешняя ссылка указываете вебхук из Code, который вы можете получить в разделе Публикации (Получить вебхук).
