### ISSUE TITLE
[HTML5, Canvas] Дать возможность загружать разные zip-архивы фронтенда для разных поверхностей

### ISSUE THREAD

**Issue by DenisNP** [sberdevices/salute-issues#277]
## Где пригодится фича:
В разработке сложных кроссповерхностных игр на HTML5.

## Описание фичи:
В обычном браузере для HTML-приложения мы можем сделать "резиновую" вёрстку. Но для игр зачастую это неудобный или вовсе невозможный вариант. Игровые движки как правило оперируют конкретным экранным пространством, а элементы в 2D играх это растровая графика: она не является резиновой.

Качество повысится, если позволить загружать **отдельную сборку под каждую поверхность**. Для телефонов свою сборку игры с большими кнопками и вертикальной ориентацией. Для Портала — другую сборку под разрешение его экрана и тач-управление. Для Боксов — третью сборку под управление пультом и высокое разрешение на телевизорах.

**Comment by Genenko-Svetlana** [comment]
Спасибо за предложение.
Пока такую доработку не планируем.
