### ISSUE TITLE
Умные лампы. Пресет

### ISSUE THREAD

**Issue by ygerzen** [sberdevices/salute-issues#278]
У меня есть три умных лампы. Они висят над одним столом. Дети регулярно просят настроить для разных ламп цвета: красный, зеленый и синий. Мне приходится переключать каждую лампу в цветной режим/либо голосом включать.
Предлагаю сделать фичу, чтобы можно было настраивать пресеты для ламп, чтобы их можно было включать голосом/в мобильном приложении. Например, я сделаю пресет с названием "детский свет", настрою в нём цвет для каждой лампы и буду его включать по команде "включи детский свет в гостиной".

**Comment by Ilchenk** [comment]
Добрый день!
Предлагаем вам написать это предложение в чат поддержки устройств либо оформить его на доске предложений к устройствам: https://bit.ly/sberdevices
Чат: https://t.me/sberdevices_chat
