### ISSUE TITLE
При выборе фона курсор не pointer на карточках

### ISSUE THREAD

**Issue by andreynovikov95** [sberdevices/salute-issues#281]
**Где нашелся баг**: [Jazz](https://jazz.sber.ru/create)
**Описание проблемы**: В настройках при выборе фона курсор не pointer на карточках. Так же можно было бы изменить курсор на скролле, чтобы было понятнее что с элементом можно взаимодействовать с точки зрения UX. Можно еще лучше проработать tabindex (доступность), так как через Tab у меня так и не получилось выбрать другой фон (еще один баг).
![Выделение_028](https://user-images.githubusercontent.com/64052598/158030107-8f044a84-6f3a-4c87-97e2-cc7e3ab2629b.png)
![Выделение_029](https://user-images.githubusercontent.com/64052598/158030111-5330dbf2-e033-4de2-b097-5ff7f77ccb0c.png)

Ожидаемое поведение: В настройках при выборе фона курсор pointer на карточках при наведении на карточку фона и скрола

Фактическое поведение: В настройках при выборе фона курсор **не** pointer на карточках при наведении на карточку фона и скрола

**Проблема воспроизводится у других пользователей?** Да.
**Дополнительная информация**: Например, на чекбокcах в настройках курсор при наведении становится pointer, немного странно что на других элементах другое поведение при наведении мыши, заводит пользователя в заблуждение.
![Выделение_030](https://user-images.githubusercontent.com/64052598/158030212-ca4ef03b-7411-4e21-82bb-8286c50a072e.png)

**Comment by Genenko-Svetlana** [comment]
Спасибо!
Похоже на маленький баг. Берем в бэклог, но с низким приоритетом.
