### ISSUE TITLE
Добавить возможность смартапу переопределить время бездействия

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#31]
Реализовать возможность переопределять значение timeout самому смартапу.

Как продолжение тикета #12

**Comment by talagaev** [comment]
проблема будет решена когда мы переведем внешние чат апы в отедльные вкладки (по аналогии как сейчас ассистент живет). так вот там не будет ограничения вовсе. 
По планам - q1 2021

**Comment by subnetsRU** [comment]
Тогда может статус всё же не "Done", а "Deffered" ?

**Comment by Genenko-Svetlana** [comment]
Срок реализации 31.03.2021

**Comment by Genenko-Svetlana** [comment]
Возвращаем в работу.

**Comment by subnetsRU** [comment]
Надеюсь, что тут всё идёт по плану. Ибо, ну честно, достал этот минимальный таймаут... Чихнуть не успеваешь как всё уже закрылось :(

Прямо крик души уже !

**Comment by Genenko-Svetlana** [comment]
@talagaev  @christinadomanskaya

**Comment by Genenko-Svetlana** [comment]
@subnetsRU  перенос срока на 2-3 квартал 2021 :-(

**Comment by subnetsRU** [comment]
Печальная печаль... Где моё мыло и верёвка...

**Comment by Genenko-Svetlana** [comment]
@subnetsRU не надо так расстраиваться )))
Тикет временно закрываем и переносим в отложенные задачи.

**Comment by subnetsRU** [comment]
К сожалению тут не получается не расстраиваться. Расстраиваюсь не только я, но и, судя по моим логам, пользователи тоже. Таймаут слишком мал, слишком... Чуть отвлёкся и усё, запускай по новой. А при тестировании чего либо так это вообще становится пыткой.

**Comment by Genenko-Svetlana** [comment]
@subnetsRU Понимаю :-(

**Comment by Genenko-Svetlana** [comment]
3 квартал 2021

**Comment by talagaev** [comment]
уже реализовано в новом типе чат-апа, в dialog это делать не будет

**Comment by subnetsRU** [comment]
А что это за новый тип ? Если реализовано, то как этим воспользоваться ?

**Comment by subnetsRU** [comment]
Так кто-то объяснит что было реализовано и как этим чем-то пользоваться?

**Comment by Genenko-Svetlana** [comment]
Новый тип апов  — чат-апы (диалоговые апы в отдельных вкладках, по аналогии с канвас апами). В первую очередь этот тип создавался для длинных диалоговых навыков для того, чтобы пользователи лучше понимали, когда он находится в контексте навыка, решил свои проблемы с навигацией и выходом из скилла. Эти апы отображаются в трее по аналогии с канвас апами.

**Comment by Genenko-Svetlana** [comment]
Все внешние диалоговые навыки ассистента открываются в отдельных вкладках благодаря этом пользователи не будут терять контекст беседы: история общения будет храниться в каждом смартапе отдельно, а значит, пользователи сразу поймут, где они находятся: в болталке с ассистентом или в конкретном смартапе.

**Comment by subnetsRU** [comment]
Это конечно всё здорово, но я так и не понял как это относится к сабжу тикета.

Вот я открыл канвас апп на боксе. Через некоторое время запускается заставка и перекрывает экран канваса. А там, например, выведены обновляемые графики. Я сетевой инженер и наблюдаю за состоянием сети. Или я трейдер и торгую на бирже, а тут бах - заставка! Очень полезно... Что нужно? Правильно, не запускать заставку.

Вот я открыл канвас апп "Мои часы" на портале. Вывел понравившиеся мне электронные часы. Встаю утром, а вместо часов вижу "рабочий стол" портала. Апп был закрыт. Что нужно? Правильно, не закрывать апп, потому что пользователь так не хочет.
