### ISSUE TITLE
В Canvas стандартные кнопки (buttons) нельзя выбрать пультом

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#34]
Приходится изобретать свои. Но зачем тогда нужны стандартные buttons? Может, их не надо тогда показывать на экране вовсе?

**Comment by subnetsRU** [comment]
На самом деле можно. Я вчера тоже столкнулся с этим. 
Если на пульте нажать несколько раз вправо, то есть шанс, что вы переместитесь на кнопки и окажетесь на самой правой кнопке. Нажатие "вниз" ни к чему не приводило, сколько б раз не нажимал.
Кол-во нажатий вправо может варьироваться. Вероятно связано с кол-вом элементов на экране или ещё чем.

ИМХО: нужно оставить штатные тоже. Надо просто понять природу этого явления и принимать решение исходя из этого.

**Comment by and7ey** [comment]
Штатные, конечно, лучше. Тогда нужно сделать, чтобы они работали нормально. 
И нам не придется тогда руками кнопки добавлять.

**Comment by awinogradov** [comment]
> Надо просто понять природу этого явления и принимать решение исходя из этого.

Пульт эмулирует нажатия клавиш клавиатуры: TOP, LEFT, RIGTH, DOWN, ENTER.

**Comment by subnetsRU** [comment]
Это хорошо что он эмулирует.
Но эта информация не помогает в понимании проблемы по переходу на suggestions.buttons с помощью пульта при нажатии, скажем "вниз" (DOWN).

**Comment by Turanchoks** [comment]
Навигация в CanvasApp'ах на Сбербоксе нужно реализовывать самостоятельно. Пульт эмулирует нажатие кнопок стрелочек и кнопки Enter, на них можно завязаться и реализовать свою навигацию. Общее решение для навигации в приложения для ТВ – Spatial Navigation. Мы работаем над тем, чтобы выложить на github нашу реализацию. Сейчас можете попробовать polyfill (https://github.com/WICG/spatial-navigation). Наше решение функционально будет работать так же.

Ниже пример кода для обработки событий от пульта:
```js
document.addEventListener('keydown', (e: KeyboardEvent) => {
    switch (e.key) {
        case 'ArrowLeft':
            // нажатие на пульте влево
            break;
        case 'ArrowRight':
            // нажатие на пульте вправо
            break;
        case 'ArrowDown':
            // нажатие на пульте вниз
            break;
        case 'ArrowUp':
            // нажатие на пульте вверх
            break;
        case 'Enter':
            // нажатие на пульте ок
            break;
        default:
            break;
    }
});
```

**Comment by Turanchoks** [comment]
> Это хорошо что он эмулирует.
> Но эта информация не помогает в понимании проблемы по переходу на suggestions.buttons с помощью пульта при нажатии, скажем "вниз" (DOWN).

На саджесты, к сожалению, пультом никак не перейти и пока не планировали поддержать такое поведение

**Comment by and7ey** [comment]
@Turanchoks, а в чем смысл такого подхода? Зачем каждому разработчику 
(1) самостоятельно рисовать кнопки (хотя они уже и так рисуются в каких-то отдельных случаях) 
(2) реализовывать эту логику?

Почему бы не реализовать такую (единую) логику на стороне Сбера?

**Comment by subnetsRU** [comment]
>На саджесты, к сожалению, пультом никак не перейти 

У меня получалось. О чём я уже писал выше.
Для этого я нажимал нцать раз вправо и оказывался таки на саджестах.
Могу повторить и если надо записать на видео.

А так согласен с **and7ey**. Зачем рисовать отдельно кнопки если они и так рисуются внизу... не ясно.

**Comment by Turanchoks** [comment]
> @Turanchoks, а в чем смысл такого подхода? Зачем каждому разработчику
> (1) самостоятельно рисовать кнопки (хотя они уже и так рисуются в каких-то отдельных случаях)
> (2) реализовывать эту логику?
> 
> Почему бы не реализовать такую (единую) логику на стороне Сбера?

1. Можете, пожалуйста уточнить, какие кнопки?
2. Эта либа при работает на основе положения дом элементов на странице и переводит фокус. Не всем приложениям это подходит.

@subnetsRU скриншот или видео очень бы помогли. Под buttons имеется ввиду HTML buttons ведь? (<button>Кнопка</button>)

**Comment by subnetsRU** [comment]
Буду дома запишу видео.

Нет, под  "Кнопка" я подразумеваю кнопки из suggestions.buttons из JSON, а не html кнопку, которую можно выводить на экране canvas.

Автор тикета так же говорит о них (suggestions.buttons).
Ведь в самом начале он пишет:
>стандартные buttons? Может, их не надо тогда показывать на экране вовсе?

единственные стандартные buttons на экране canvas это suggestions.buttons

**Comment by and7ey** [comment]
все верно, речь про suggestions.buttons

**Comment by subnetsRU** [comment]
>Буду дома запишу видео.

https://dropmefiles.com/lLNqj

>На саджесты, к сожалению, пультом никак не перейти

В видео наглядно видно, что это не совсем так.

**Comment by Turanchoks** [comment]
@and7ey @subnetsRU Понял, спасибо, неверно понял изначальный вопрос.

@talagaev Подскажи, пожалуйста, разобраться

**Comment by subnetsRU** [comment]
Исходя из сегодняшнего общения в zoom, где было сказано что сам апп и 
suggestions.buttons находятся "по разную сторону баррикад", то получается, чтобы это нормально работало, как бы не было печально, надо отказываться от suggestions.buttons и рисовать кнопки внутри canvas самому и делать навигацию самому. 
Но так получается, что при нажатии на кнопку canvas должен как-то передать команду webhook'у. 
Это делается через assistant.sendData() ? Верно ?

**Comment by Turanchoks** [comment]
@subnetsRU Да. Скоро пример этого появится в демо аппе

**Comment by subnetsRU** [comment]
Итак попробовал я assistant.sendData.
На версии 1.0.2 @sberdevices/assistant-client не взлетело.
При нажатии на кнопку в sberbox ассистент сразу выпуливал фразу "навык временно недоступен" и на webhook совсем ничего не приходило, но при этом в браузере это работало.

По совету от **Turanchoks** в ТГ чате обновил assistant-client до версии 1.1.2 и sendData заработала и на sberbox.
Навигация по кнопкам с пульта тоже работает. Я для этого ничего специального в коде не делал, т.е. addEventListener не добавлял.

**Comment by Genenko-Svetlana** [comment]
В Canvas стандартные кнопки (buttons) нельзя выбрать пультом #34 - @and7ey можно закрывать?

**Comment by and7ey** [comment]
Я бы все-таки проработал этот вопрос на вашей стороне более детально.

Сейчас suggestions.buttons в Сбербокс не работают. Итого каждый разработчик должен их делать самостоятельно. Отрицательные стороны этого - 
1) Каждый разработчик делает одно и то же самостоятельно.
2) Не используется уже имеющаяся функциональность - suggestions.buttons.
3) У каждого разработчика будет свой дизайн этих кнопок, свое расположение - у пользователей будет отрицательный опыт использования кнопок.

**Comment by talagaev** [comment]
Я предложил закрыть этот тикет. 
Нажатия на саджесты в канвасах сделать совсем не просто, да и пользоватлю нажать как показали UX тесты не особо и надо, проще сделать голосом переход на след шаг. 
+ мы готовим новый элемент "Подсказки" которые будут вместо саджестов
