### ISSUE TITLE
Увеличить время работы ключа Assistant Client

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#35]
1 день - очень мало. Раз в день приходится делать бесполезное действие.

**Comment by ffDowen** [comment]
К сожалению, мы не планируем в ближайшее время работу по данной задаче.

**Comment by subnetsRU** [comment]
Печально... Ибо я соглашусь с автором тикета.
Дня три бы, хотя бы.

**Comment by and7ey** [comment]
Ну тогда какое-нибудь другое решение надо придумать. Ключ - на неделю, но можно запускать только свой навык.

И, кажется, некорректно перемещать невыполненные задачи в Done. Сделайте колонку Cancelled что ли ;).
