### ISSUE TITLE
Блок Ввод числа в Graph работает некорректно

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#4]
Блок Ввод числа с голосовым вводом сейчас использовать нельзя, т.к. голосовой ввод не работает корректно (123 распознается как 1пробел2пробел3, а потому числом уже не считается).
Использую сейчас Ввод текста. А затем делаю преобразование - 

`$tg_user_id = String($tg_user_id).toLowerCase().replace(/восемь/g, '8').replace(/семь/g, '7').replace(/шесть/g, '6').replace(/пять/g, '5').replace(/четыре/g, '4').replace(/три/g, '3').replace(/два/g, '2').replace(/один/g, '1').replace(/единица/g, '1').replace(/ноль/g, '0').replace(/\D/g,'')`

(если человек скажет "восемьдесят пять", например, то это уже не сработает)

затем проверку, что получилось число - 

`!isNaN($tg_user_id)`

а потом отдельным блоком говорю, что все плохо, если число не получилось.

Почему бы эту логику просто не встроить в Ввод числа?

**Comment by Genenko-Svetlana** [comment]
Срок реализации 11.12.2020

**Comment by Genenko-Svetlana** [comment]
@asmalakhov-sberdevices 11.12.2020 удалось реализовать?

**Comment by asmalakhov-sberdevices** [comment]
@and7ey @Genenko-Svetlana 
запрос частично реализован. 
Проблемы с вводом чисел "восемьдесят пять" и т.д. была исправлена. 

Запрос на склеивание ввода "один два три ..." пока отложен на анализ, так как быстро реализовать не удалось. По срокам, не ранее q2 21.

**Comment by Genenko-Svetlana** [comment]
Тогда этот тикет закрываю и переношу в отложенные (переоткроем в след.году). 
Срок - 30.06.2021

**Comment by Genenko-Svetlana** [comment]
Возвращаем в работу

**Comment by Genenko-Svetlana** [comment]
@and7ey исправлено, проверяйте, пожалуйста
