### ISSUE TITLE
Graph некорректно работает с "пустыми переменными"

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#44]
**Где нашелся баг**: Graph
**Описание проблемы**: 
<img width="393" alt="Снимок экрана 2020-11-12 в 10 17 53" src="https://user-images.githubusercontent.com/900474/98907837-85b59700-24d0-11eb-8175-bf5abfabdbd6.png">
при таком коде, где $te - пустое значение, следующий блок просто не срабатывает (текст не выводится), а при `$te=" "` (с пробелом) все работает.

**Comment by Genenko-Svetlana** [comment]
Срок реализации - 31.12.2020

**Comment by voipp** [comment]
Блок условия с пустой строкой выполняется как javascript код:
`if: $session.te = ""`
а этот код работает правильно :http://www.ecma-international.org/ecma-262/5.1/#sec-9.2
операция присваивания вернет пустую строку в условие, а if-условие с пустой строкой вычисляется в false

а блок условия с непустой строкой всегда вернет true

**Comment by and7ey** [comment]
Не очень понял каким тогда должно быть решение. Протянуть еще одну связь из `else` в текстовый блок? И тогда в $te будет пустота? 

Почему `if: $session.te = ""` возвращает `true`, разве не должно быть `undefined`?

**Comment by voipp** [comment]
@and7ey  проверка с пустой строкой вернет false
вот пример работы js : http://jsfiddle.net/57coetar/
ссылка на ecma выше

**Comment by voipp** [comment]
> 
> 
> Не очень понял каким тогда должно быть решение. Протянуть еще одну связь из `else` в текстовый блок? И тогда в $te будет пустота?

все зависит от того чего вы хотите добиться

**Comment by and7ey** [comment]
Хочу присвоить переменной $te пустое значение. Чтобы потом использовать для обращения на "ты" или "вы" -  например, `хоти$te продолжить игру?`.

**Comment by asmalakhov-sberdevices** [comment]
@and7ey Да, как обходной путь связать else в тот же тестовый блок. 
ну или как и сейчас, обыграть это с пробелом в тексте.

**Comment by asmalakhov-sberdevices** [comment]
@Genenko-Svetlana предлагаю закрыть тикет. 
Это нормальное поведение для JS условия.
