### ISSUE TITLE
Canvas и finished=true на сбербокс

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#45]
**Где нашелся баг**: в завершении canvas смартапа на сбербокс. 
**Описание проблемы**: запускаем canvas. Затем webhook'ом присылаем finished=true и сессия завершается со стороны смартапа, но окно canvas не убирается с экрана, т.е. сберокс не возвращается на домашний экран. 
**Проблема воспроизводится у других пользователей?** да. 
**Дополнительная информация**: если завершать canvas штатной фразой "хватит", то все работает корректно. Приставка возвращается на главный экран.

**Comment by sasha-tlt** [comment]
@subnetsRU, попробуйте вызывать assistant.close (https://github.com/sberdevices/assistant-client#close-void) или window.AssistantHost.close (если не используете @sberdevices/assistant-client) на фронтенде.

**Comment by Genenko-Svetlana** [comment]
Canvas App сам должен прислать close_app в sdk, когда закончил сценарий. Рекомендацию про самозакрытие Canvas App добавим в документацию на следующей неделе.

**Comment by subnetsRU** [comment]
Хорошо, попробую отпишусь.

**Comment by Genenko-Svetlana** [comment]
Ок, ждём обратную связь

**Comment by subnetsRU** [comment]
Вызов assistant.close() закрыл "окно" и вернул бокс на главный экран.
Спасибо.

>добавим в документацию

Да, было бы здорово, т.к. это не очевидно.

**Comment by Genenko-Svetlana** [comment]
Очень хорошо! В документацию добавим.
