### ISSUE TITLE
Мониторинг смартапов

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#46]
Сегодня в zoom было сказано про мониторинг смартапов. О чем до сих пор не было известно и в документации я не видел, чтобы это как-то упоминалось. 
Так же было озвучено наказание, если апп не работает, в виде удаления из каталога. 

Просьба озвучить условия по которым работает (или будет работать) система вашего мониторинга.
Как она работает?
Что конкретно мониторится?
Каковы условия для удаления из каталога?
Временные рамки? 
Будут ли какие-то уведомления, предварительно, на почту разработчика смартапа? Или сразу "секир башка"? 
Будет ли доступна информация из этой системы разработчику навыка? (графики или иное) 
Влияет ли это на рейтинг смартапа? 

Ну вообщем максимальная информация по данному вопросу.
Ведь, как минимум, есть понятие "регламенты работы", которые могу производится на сети и  которые могут сопровождаться простоями.
Да и просто неисправности. Сети, роутера, сервера, по и так далее. 

Все заинтересованы в том, чтобы смартап работал. 
Посему надо иметь понимание в этом вопросе.

**Comment by xoxulin** [comment]
В ближайших релизах тема состояния "Веременно выключено" будет освещена. Важный момент – при расследовании инцидентов со внешними навыками будет задействована прямая коммуникация с разработчиками. Процесс не ставится в терминах "удаления из каталога", а скорее в терминах защиты и информировании пользователей девайсов – дескать "навык сейчас недоступен, мы разбираемся".

Причины могут быть разные, но типов два:

1. технические: сеть, падения бэка, регламентные работы (без выключения смартапа в Студии) или что-то еще,
1. контентные: в навыке могут быть замечены нарушения правил, по которым приложение проходило модерацию (в большей степени смартапы на внешних хуках и Canvas Apps где контент менее контролируем на стадии модерации). Например, это может быть нецензурная лексика, контент не по возрасту, запрещенный законодательством контент – это может быть как в полуавтоматическом режиме замечено, так и принято в виде жалобы от внешнего пользователя.

Реакция может быть сверхбыстрой в зависимости от рисков, но не волнуйтесь – драконовских санкций точно не планируется, мы исходим из принципа "презумпция невиновности", то есть на время выключить навык мы обязаны, как разберемся с причинами, примем решение и не без уведомления сообщим его разработчику.

**Comment by subnetsRU** [comment]
По первому типу: Как именно это мониторится ? Ваш бот/сотрудник ходит и запускает смартапы как обычный пользователь ? Что является фактом фиксирования тех.сбоя ? Смартап единожды не ответил ? Не единожды в рамках определённого времени ? Какого ?

2. 
> "нецензурная лексика" 

но тут же может быть такое, что ассистент повторил фразу клиента, который матерился, а код смартапа либо не валидирует либо ошибочно не понял, что это мат и повторил за клиентом. Например в игре, чтобы уточнить правильно ли распознался ответ, ассистент его повторяет. Как быть в таком случае ? Как работает этот "полуавтоматический режим" ? Ибо я сомневаюсь, что пользователь, который выругался, пойдет жаловаться на то, что смартап повторил его мат.

>"презумпция невиновности"

Очень на это надеюсь, что не будут рубать шашкой по чиху пользователя, а всё же предпринимать попытки разобраться в ситуации и выслушать обе стороны.

**Comment by xoxulin** [comment]
> По первому типу: Как именно это мониторится ? Ваш бот/сотрудник ходит и запускает смартапы как обычный пользователь ? Что является фактом фиксирования тех.сбоя ? Смартап единожды не ответил ? Не единожды в рамках определённого времени ? Какого ?

Бот обходит навыки, корзинки запросов формируются подвыборкой из живого потока, если процент неответов навыка переходит некоторую отметку, то тест-отчет "краснеет" – дале реагируют люди. Технические детали будут отдельно опубликованы, когда алгоритм вступит в боевое дежурство.

> "нецензурная лексика"
> но тут же может быть такое, что ассистент повторил фразу клиента, который матерился, а код смартапа либо не валидирует либо ошибочно не понял, что это мат и повторил за клиентом. Например в игре, чтобы уточнить правильно ли распознался ответ, ассистент его повторяет. Как быть в таком случае ? Как работает этот "полуавтоматический режим" ? Ибо я сомневаюсь, что пользователь, который выругался, пойдет жаловаться на то, что смартап повторил его мат.

Факт повтора легко проверяется по логам. Важен сигнал, когда сам навык генерирует неприемлемый ответ.

**Comment by subnetsRU** [comment]
>Факт повтора легко проверяется по логам.

Безусловно. Но будет ли это делать "полуавтоматический режим" ?

>сам навык генерирует

Сомневаюсь, что кто-то из разработчиков захочет, чтобы его навык общался с пользователем матом... Слабо себе представляю такую ситуацию, но не отрицаю, что она возможна.

**Comment by xoxulin** [comment]
> Безусловно. Но будет ли это делать "полуавтоматический режим" ?

Пока нет.

> Сомневаюсь, что кто-то из разработчиков захочет, чтобы его навык общался с пользователем матом... Слабо себе представляю такую ситуацию, но не отрицаю, что она возможна.

Если навык под капотом реализован на ML, то однозначно на это нельзя полагаться – это может происходить даже без осознания разработчиком.
