### ISSUE TITLE
Приведенение $entities к единообразию

### ISSUE THREAD

**Issue by snyuryev** [sberdevices/salute-issues#47]
$entities undefined при обработке команды (action_id) сценарием Code
Просьба сделать пустой массив, как в случае если бы пользователь сказал фразу и ней не были распознаны сущности.

**Comment by asmalakhov-sberdevices** [comment]
@snyuryev 
Пока обсудили внутри, и решили, оставить как есть. 
Так как в целом это разные ситуации и возможно кто-то завязан на текущем поведении. Изменение может заафектить некоторые сценарии.

Возможно, если запросов по этой теме от разработчиков будет больше, вернемся к вопросу. 

@snyuryev а в чем основное неудобство сейчас? только в том, что нужно делать дополнительную проверку в условии?

**Comment by snyuryev** [comment]
да, дополнительная проверка.
может быть как-то в документации отразить? 
я первый раз подумал что как $client и др. JS API: переменные $entities всегда чем-то заполнены.

**Comment by Genenko-Svetlana** [comment]
@Lytkini 
может быть как-то в документации отразить?
я первый раз подумал что как $client и др. JS API: переменные $entities всегда чем-то заполнены.

**Comment by Genenko-Svetlana** [comment]
@oblomil @Lytkini посмотрите в части документации, пожалуйста, и напишите комментарий.
Тикет переоткрыла.

**Comment by Lytkini** [comment]
Добавили уточнение в [документацию](https://developer.sberdevices.ru/docs/ru/developer_tools/ide/NLU_core/entities#использование-сущностей).

**Comment by snyuryev** [comment]
@Lytkini спасибо!
