### ISSUE TITLE
Использование музыки СберЗвук в смартапах

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#5]
Можно ли сделать так, чтобы музыка из СберЗвука была доступна в навыках? Было бы полезно для навыков типа "Угадай мелодию" - чтобы не искать свою музыку и чтобы все было законно.

(Понятно, что музыка может появляться и исчезать в каталоге, но разработчики навыков смогут это предусмотреть).

**Comment by KKPotapova** [comment]
Добрый день! С ответом вернемся до конца текущей недели.

**Comment by xenia-molchanova** [comment]
Добрый день! Прошу прощения на задержку, получила от ребят из СберЗвука. 

Если коротко - просто передать данные мы не можем, каждый кейс нужно решать отдельно с ребятами из СберЗвука. 
"Просто отдать - ни в коем случае нельзя. Это противоречит юридической договоренности с правообладателями.
Обсудить варианты - можно.
Если есть бизнес кейс, приложения могут напрямую со СберЗвуком подписать договор, мы добавим их в лицензионные соглашения с правообладателями контента, и тогда станет можно".

Для того, чтобы связаться с ребятами из СберЗвука, можно написать мне в телеграм - @ksu_chats

**Comment by vkycniichai** [comment]
@and7ey есть ли дополнительные вопросы по теме?

**Comment by and7ey** [comment]
Пока, видимо, нет. Пока сервисы Сбера не запущены полноценно - речи о бизнес-кейсе быть не может, увы.

**Comment by vkycniichai** [comment]
Тикет закрыт.
Если будет необходимо получить дополнительную информацию по вопросу - контакты указала Ксения выше.
