### ISSUE TITLE
Расширить стандартных пакет иконок в plasma ui

### ISSUE THREAD

**Issue by snyuryev** [sberdevices/salute-issues#50]
Просьба добавить
"Информация" 
"Share"

**Comment by Yeti-or** [comment]
Иконки расширим, про инофрмацию будет что-то такое: 
<img width="326" alt="info" src="https://user-images.githubusercontent.com/1813468/99246015-a7d35000-2815-11eb-95cf-a6085419b33a.png">

 
@snyuryev Расскажите какое действие предпологается у иконки share ?

**Comment by snyuryev** [comment]
Спасибо!

По "share" - это "отправить информацию на девайс пользователя"
Простор для использования достаточно большой - отправить на телефон (емейл или любой канал связи) чек или картинку, или ссылку

**Comment by Yeti-or** [comment]
Иконки добавили ещё в прошлом году: https://github.com/sberdevices/plasma/pull/115
Забыли закрыть эту задачу.

Доступные иконки можно посмотреть здесь:
http://plasma.sberdevices.ru/current/components/Icon
