### ISSUE TITLE
Не работают переменные в блоке Ввод текста

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#51]
**Где нашелся баг**: Graph
**Описание проблемы**: 
Не работают переменные в Graph в блоке Ввод текста. "Какой-нибудь текст $var" отображает в салюте "Какой-нибудь текст {{$session.var}}"
**Проблема воспроизводится у других пользователей?** не знаю
**Дополнительная информация**: https://t.me/smartapp_studio/4493

**Comment by Genenko-Svetlana** [comment]
Добрый день! Планируем устранить завтра до конца дня.

**Comment by Genenko-Svetlana** [comment]
Срок реализации - 31.12.2020

**Comment by and7ey** [comment]
В Code если попробовать использовать переменные в InputText, то возникает та же самая проблема.

**Comment by Genenko-Svetlana** [comment]
@skobets @asmalakhov-sberdevices посмотрите комментарий выше, пожалуйста.

**Comment by asmalakhov-sberdevices** [comment]
@and7ey да, так и есть. Блоки ввод текста в реализации использует тэг InputText, поэтому это будет исправлено вместе.

**Comment by asmalakhov-sberdevices** [comment]
@Genenko-Svetlana  проблема исправлена, @and7ey проверьте, пожалуйста. 
Спасибо!

**Comment by NikolayPakhomov** [comment]
Добрый день! Так как @and7ey не ответил, а проблема исправлена, задачу закрываю. Если сложности остались, дайте знать.
