### ISSUE TITLE
Пример ScrollList не работает (plasma ui)

### ISSUE THREAD

**Issue by snyuryev** [sberdevices/salute-issues#53]
Пример ScrollList не работает
https://plasma-docs.netlify.app/components/ScrollList

Где объявлен **markerRef** ?

Item и key отсутствуют в StyledListItem
**<StyledListItem item={item} key={item.id} />**

**Comment by Yeti-or** [comment]
Перерабатываем компонент, https://github.com/sberdevices/plasma/pull/73/

В данном случае действительно ошибка в документации, должен быть не markerRef а ref:


```
    const ref = React.useRef<HTMLDivElement | null>(null);
    const ctx = React.useContext(ListContext);

    React.useEffect(() => {
        ctx.register(ref);

        return () => ctx.unregister(ref);
    }, [ctx]);



```

**Comment by snyuryev** [comment]
Спасибо за информацию!

**Comment by snyuryev** [comment]
Уже не актуален с появлением Carousel
