### ISSUE TITLE
Странное озвучивание текста ассистентом.

### ISSUE THREAD

**Issue by snyuryev** [sberdevices/salute-issues#54]
Навык работает через вебхук.
Выбран персонаж Сбер.
Проверял на приложение Сбер Салют iOS

По непонятной причине  вместо "из сети" озвучивает "из **стационарной** сети"

**Comment by Genenko-Svetlana** [comment]
Сергей, добрый день!
Пришлите, пожалуйста, json

**Comment by RulevAnton** [comment]
Проблему воспроизвел, зевёл дефект.
В след релиз постараемся успеть, к 18.11 - 19.11.

**Comment by snyuryev** [comment]
Отлично!

**Comment by Genenko-Svetlana** [comment]
@snyuryev проверяйте, пожалуйста

**Comment by RulevAnton** [comment]
Коллеги, обновление ещё не выехало, надеемся на сегодня, что раскатим на ИФТ, проверим и вечером покатим.
Если не успеем, то уже на след. неделе.

**Comment by Genenko-Svetlana** [comment]
@RulevAnton  Антон, удалось реализовать? Вчера на конференции прозвучало, что нет.

**Comment by RulevAnton** [comment]
Разработчики сделали, релиз запланирован на 02.12.

**Comment by RulevAnton** [comment]
@snyuryev Добрый день! Можно проверять и закрывать, исправление на проде.
На своей стороне проверили.

**Comment by snyuryev** [comment]
@RulevAnton Спасибо! Проверю.

**Comment by RulevAnton** [comment]
Тикет закрываю.
