### ISSUE TITLE
Assistant client: Uncaught DOMException: Failed to execute 'start' on 'AudioBufferSourceNode': cannot call start more than once.

### ISSUE THREAD

**Issue by snyuryev** [sberdevices/salute-issues#55]
Такую ошибку можно увидеть в консоли если приходит новый респонс от бэкенда во время озвучивания текста с предыдущего респонса. 

Режим: дебаг
Версия assistant client 1.1.2

**Comment by sasha-tlt** [comment]
@snyuryev, выпустили версию 2.0.0 - в нее включили исправление данной проблемы

**Comment by snyuryev** [comment]
@sasha-tlt спасибо, проверю
