### ISSUE TITLE
Некорректно работает кнопка Отправить на клавиатуре в Сбер Салюте на Android

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#57]
**Где нашелся баг**: Сбер Салют на Android
![photo_2020-11-17 10 05 46](https://user-images.githubusercontent.com/900474/99357286-b6c10d80-28bc-11eb-9212-31586517fbf2.jpeg)
**Описание проблемы**: кнопка отправки сообщения на клавиатуре Android работает странно - после нажатия кнопки клавиатура скрывается (зачем? при использовании зеленой кнопки со стрелкой вверх - клавиатура не скрывается), а само текстовое сообщение в каких-то случаях отправляется, а в каких-то - нет  
**Проблема воспроизводится у других пользователей?** не знаю.

**Comment by Genenko-Svetlana** [comment]
Зафиксировали, поправим, но уже в следующем году.

**Comment by Genenko-Svetlana** [comment]
В сборке салюта, которая в проме 20.12.2.4915 не воспроизводится.
@and7ey  проверьте, пожалуйста.

**Comment by NikolayPakhomov** [comment]
Добрый день! Так как @and7ey не ответил, а проблема исправлена, задачу закрываю. Если сложности остались, дайте знать.
