### ISSUE TITLE
[Салют] После таймаута смартапа кнопки (suggestions) от него остаются на экране.

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#58]
**Где нашелся баг**: в приложении "Салют".
**Описание проблемы**: После того как смартап был закрыт по таймауту его кнопки (suggestions) не убираются с экрана.
![timeout_sugg_bug_scrn](https://user-images.githubusercontent.com/18159237/99379565-e9c5ca00-28d9-11eb-89a6-cd99d97f8daf.jpeg)
Как повторить: запускаем апп, выключаем мобильник. Ждём пять минут, включаем мобильник.
На предыдущей версии Салюта такого замечено не было.

**Проблема воспроизводится у других пользователей?** да.
**Дополнительная информация**: Версия "Салюта" 20.11.0.4145

**Comment by Genenko-Svetlana** [comment]
Зафиксировали, поправим, но уже в следующем году.

**Comment by talagaev** [comment]
это уже можно закрыть, проблема решилась тем, что в Приветствии пояивлся обязательный саджест Каталог, который очищает старые саджесы

**Comment by Genenko-Svetlana** [comment]
@subnetsRU посмотрите, пожалуйста

**Comment by subnetsRU** [comment]
Да, так и есть. Теперь саджесты заменяются.
