### ISSUE TITLE
Canvas App не протестировать из Graph

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#6]
Если запускать Canvas App из Graph, то никакие запросы на frontend endpoint не посылаются. Было бы правильно либо их отсылать, либо хотя бы уведомлять, что Canvas App надо тестировать либо в браузере, либо на СберБоксе/в СберСалюте.

**Comment by asmalakhov-sberdevices** [comment]
Спасибо за инсайт. Добавим задачу об уведомлении в бэклог.

**Comment by Genenko-Svetlana** [comment]
Срок реализации 31.12.2020

**Comment by asmalakhov-sberdevices** [comment]
@Genenko-Svetlana @and7ey сделали дополнительное предупреждение, но в релиз пока это не успело попасть. 
Давайте ожидать в следующем месяце, срок до 31.01.21 сдвинем

**Comment by asmalakhov-sberdevices** [comment]
@Genenko-Svetlana @and7ey предупреждение должно уже отображаться, проверьте пожалуйста.

**Comment by and7ey** [comment]
Уведомление нашел, спасибо!

Теперь бы еще научить Graph все-таки отправлять запросы на front ;)
