### ISSUE TITLE
Не заполняется комментарий при сохранении в Code

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#61]
**Где нашелся баг**: Code
**Описание проблемы**: если нажать сначала кнопку Собрать, а потом кнопку Сохранить в Code, то поле Комментарий не заполняется
**Проблема воспроизводится у других пользователей?** не знаю.

**Comment by asmalakhov-sberdevices** [comment]
@and7ey 
При Сборке - сохранение проекта происходит автоматически. 
Комментарий автоматически заполняется названиями файлов, в которых были изменения. 
После сборки, если изменений не было, то комментарий остается пустым.

**Comment by and7ey** [comment]
Может тогда, если изменений не было, а сохранение произошло автоматически, то кнопку Сохранить надо делать недоступной для нажатия?

**Comment by asmalakhov-sberdevices** [comment]
@and7ey  принято, будем отключать кнопку, если нет изменений.  Добавили задачу себе в бэклог на q1 21, сделаем до 31.03.21.

**Comment by Genenko-Svetlana** [comment]
Возвращаем в работу.

**Comment by Genenko-Svetlana** [comment]
@and7ey проверьте, пожалуйста.
