### ISSUE TITLE
[SBERBOX,SALUTE] Card type grid_card крашит Sberbox и Salute

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#64]
Где нашелся баг: В Sberbox и Salute
Описание проблемы: приставка перегружается и показывает экран "смерти"
Проблема воспроизводится у других пользователей? скорее да, чем нет.
Дополнительная информация: Я разбирался с card grid_card в smartapp api. 
Всё шло неплохо, пока я не попробовал "item_width":"resizable"...
Приводит это к тому, что получая такой JSON приставка не раскрывает шторку с навыком и остаётся на главном экране, но chat app запускается. После некоторого времени на экране появляется надпись "выключение" и приставка уходит в перезагрузку. После чего чёрный экран с ошибкой и путь к сбросу к заводским настройкам.

![sberbox_crash](https://user-images.githubusercontent.com/18159237/99880532-f2ddd080-2c24-11eb-8865-7aa70b5ca5e0.jpg)

Это я **повторил** уже **3 раза**. На третий я уже был готов и снял на телефон как это было. На видео только иконка ассистента не моргала как это было в первый и второй раз.
Видео можно посмотреть тут: https://t.me/sberdevices_chat/2905

Почему я решил что это "resizable" ?

Потому что если его поменять на "small", то проблема не повторяется.
Вот такой JSON: [killer.json.txt](https://github.com/sberdevices/salute-issues/files/5577831/killer.json.txt)

P.S. Версия прошивки 1.63.11

**Comment by subnetsRU** [comment]
Нашелся доброволец - @s41ty
Проблема воспроизвелась и на его сбербоксе.

**Comment by subnetsRU** [comment]
Сейчас проверил сей баг на Салюте.... Салют закрылся сам по себе и теперь при нажатии на кнопку ассистента приложение просто вылетает. 

Видео тут: https://t.me/smartapp_studio/5311

* Остановка приложения и запуск по новой не помогают.
* Очистка кеша и перезапуск тоже не помогли.
* Перезагрузка телефона тоже не спасает.

Помогла только переустановка приложения Салют.

**Comment by subnetsRU** [comment]
Нужна какая-то дополнительная информация по багу ? Или всё понятно ?

**Comment by Genenko-Svetlana** [comment]
Всё понятно, баг в работе

**Comment by Genenko-Svetlana** [comment]
Проблема устранена? Проверьте, пожалуйста.

**Comment by subnetsRU** [comment]
Как же я надеялся, что это утверждение, а не вопрос.... Что знак вопроса это просто опечатка.

Нет, проблема **НЕ** устранена. Испытал на Салюте и он снова выпал в осадок и мне снова придётся его переустанавливать.

Простите, но на сбербоксе даже проверять не буду. Мне не очень удобно лазать за телевизор, который висит на стене.

**Comment by Genenko-Svetlana** [comment]
1. resizable в grid_card не поддерживается
2. баг еще в работе

**Comment by sdtestersd** [comment]
Падение Салюта исправлено в версии 20.12.1

**Comment by exitoso** [comment]
Падения мобильного приложения Салют продолжается если отправить resizable в grid_card. Версия мобильного приложения 20.12.1.4689

**Comment by sdtestersd** [comment]
Добрый день!
Просьба уточнить сценарий воспроизведения для приложения Сбер Салют на андроид.

**Comment by exitoso** [comment]
1. В чате прошу ассистента запустить мой смарт апп 
2. Ассистент обращается к моему серверу и получает json. В json у card установлено поля "item_width" в значение "resizable". Если кроме card я отправлял еще и bubble, то приложение не падает, если отправил только card, то приложение падает.
3. После получения сообщения приложение аварийно закрывается
4. Если повторно зайти в приложение и нажать на кружок вызова ассистента приложение аварийно закроется.
[error_message.txt](https://github.com/sberdevices/salute-issues/files/5695717/error_message.txt)
[mobile_error.zip](https://github.com/sberdevices/salute-issues/files/5695719/mobile_error.zip)

**Comment by sdtestersd** [comment]
Как я понимаю этот навык доступен только тебе, попробую воссоздать еще раз.
Спасибо.

**Comment by exitoso** [comment]
Да, навык доступен только мне.

**Comment by sdtestersd** [comment]
Отпишусь по результатам исправления.

**Comment by sdtestersd** [comment]
Падение исправлено, но не попало в 20.12.1.
Исправление влилось в 20.12.2.
Просьба проверить на своем навыке после обновления.

**Comment by Genenko-Svetlana** [comment]
@sdtestersd  версия 20.12.2.  для Android уже вышла?

**Comment by sdtestersd** [comment]
20.12.2. для Android уже доступна для обновления.

**Comment by subnetsRU** [comment]
Android версия обновилась до 20.12.2.4915.

Проверил. Теперь с item_width: "resizable" на экран теперь вообще ничего не выводится и, соответственно, приложение не падает.

**Comment by subnetsRU** [comment]
Эммм.... Closed ? А как же фикс для сбербокс ? Пускай дальше крашится ? :D

**Comment by Genenko-Svetlana** [comment]
@sdtestersd, а по SberBox устранили проблему?

**Comment by sdtestersd** [comment]
@nasdspb подскажи пожалуйста по статусу исправления дефекта в SberBox, в какой версии можно проверить исправление?

**Comment by Genenko-Svetlana** [comment]
@nasdspb подскажи, пожалуйста, по статусу исправления дефекта в SberBox, в какой версии можно проверить исправление?
@talagaev

**Comment by Ibragimow** [comment]
@subnetsRU проверьте, пожалуйста, сейчас. На прошивке 1.67 уже не должно воспроизводиться. 
Если вдруг актуально, уточните, пожалуйста, версию прошивки в ответном комментарии.

**Comment by subnetsRU** [comment]
А вы на себе уже проверили ? Точно не воспроизводится ?

**Comment by Ibragimow** [comment]
@subnetsRU да, конечно. У нас всё хорошо.

**Comment by subnetsRU** [comment]
Хорошо, проверю и отпишусь, но скорее всего уже завтра. 

Бокс дома. Если мне не изменяет память, то сейчас на нём прошивка 1.67.37.

**Comment by Ibragimow** [comment]
Для истории:
https://sbtatlas.sigma.sbrf.ru/jira/browse/ATHENADEV-3982 
https://sbtatlas.sigma.sbrf.ru/jira/browse/ATHENADEV-3922
https://sberdevices.slack.com/archives/CKT4U1HND/p1609228417430000

**Comment by subnetsRU** [comment]
Проверил. Проблема больше не воспроизводится. Версия прошивки бокса 1.67.37.
