### ISSUE TITLE
Отсутствуют кнопки (саджесты) при первом запуске смартапа на сбербокс и сберпортал

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#7]
Запускаем смартап на Сбербокс. 
В ответе от смартапа в payload присутствует:
`"suggestions":{"buttons":[{"title":"test","action":{"type":"text","text":"test"}}]}`
Но на экране кнопка (саджест) отсутствует. Появляется только при последующих запросах в смартап.

**Comment by talagaev** [comment]
Светлана, а можете этот тоже к нам перенести в QA - похоже на баг

**Comment by subnetsRU** [comment]
Ещё вчера точно не работало. 
Сегодня, работает у chat app, но не работает на canvas app. 

Уже исправили, но не успели отписать?
Исправилось само, потому что поправили что-то еще?
Иное?

**Comment by vkycniichai** [comment]
Исправлено в ChatApp. Для Canvas app ведется работа над фиксом.

**Comment by talagaev** [comment]
https://sbtatlas.sigma.sbrf.ru/jira/browse/ATHENADEV-3922

**Comment by talagaev** [comment]
> проблема была в смартапе техасский холдем покер на сбербоксе, но затем разработчик пофиксил свой навык убрав сайджесты и добавил карточки

в других канвас апах проблема не воспроизводилась

**Comment by subnetsRU** [comment]
Да, я убрал сайджесты, т.к. надо было решать проблему на которую указывали модераторы.

Сейчас проверил, вернул сайджесты и вижу что проблема по прежнему актуальна. При первом запуске сайджестов на экране нет, не смотря на то, что в JSON они есть.
```
[31.12.2020 11:45:19.8765]
"messageId":1609404315665795000,"sessionId":"3808e686-0f17-41b2-84c8-d569d3673e5e"
```
И такая ситуация на всех канвасах.

P.S. Не понимаю как она у вас не воспроизводится. Может у вас другая прошивка на боксе ? У меня сейчас 1.67.37.
Если вы хотите потестировать, то можете написать мне в ТГ и я верну саджесты для вашего user_id.

**Comment by snyuryev** [comment]
@talagaev @subnetsRU Аналогично, саджесты не отображаются при первом запуске на Сбербокс - приложение Курс биткоина. Отображаются только если что-то сказать и получить ответ от приложения (сами саджесты отправляются из сценария всегда)

**Comment by Genenko-Svetlana** [comment]
Срок реализации - 31.03.2021

**Comment by subnetsRU** [comment]
На Сберпортале точно такая же проблема.

**Comment by subnetsRU** [comment]
Можно ли уточнить срок ?

**Comment by Genenko-Svetlana** [comment]
Перенос срока реализации на 3 квартал 2021.

**Comment by talagaev** [comment]
перенос на q4

https://sbtatlas.sigma.sbrf.ru/jira/browse/ATHENADEV-3922

**Comment by Genenko-Svetlana** [comment]
Временно закрываем и переносим в отложенные задачи

**Comment by and7ey** [comment]
@xoxulin Алексей, добрый день, я правильно понял ответ на вчерашнем митапе - этот issue в ближайшее время будет исправлен вместе с обновлением эмулятора?

**Comment by Genenko-Svetlana** [comment]
Срок - 31.03.2022
