### ISSUE TITLE
Добавить в Plasma UI Kit компонент с кнопками, заменяющими suggestions

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#70]
**Где пригодится фича**: Plasma UI Kit, CanvasApp
**Описание фичи**: сейчас в CanvasApp не поддерживаются стандартные suggestions (https://github.com/sberdevices/salute-issues/issues/34), потому каждый разработчик вынужден добавлять эти кнопки самостоятельно. В итоге - в каждом смартапе они будут свои (разного размера, цвета, с разными шрифтами, расположением и т.п.). Нужно сделать компонент, который упростит работу разработчиков апов и сделает эти кнопки одинаковыми во всех апах. 
**Дополнительная информация**: в идеале, надо сделать так, чтобы при нажатии на эти кнопки отправлялся приложению текст, который на кнопке написан (а еще лучше - отдельно задан в свойствах кнопки). Тогда на стороне бэка не придется делать отдельную обработку событий при нажатии на такие кнопки.

**Comment by Yeti-or** [comment]
@and7ey можете приложить пару скриншотов о каких кнопках идет речь
видео из https://github.com/sberdevices/salute-issues/issues/34 перестало работать

**Comment by and7ey** [comment]
<img width="862" alt="Снимок экрана 2020-11-26 в 12 34 09" src="https://user-images.githubusercontent.com/900474/100333589-d3a7c000-2fe3-11eb-814f-f4c64ef8b060.png">
три кнопки слева - надо рисовать вручную

аналогичные кнопки справа - это то, что рисуете вы сейчас (но в боксе они то рисуются, то нет, а модераторы требуют их заменять на вручную добавленные кнопки)

**Comment by Yeti-or** [comment]
Спасибо стало понятнее;

**Comment by Yeti-or** [comment]
После обсуждений в связанном тикете :
https://github.com/sberdevices/salute-issues/issues/34#issuecomment-747303147
```
Нажатия на саджесты в канвасах сделать совсем не просто, да и пользоватлю нажать как показали UX тесты не особо и надо, проще сделать голосом переход на след шаг.

мы готовим новый элемент "Подсказки" которые будут вместо саджестов
```

Пришли к выводу что необходимости реализовывать данную фичу в Plasma UI Kit нет
