### ISSUE TITLE
Кнопка "Остановить" (апп) в студии должна быть красного цвета

### ISSUE THREAD

**Issue by snyuryev** [sberdevices/salute-issues#71]
Аналогично "Отозвать с модерации".

**Comment by xoxulin** [comment]
Коллеги, а можете чуть шире обосновать это желание. Чисто семантически **Остановить** и **Отозвать с модерации** не опасные и обратимые действия. Красным сейчас обозначены кнопки про **Отключение** и **Удаление** смартапов, они запускают диалог, который просит подтвердить остановку/удаление. Главный вопрос – чем обусловлен выбор красного цвета для приведенных кнопок?
cc @snyuryev

**Comment by xoxulin** [comment]
Договорились голосом в Zoom:

> UX-баг. Можно не заметить как пришёл в Опубликованную версию и вместо отправки на модерацию нажал Выключить, так же легко про это забыть и оставить прод без работающего смартапа.

Я бы кроме покраски в красный цвет всё же ещё и Confirm Dialog лайтовый добавил – дескать "Вы уверены что хотите это сделать?" И для выключения и для отправки / отзыва с модерации.

**Comment by snyuryev** [comment]
опасения что выключишь апп и не заметишь. 
(был момент что я хотел снять с модерации апп, а выключил прод версию - когда открываешь в студии апп то попадаешь в закладку с прод версией)

**Comment by Ivan-Frost235** [comment]
@xoxulin сообщает, что решение будет до 31.01.2021, пока в бэклоге.

**Comment by Genenko-Svetlana** [comment]
Срок реализации 31.03.21

**Comment by xoxulin** [comment]
Мы доуточнили немного кейс красной кнопки – она на странице должна быть одна – тк все остальные реально обратимы. В остальном мы учли что цвет у нее должен быть не базовый primary, а также в местах, где требуется аккуратность (от случайного нажатия например) снабдим дополнительным Confirm диалогом. Выйдет это реально раньше чем конец Q1 – как раз сейчас тестируем новую версию UI и скоро выведем в прод.

**Comment by Genenko-Svetlana** [comment]
@filomat уточни срок, пжл.

**Comment by Genenko-Svetlana** [comment]
@snyuryev реализовано, проверяйте, пожалуйста.

**Comment by snyuryev** [comment]
Спасибо!
