### ISSUE TITLE
Список слов и фраз, которые могут принудительно завершить работу смартапа

### ISSUE THREAD

**Issue by KKPotapova** [sberdevices/salute-issues#73]
Мы готовим список слов и фраз, которые могут принудительно завершить работу смартапа, но при этом нужны для выполнения сценариев.
Чтобы избежать неожиданностей и дать вам больше возможностей для создания богатых возможностями приложений, мы предлагаем вам поделиться словами и фразами, которые пригодятся в ваших смартапах и не должны их выключать.
Например, слово «хватит» и т. п.
Предлагайте ваши варианты в комментариях к данному запросу.

**Comment by KKPotapova** [comment]
Комментарий в канале Телеграм от @SergeyCool: 
А почему не оставить только "хватит"? Остальные типа "Выход" или "Завершить" уже сами разработчики добавят с сценарий. Я потому и ответил, что только за 1 слово. Оно уже в ходу у Алисоманов, многие привыкли. А вот когда навык/смартап прерывается по другим словам, то для многих разработчиков это часто воспринимается, как лезть в личные дела апа. Но это лишь моё мнение.

**Comment by subnetsRU** [comment]
Наверно стоит сначала запостить текущий список:
* перестань;
* завершить сценарий;
* выйти из сценария;
* выйти из приложения;
* закройся;
* выйти;
* выйди;
* сверни;
* сворачивай;
* надоела;
* надоел;
* надоело;
* стоп;
* хватит;
* прекрати;

Даже не смотря на то, что слово "хватит" губительно для моего смартапа я даже не буду предлагать его убрать. Мне кажется это самое то для озвучивания желания покинуть смартап.

Я предложу иное, а именно каким-то образом иметь возможность смартапу сообщить платформе о том, что некое стоп слово её списка это для него норма и он сам позаботится о том, чтобы сообщить пользователю как выйти.

Если же идти только путём составления списка слов, то, на мой взгляд, он должен быть минимальным и точно исключать слова: _выход, выйти, стоп, сверни, сворачивай, закройся, закрой_

Ибо для многих навыков это нормальные слова. Лично я, в своих смартапах, сам поддерживаю множественные команды для выхода, которые я собирал исходя из общения пользователей с навыком (имею привычку читать логи). А если звучит фраза, которая похожа на нечёткое намерение выйти, то озвучиваю например это: "Если ты хочешь выйти из игры, то скажи «выход»."

**Comment by snyuryev** [comment]
"вперед"
"назад"
и аналогичные "навигационные" команды не должны прерывать работу аппа
а в целом чем меньше вариантов для закрытия аппа тем лучше для всех

**Comment by Sergeycul** [comment]
Первый мой опыт с ассистентом БЕЗ ЭКРАНА был с колонки Алисы. С семьей запустили навык «Папа Джонс» для шутки и когда поняли, что не можем с него выйти, то попали в тупик. Что только не пытались говорить, в итоге колонка так и осталась в режиме «навыка». В итоге пришлось полностью колонку обнулять и переподключать заново, так что я знаю об этой проблеме. И только потом вычитал в поиске, что надо было сказать «хватит».
Но считаю, что лучше сейчас всем ассистентам прийти к 1 общему правилу (слову), чем делать разные версии и путать пользователя. А то получится, как с зарядками к телефону – идея одинаковая, а шнурок разный.

**Comment by and7ey** [comment]
Поддерживаю вариант с одним словом "хватит".

**Comment by noskoviv** [comment]
Слова/фразы - их должно быть минимально - согласен
как вариант - в каждом апе должно быть в настройках перечень завершающих слов которые переопределяют глобальные слова

**Comment by noskoviv** [comment]
и это список слов/фраз (которые должны переопределять глобальные) должен быть не только на завершение...
у меня на фразе Новости - срабатывает глобальная фраза, и мои интенты не отрабатывают

**Comment by xoxulin** [comment]
Почему-бы этот конфиг не пробрасывать на каждую сессию в самом начале в виде отдельного session-manifest-сообщения – дескать «я начинаю сессию и из нее можно выйти вот так "хватит", а еще я хочу чтобы в моем чате фоном был градиент зеленого цвета, а в заголовке было написано "Кастомизируемый заголовок"».

**Comment by Sergeycul** [comment]
Много думал над этим вопросом. И в итоге вот такой баланс предложил бы:
1. Слово «Хватит» - выход из любого апа.
2. При модерации – разработчик должен сделать в апе саджест выхода, но эту кнопку может назвать сам по стилю игры. Например «Выход» или «Завершить». Без этого ап не проходит модерацию.
Таким образом, есть универсальная фраза + есть подсказка на экране.
