### ISSUE TITLE
Assistant client: добавить возможность отправки текста

### ISSUE THREAD

**Issue by snyuryev** [sberdevices/salute-issues#75]
"sendText" - по аналогии с "sendData"
"sendText" - альтернатива произнесенному пользователем тексту

**Comment by Turanchoks** [comment]
@snyuryev 👋 
Расскажите, пожалуйста, какой у вас кейс? 

sendText – есть такой внутренний API, через него работает панелька ассистента в режиме разработки локально.

**Comment by subnetsRU** [comment]
Серёг, а действительно в чём смысл ? Ничего же не мешает запихать что угодно в sendData и текст в том числе.

Ну и смысла его отправлять обратно в webhook ? Что есть "альтернатива" ?

**Comment by snyuryev** [comment]
@Turanchoks @subnetsRU некоторым разработчикам бы пригодилась такая функциональность при реализации кастомных саджестов. т.е. на канвас (например вниз) ставятся кнопки и по нажатию на них отправляется текст в бэкенд. 

понятно что в том же Code можно добавить event и ловить sendData вместе с текстом, но у кого-то уже может быть реализован сценарий и адаптация заняла бы меньше время (нет необходимости обрабатывать события)

("альтернатива" - в том смысле что вместо того что бы отправлять голос, мы отправляем уже финальный текст)

**Comment by subnetsRU** [comment]
Ах, это с code связано. Теперь понятно. Сразу б написал ;)

**Comment by and7ey** [comment]
https://github.com/sberdevices/salute-issues/issues/70
здесь я писал о похожем, только в моем issue - более полноценная реализация того же самого)

**Comment by snyuryev** [comment]
@subnetsRU ну не только code, допустим у тебя уже была игра/приложение, портируешь ее через api и добавляешь канвас. возникает необходимость сделать саджесты. и в сценарии code и в своем приложение надо добавлять логику обработки событий (хотя если бы приходил текст то уже ничего добавлять не нужно)

**Comment by Turanchoks** [comment]
С нашей стороны это продуктовое решение. Assistant Client – это лишь обертка над нативными методами, сейчас в нативе нет такого метода. Отпишемся, когда будет продуктовое примем продуктовое решение.

**Comment by Genenko-Svetlana** [comment]
@Turanchoks Павел, есть новая информация?

**Comment by talagaev** [comment]
привет, решили не делать пока sendText, тк сейчас есть sendData, в которую можно положить любую обработку для апа.
