### ISSUE TITLE
Таймаут на HTTP-запросы

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#76]
**Где нашелся баг**: Graph (возможно, есть и в Code)
**Описание проблемы**: сейчас в Graph невозможно задать таймаут на HTTP-запрос. Сторонний сервис может отвечать дольше, чем время, отведенное на ответ смартапа. Нужно (1) дать возможность задавать таймаут на HTTP-запрос, (2) сделать дополнительное условие - что делать, если ответ не получен вовремя (как сейчас задается Завершен с ошибкой). В идеале где-то все-таки сохранять ответ (полученный позднее таймаута), чтобы можно было его все-таки выдать пользователю и не делать http-запрос повторно).
**Проблема воспроизводится у других пользователей?** да

**Comment by asmalakhov-sberdevices** [comment]
@and7ey Добавили задачу себе в бэклог на q2 21 ориентировочно до 01.07.21.

В code возможность настроить таймаут уже есть. 
https://developer.sberdevices.ru/docs/ru/developer_tools/ide/JS_API/built_in_services/http/query.md

**Comment by and7ey** [comment]
Из приведенной документации не очень понятно как будет обрабатываться timeout. Если ответ вовремя не поступил, то `isOk` будет `true` или `false`? Какими будут `error` и `status`?

**Comment by Genenko-Svetlana** [comment]
@oblomil @Lytkini посмотрите про документацию, пожалуйста, и добавьте комментарий. 
Я переоткрыла тикет.

**Comment by Lytkini** [comment]
В настоящий момент проверяем как работает.
По результатам обновим документацию и добавим ссылку здесь.

**Comment by Lytkini** [comment]
При таймауте вернётся объект вида:
```json
{
  "onSuccess": [],
  "onRejection": [],
  "error": "Read timed out",
  "status": -1,
  "response": {},
  "isOk": false
}
```

Уточнили поведение в [документации](https://developer.sberdevices.ru/docs/ru/developer_tools/ide/JS_API/built_in_services/http/query).

**Comment by Genenko-Svetlana** [comment]
@and7ey  посмотрите, пожалуйста, изменения в документации.

**Comment by Genenko-Svetlana** [comment]
@and7ey посмотрите, пожалуйста, изменения в документации.

**Comment by Genenko-Svetlana** [comment]
@and7ey посмотрите, пожалуйста, изменения в документации.

**Comment by Genenko-Svetlana** [comment]
@and7ey посмотрите, пожалуйста, изменения в документации.

**Comment by Genenko-Svetlana** [comment]
@and7ey пока закрываю тикет и переношу в отложенные. Изменения в документацию внесены. 
Срок реализации - 31.07.21.

**Comment by and7ey** [comment]
Прошу прощения за столь поздний ответ. В документации все увидел, спасибо.

Возник другой вопрос. Я в Code открыл проект, сделанный в Graph. В нем используется другой код для http-запроса - 
```
    state: newNode_3
        HttpRequest:
            url = https://example.com
            method = GET
            body = 
            okState = /newNode_4
            errorState = /newNode_6
            timeout = 0
            headers = []
            vars = [{"name":"q","value":"$httpResponse.q"},{"name":"session_id","value":"$httpResponse.session_id"}]
..
    state: newNode_6
        a: Что-то пошло не так. Давай попробуем начать сначала.
        script:
            $reactions.timeout({interval: _.template('3 seconds', {variable: '$session'})($session), targetState: '/newNode_0'});
```

Как здесь обработать таймаут? `$httpResponse.error` будет содержать `Read timed out`? Какой `state` отработает? `errorState`? Или как-то код выше на `query(url, settings)` переписать? Не очень понимаю как организовать  переход на другие ноды в случае успешного/неуспешного ответа, если код на `query(url, settings)` перепишу.

**Comment by and7ey** [comment]
@Genenko-Svetlana в graph добавили таймаут?
https://developers.sber.ru/docs/ru/salute/graph/reference/blocks/http_request - не вижу тут указания на это.

**Comment by waxerdima** [comment]
В graph timeout по-умолчанию сейчас установлен в 5 с. Соответственно если запрос был дольше произойдет разрыв по таймауту и в httpStatus будет записано -1 что описано в документации https://developers.sber.ru/docs/ru/salute/code/js-api/services/http/query соответственно вы в блоке условие можете обработать эту ситуацию и сделать то что вам требуется.

**Comment by and7ey** [comment]
Правильно я понял, что отделить таймаут от другого типа ошибки не выйдет? Например, по таймауту я могу ответить "подождите еще немного", а при 404 - "не удалось получить информацию". Но в Graph такого не сделать?

**Comment by waxerdima** [comment]
Нет не правильно, при таймауте httpStatus  будет равен -1, а при 404 httpStatus будет равен 404, соответственно можно с помощью блока условие разделить это поведение.

**Comment by and7ey** [comment]
Понял. Привел неправильный пример. Смущает вот это - 
>> При ошибке внутри $http-сервиса **или** при истечении таймаута

**Comment by waxerdima** [comment]
Если $http-сервис успеет вернуть любой статус (1xx, 2xx, 3xx, 4xx, 5xx) то он будет в httpStatus если не успеет то будет -1.
