### ISSUE TITLE
Plasma UI Kit: добавить css для различных поверхностей

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#78]
**Где пригодится фича**: для всех CanvasApp
**Описание фичи**: хотелось бы пример CSS, в котором были бы готовые стили для разных разрешений экранов - чтобы не каждый самостоятельно css создавал, а был бы какой-нибудь шаблон. В идеале - еще и обновить текущий пример CanvasApp, куда надо добавить поддержку разных разрешений и ориентаций экранов. Туда же добавить примеры дизайна suggestion buttons (см #70).

**Comment by Yeti-or** [comment]
Привет, а вот такого не хватает? https://plasma-docs.netlify.app/theme
я правильно понял?

**Comment by and7ey** [comment]
Кажется, что нет.
Если открыть один и тот же смартап на Боксе и в Салюте на телефоне, то ориентация экрана, размеры будут разными. Theme как-то адресует этот кейс? Кажется, что theme лишь про цвета. Или я ошибаюсь?

**Comment by Yeti-or** [comment]
Нет для размеров у нас есть https://plasma-docs.netlify.app/utils#detectdevice
расширим пример в нём

**Comment by vkycniichai** [comment]
@and7ey можем закрывать тикет, или есть еще вопросы?

**Comment by and7ey** [comment]
@vkycniichai , а разве есть уже решение, которое закрывает данный вопрос?

**Comment by Genenko-Svetlana** [comment]
@Yeti-or

**Comment by Genenko-Svetlana** [comment]
@Yeti-or

**Comment by Genenko-Svetlana** [comment]
Срок реализации - 1 квартал 2021

**Comment by Genenko-Svetlana** [comment]
Перенос срока реализации - 31.05.21.

**Comment by and7ey** [comment]
Добрый день, получилось сделать?

**Comment by Yeti-or** [comment]
К сожалению вынуждены сообщить что задача постоянно откладывалась в прошлом году, и в текущий квартал она тоже не влезла; Похоже в ближайшее время она не будет сделана; Тикет закрываю, если наши приоритеты изменятся  создадим новый
