### ISSUE TITLE
Документация: что где поддерживается

### ISSUE THREAD

**Issue by and7ey** [sberdevices/salute-issues#79]
**Где пригодится фича**: нужна табличка в Документации
**Описание фичи**: что где поддерживается, а что нет - 

- например, suggestions не поддерживаются на Боксе
- raw ответы не поддерживаются в тестовом виджете в Code (https://t.me/smartapp_studio/5281)
- персонажи (значение в $rawRequest.payload.character.name) не поддерживаются в тестовом виджете в Code и Graph
- https://t.me/smartapp_studio/4884
- картинки в Graph
и т.д.

**Comment by Ibragimow** [comment]
Добрый день! Извините, что так долго не отвечаем. За идею спасибо, но реализовывать ее мы пока не планируем.

**Comment by Nashev** [comment]
Отдельной табличкой вряд-ли будет удобно, а вот про частные страницы документации - указывать в них про какие-то важные частные случаи, наверное, проблем нет? Думаю, отдельные запросы на такие правки по отдельным страницам документации смысл делать есть.. а?

**Comment by Genenko-Svetlana** [comment]
@Lytkini посмотри, пожалуйста
