### ISSUE TITLE
Неправильно работает блок «Ввод числа» в поле «От» - «До».

### ISSUE THREAD

**Issue by Sergeycul** [sberdevices/salute-issues#80]
ГРАФ. Блок «Ввод числа» - если ввести в поле «От» число, которое начинается на первую цифру больше первой цифры поля «До», то такой блок не дает сохранить. Например, от 3 до 20 – сохранить не получится блок, а уже от 3 до 30 блок сохранится нормально.

**Comment by asmalakhov-sberdevices** [comment]
@Sergeycul добавили баг себе в бэклог, постараемся поправить оперативно.

**Comment by Sergeycul** [comment]
Баг исправлен 👌 Затестил!
