### ISSUE TITLE
Неправильно работает блок «Ввод числа» - нельзя использовать без вводного текста.

### ISSUE THREAD

**Issue by Sergeycul** [sberdevices/salute-issues#81]
ГРАФ. Блок «Ввод числа» - очень желательно сделать, чтобы поле «Сообщение» было не обязательным, т.к. это поле нельзя сделать с разметкой синтеза речи + здесь сейчас не работает подстановка переменных. На данный момент выкручивался так: делал изначально блок «Текст», а в поле «Ввод числа» ставил смайлик.

**Comment by asmalakhov-sberdevices** [comment]
Планировали добавить в блоки ввода, возможность использовать разметку https://github.com/sberdevices/salute-issues/issues/21

**Comment by Genenko-Svetlana** [comment]
@asmalakhov-sberdevices  т.е. это дубликат #21? 
По нему срок реализации 31.03.2021.

**Comment by Genenko-Svetlana** [comment]
@Sergeycul, посмотрите, пожалуйста, https://github.com/sberdevices/salute-issues/issues/21.
Если он о том же, то этот тикет я закрою.

**Comment by Sergeycul** [comment]
Я бы не сказал, что это дубликат. Я предложил рассмотреть возможность не задавать поле "Сообщение" как обязательное.

**Comment by Genenko-Svetlana** [comment]
@asmalakhov-sberdevices

**Comment by asmalakhov-sberdevices** [comment]
@Sergeycul хорошо, вернемся к запросу, когда будет добавлять возможность настроить разметку в блоках ввода. 
Постараемся сделать вместе с https://github.com/sberdevices/salute-issues/issues/21

**Comment by Genenko-Svetlana** [comment]
Ок, тогда срок реализации - 31.03.2021.
Пока закрываю тикет и переношу в отложенные.

**Comment by Genenko-Svetlana** [comment]
Возвращаем в работу.

**Comment by Genenko-Svetlana** [comment]
@Sergeycul проверьте, пожалуйста
