### ISSUE TITLE
Неправильно работает блок «Ввод числа»: не воспринимает числа от 80 до 89.

### ISSUE THREAD

**Issue by Sergeycul** [sberdevices/salute-issues#82]
ГРАФ. Блок «Ввод числа» - неправильно воспринимает числа от 80 до 89, съедает часть числа.

**Comment by asmalakhov-sberdevices** [comment]
@Sergeycul такая задача уже есть в бэклоге. Планируем исправить до конца декабря.

**Comment by Genenko-Svetlana** [comment]
Срок 31.12..2020

**Comment by Genenko-Svetlana** [comment]
@asmalakhov-sberdevices  дубликат #4?

**Comment by Genenko-Svetlana** [comment]
@Sergeycul, посмотрите, пожалуйста, #4.
Если он о том же, то этот тикет я закрою.

**Comment by Sergeycul** [comment]
Нет, я описал другую проблему. Также ранее описывал эту проблему Антону Малахову. Отз знает в деталях.

**Comment by Genenko-Svetlana** [comment]
@asmalakhov-sberdevices

**Comment by asmalakhov-sberdevices** [comment]
@Sergeycul да, эту задачу добавляли
@Genenko-Svetlana эти проблемы просто будут исправляться вместе с https://github.com/sberdevices/salute-issues/issues/4

**Comment by Genenko-Svetlana** [comment]
Ок, значит срок исправления такой же - 31.12.2020

**Comment by asmalakhov-sberdevices** [comment]
@Sergeycul проблема была исправлена. Перепроверьте, для проверки лучше использовать новый проект.

**Comment by NikolayPakhomov** [comment]
Добрый день! Так как @Sergeycul не ответил, а проблема исправлена, задачу закрываю. Если сложности остались, дайте знать.
