### ISSUE TITLE
Неправильное воспроизведение текста с разметкой речи.

### ISSUE THREAD

**Issue by Sergeycul** [sberdevices/salute-issues#84]
ГРАФ. Если использовать разметку синтеза речи и в этой строке писать не в 1 строку, а с переносом строки, то потом в этом месте произносит «н».

**Comment by Genenko-Svetlana** [comment]
@asmalakhov-sberdevices

**Comment by Genenko-Svetlana** [comment]
Срок реализации 31.01.2021

**Comment by asmalakhov-sberdevices** [comment]
@Sergeycul исправлено. Проверьте, пожалуйста, что теперь срабатывает корректно. Спасибо!

**Comment by Sergeycul** [comment]
Проверил, все работает теперь корректно. Спасибо. Можно закрывать.
