### ISSUE TITLE
Невозможно вставить саджесты при завершении сценария.

### ISSUE THREAD

**Issue by Sergeycul** [sberdevices/salute-issues#85]
ГРАФ. В конце апа нельзя поставить саджест вместе с текстом, т.к. при блоке «Завершение сценария» вставка кнопки не возможна.

**Comment by asmalakhov-sberdevices** [comment]
@Sergeycul можно пожалуйста подробнее, не совсем понятно, для каких ситуаций это нужно?

После попадания на экран завершения сценария, управление отдается ассистенту и кнопки в любом случае работать не будут. Нужны подробности, о кейсе, который пытаетесь решить.

**Comment by Sergeycul** [comment]
Пример. Скорее всего, в дальнейшем будет какая-то система отзывов по апам. Чтобы подтолкнуть человека проголосовать было бы не плохо в в конце апа вставить кнопку с переходом на оставление отзыва. Или может потребоваться указать кнопку с переходом на сайт.

**Comment by Genenko-Svetlana** [comment]
@asmalakhov-sberdevices

**Comment by asmalakhov-sberdevices** [comment]
@Sergeycul кажется в этом случае, достаточно просто поставить логику получения оценки до блока завершения сценария.

**Comment by Sergeycul** [comment]
Да, но с этого блока тогда как вести к блоку завершения сценария? Можно поставить интентом любой текст и с него вести на завершение, но это костыль.

**Comment by Genenko-Svetlana** [comment]
@asmalakhov-sberdevices

**Comment by asmalakhov-sberdevices** [comment]
@Sergeycul можно и так сделать. 
Но тут скорее лучше добавить несколько интентов, например отдельно интент для каждой оценки, потом например это может быть http запрос в гугл таблицу куда оценка сохраниться, а из блока запроса уже выход из сценария.

**Comment by Genenko-Svetlana** [comment]
@Sergeycul  рекомендации, были полезны? С нашей стороны доработки по факту не требуются.

**Comment by Sergeycul** [comment]
Можно закрыть.
