### ISSUE TITLE
Показывается старое название апа в Code при переименовке в Graph.

### ISSUE THREAD

**Issue by Sergeycul** [sberdevices/salute-issues#86]
ГРАФ-CODE. При переименовании апа в Graph - в Code остается старое название.

**Comment by asmalakhov-sberdevices** [comment]
@Sergeycul а можно подробнее, пожалуйста, описать проблему?
не смогли точно понять, где именно не удается изменить название. 

может быть речь о проблеме https://github.com/sberdevices/salute-issues/issues/23

**Comment by Sergeycul** [comment]
Изначально в Студио назвал игру "Безумный курьер", потом переименовал проект на "Веселый курьер" и так она пошла в каталог. А если зайти в Code, то там в проектах так и осталось старое название "Безумный курьер".

**Comment by Genenko-Svetlana** [comment]
Дубликат #23.
Срок 26.02.2021

**Comment by Genenko-Svetlana** [comment]
@Sergeycul, посмотрите, пожалуйста, #23.
Если он о том же, то этот тикет я закрою.

**Comment by Sergeycul** [comment]
Да, не заметил. Получилось, что это дубликат.

**Comment by Genenko-Svetlana** [comment]
Спасибо. Закрываю, как дубликат #23 (срок решения 26.02.2021)

**Comment by Genenko-Svetlana** [comment]
Изменился срок реализации - до 31.05.21. Тикет временно закрываем и переносим в отложенные задачи.

**Comment by Genenko-Svetlana** [comment]
Возвращаем в работу
