### ISSUE TITLE
Ошибка в ударении

### ISSUE THREAD

**Issue by danchistyakov** [sberdevices/salute-issues#87]
Где нашелся баг: в ассистенте;
Описание проблемы: неправильное ударение.
Проблема воспроизводится у других пользователей? да;
Дополнительная информация: ассистент говорит мышка-нОрушка, а надо мышка-норУшка.

**Comment by RulevAnton** [comment]
Завёл TTSQA-1214

**Comment by RulevAnton** [comment]
@DCStudioProjects Можете пока воспользоваться временным решением и вручную проставить ударение?
"мышка-нору'шка"

**Comment by danchistyakov** [comment]
Это не критично. И это http-запрос, думаете сработает?

**Comment by RulevAnton** [comment]
должно, если я правильно это представляю.
Можно ещё в закодированном виде в url передать:
%D0%BC%D1%8B%D1%88%D0%BA%D0%B0-%D0%BD%D0%BE%D1%80%D1%83'%D1%88%D0%BA%D0%B0

**Comment by RulevAnton** [comment]
Исправление поедет на прод сегодня в ночь.
