### ISSUE TITLE
сделать ссылку на номера телефонов и почты в сбер салют

### ISSUE THREAD

**Issue by kamnevtmb** [sberdevices/salute-issues#88]
реализовать ссылки, где присутствуют номера телефонов или почты.
по клику стандартное действие набор номера или открыть почтовую программу.

![Screenshot_20201202-072009_ ](https://user-images.githubusercontent.com/21268026/100828693-be61e400-3470-11eb-808a-e248c148ef1b.jpg)

**Comment by sdtestersd** [comment]
Сылку в тексте можно выполнить с помощью markdown
За основу вязт формат - https://commonmark.org/help/
Формат:
{
  "showText": "privet",  // (пока не приходит!) если пришло поле showText, игнорируем items
                          // поле showText будет приходить вместо текстовых сообщений
  "auto_listening": true, // (пока не приходит!) признак того, что нужно включить слушание автоматически после того как ассистент закончит озвучивать ответ,
                          // или сразу, если пришло expected_tts = false. По-умолчанию = false
  "items": [
    {
      "card": {}
    },
    {
      "card": {}
    },
    {
      "bubble": {
        "text": "Привет!"
      }
    },
    { 
      "bubble": {
        "text": "*Привет всем*",
        "markdown": true    // markdown=true - сигнал клиенту, о том что в поле text передана строка с разметкой markdown и клиент должен при отображении это учесть.
                            // markdown=false говорит о том, что клиент должен отобразить text как есть, без изменений.
      }
    },
    {
      "command": {}
    },
    {
      "command": {}
    },
    {
      "command": {}
    },
    {
      "card": {}
    },
    {
      "card": {}
    }
  ]
}

**Comment by kamnevtmb** [comment]
Понял, спасибо!

Вообще приложение не мое, но в своих буду использовать разметку)
