### ISSUE TITLE
[синтез речи] Проблема с синтезом речи слова "хаус" у Джой

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#89]
Джой плохо воспроизводит слово "хаус". При этом "Сбер" и "Афина" этой проблемы не имеют.
ударение не помогает, _say-as_ тоже.

Можно ли это исправить ?

**Comment by RulevAnton** [comment]
Завёл TTSQA-1222

**Comment by RulevAnton** [comment]
Временное решение, звучит лучше, если на синтез уходит: 
хауус

**Comment by subnetsRU** [comment]
Только это решение ломает синтез для "Сбер" и "Афина".

Пришлось реализовать для id:joy свою фразу, но как по мне что так, что эдак криво. Буду ждать исправления. Спасибо.

**Comment by RulevAnton** [comment]
Для исправления ждём выкатки новой модели синтеза, в которой Erm так не косячит.

**Comment by RulevAnton** [comment]
Исправлено, сегодня в ночь в прод.

**Comment by subnetsRU** [comment]
Проверил, подтверждаю, исправлено.
