### ISSUE TITLE
Засыпание смартфона при использовании Салюта.

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/salute-issues#9]
При использовании приложения Салют на android 9 (и некоторых других версиях, судя по всему те что менее 10-ой) смартфон засыпает прямо на ответе от ассистента. 
Приходится постоянно тыкать в экран, чтобы взаимодействовать со смартапами.

**Comment by Genenko-Svetlana** [comment]
По android есть баг, поправили в ноябрьской версии (ориентировочно 09.11.20)

**Comment by subnetsRU** [comment]
Ясно, спасибо. Ждём.

**Comment by subnetsRU** [comment]
Планы, по выпуску исправленной версии, не изменились ? Сегодня ?

**Comment by Genenko-Svetlana** [comment]
Проверьте завтра утром, пожалуйста. Ждём обратную связь от вас.

**Comment by subnetsRU** [comment]
Вижу что версия приложения изменилась. Теперь это 20.11.0.4145
Но увы и ах, проблема всё ещё актуальна. Мобильник по прежнему засыпает.

**Comment by Genenko-Svetlana** [comment]
Спасибо, продолжаем работать над проблемой.

**Comment by Genenko-Svetlana** [comment]
Срок реализации 26.11.2020

**Comment by Genenko-Svetlana** [comment]
Проверьте завтра, пожалуйста.

**Comment by subnetsRU** [comment]
Пока версия приложения на мобилке всё та же 20.11.0.4145. В маркете вижу тоже самое. Версия такая же с последней датой обновления 09.11.2020. 

Посмотрю вечером тогда.

**Comment by subnetsRU** [comment]
Ни вечером, ни сегодня с утра ситуация не изменилась. И в store и на мобильнике всё та же старая 20.11.0.4145.

Потому проверять пока нечего.

**Comment by talagaev** [comment]
@sdtestersd  в какой версии фикс?

**Comment by subnetsRU** [comment]
Проверяю обновилась ли версия каждое утро. Пока всё по прежнему. Версия всё ещё прежняя.

**Comment by sdtestersd** [comment]
в 20.11.1 поправили

**Comment by subnetsRU** [comment]
Ага, приложение обновилась. Мобильник не засыпает ! Ура ! Спасибо.
