### ISSUE TITLE
Голосовой ассистент иногда не отвечает

### ISSUE THREAD

**Issue by danchistyakov** [sberdevices/salute-issues#90]
Где нашелся баг: в ассистенте;
Описание проблемы: ассистент может просто не ответить;
Проблема воспроизводится у других пользователей? Да;
Дополнительная информация: непонятно почему это возникает.

**Comment by subnetsRU** [comment]
Да, бывает такое. Он тебя слушает, заканчиваешь говорить, иконка показывает, что он перестал тебя слушать, а ничего дальше не происходит и текста распознавания на экране нет.

Обычно само начинается, само проходит. Создаётся впечатление, либо запрос не доходит до ASR, либо её ответ не доходит обратно.

**Comment by vkycniichai** [comment]
@DCStudioProjects уточните, пожалуйста, воспроизвелось на боксе или в салюте?
Можете указать id девайса и время воспроизведения бага?

**Comment by danchistyakov** [comment]
В Салюте, если произнести какую-либо фразу потом, то диалог продолжается.

**Comment by subnetsRU** [comment]
Это же бывает и на боксе. Не только в салюте. В юзерском чате даже видео было на эту тему.

**Comment by danchistyakov** [comment]
Да, но из-за этого у меня не одобрили Ап, можете пока это убрать из критериев оценки или делать пока исключения?(

**Comment by vkycniichai** [comment]
@DCStudioProjects пришлите сюда, пожалуйста, message_id либо модель телефона (первое предпочтительнее).
В Салюте нужно зажать палцем фразу (либо ошибочную, но судя по всему, она не появилась вообще) либо рядом которые (по обе стороны) и нажать “Сообщить об ошибке” и там будет Message_id указан, вот он нужен.
+ желательно время воспроизведения бага

**Comment by danchistyakov** [comment]
До ошибки: -1;
После ошибки: 1607005246142.
Xiaomi MI 9.
Время 17:00 — 17:30.

**Comment by danchistyakov** [comment]
Могу сказать точнее: 
ID сообщения: -1;
Время 17:58;
Xiaomi MI 9.
Причём, сообщение просто не выводится, но если ответить фразой после этого, то сценарий продолжается.

**Comment by RulevAnton** [comment]
Если получилось достать id ошибочного сообщения, то оно значит вывелось на экран?

**Comment by RulevAnton** [comment]
То есть ASR получается распознал фразу перед отсутствующим ответом навыка? раз получилось ID достать.

**Comment by danchistyakov** [comment]
Да, я произнёс "Дальше" — и в ответ тишина. Может просто совпадение, но у меня в основном при переходе из экрана приветствия и при обращении к JS-условию 'random'.

**Comment by subnetsRU** [comment]
@DCStudioProjects
См. тикет #16

**Comment by danchistyakov** [comment]
Немного не то, вылетает через раз, но я заметил ещё одну закономерность, если быстро нажать сайджест, который ведёт на богатый сюжет (в первую секунду), то он как будто вылетает от перегрузки (ИМХО). Как будто он не успевает прописать пути сайджестов.

**Comment by vkycniichai** [comment]
@DCStudioProjects дальше решается в [16-м ](https://github.com/sberdevices/salute-issues/issues/16)

**Comment by danchistyakov** [comment]
Так у меня же может на любую команду не ответить.

**Comment by vkycniichai** [comment]
@DCStudioProjects по Вашему кейсу заведен баг на нашей стороне. id: SMSAIDE-1612
Сроки решения, ориентировочно - 10.12.2020, либо 15.12.2020
Навык одобрят сегодня

**Comment by danchistyakov** [comment]
Спасибо!

**Comment by danchistyakov** [comment]
@vkycniichai Добрый день, удалось ли решить проблему?

**Comment by vkycniichai** [comment]
@DCStudioProjects прошу прощения за долгий ответ.
Баг еще в работе. Сроки выпуска фикса немного сдвинулись. Актуальные: ночь с 17.12 на 18.12.
Как временное решение этого кейса могу предложить следующий вариант - в блок, где есть random, добавьте else.
У нас при таком способе все работает.
![атач](https://user-images.githubusercontent.com/73777988/102341075-86ef4d80-3fc1-11eb-904a-0a02179f5847.PNG)

**Comment by Genenko-Svetlana** [comment]
15.12 не успели, срок 18.12.2020

**Comment by danchistyakov** [comment]
> @DCStudioProjects прошу прощения за долгий ответ.
> Баг еще в работе. Сроки выпуска фикса немного сдвинулись. Актуальные: ночь с 17.12 на 18.12.
> Как временное решение этого кейса могу предложить следующий вариант - в блок, где есть random, добавьте else.
> У нас при таком способе все работает.
> ![атач](https://user-images.githubusercontent.com/73777988/102341075-86ef4d80-3fc1-11eb-904a-0a02179f5847.PNG)
> 
> 

@vkycniichai это прописать во всех блоках random? И в Камень, ножницы, бумага у меня нету блоков random.

**Comment by vkycniichai** [comment]
@DCStudioProjects баг как в КНБ воспроизводится при использовании RANDOM, и про этот баг мы знаем.
Если RANDOM в блоках нет, но при этом ответ от ассистента не возвращается, то баг, вероятно, не на нашей стороне.
Дополнительно возникает вопрос - как при отсутствии RANDOM происходит выбор в навыке?

**Comment by danchistyakov** [comment]
> @DCStudioProjects баг как в КНБ воспроизводится при использовании RANDOM, и про этот баг мы знаем.
> Если RANDOM в блоках нет, но при этом ответ от ассистента не возвращается, то баг, вероятно, не на нашей стороне.
> Дополнительно возникает вопрос - как при отсутствии RANDOM происходит выбор в навыке?

@vkycniichai Я сделал рандомизацию на стороне своего сервера через PHP, однако всё равно вылеты.

**Comment by vkycniichai** [comment]
@DCStudioProjects понял.
Как мы поняли при тесте, у нас проблема возникает при генерации числа 0.
То есть, если в _.random(10) - возвращает числа начиная от 0 до 10 - и в случае если у нас выпал 0 - сценарий ничего не делает и молчит.
Стоит попробовать заменить на использование функции _.random(1, 10).
Если реализовали на своей стороне рандомизацию, попробуйте сделать _.random(1, 3).

**Comment by danchistyakov** [comment]
> @DCStudioProjects понял.
> Как мы поняли при тесте, у нас проблема возникает при генерации числа 0.
> То есть, если в _.random(10) - возвращает числа начиная от 0 до 10 - и в случае если у нас выпал 0 - сценарий ничего не делает и молчит.
> Стоит попробовать заменить на использование функции _.random(1, 10).
> Если реализовали на своей стороне рандомизацию, попробуйте сделать _.random(1, 3).

@vkycniichai К сожалению, даже без нуля проблема осталась.

**Comment by danchistyakov** [comment]
Ну, как идут дела?

**Comment by vkycniichai** [comment]
@DCStudioProjects спасибо за длительное ожидание!
Есть проблема в обработке логике самого js кода. В js сравнение с значением "0" не является истинной. 
С нашей стороны зарегистрирован только этот баг. Возможно сложность все таки на стороне вашего приложения.
Дайте нам, по возможности, больше информации.

**Comment by danchistyakov** [comment]
> @DCStudioProjects спасибо за длительное ожидание!
> Есть проблема в обработке логике самого js кода. В js сравнение с значением "0" не является истинной.
> С нашей стороны зарегистрирован только этот баг. Возможно сложность все таки на стороне вашего приложения.
> Дайте нам, по возможности, больше информации.

Какую информацию Вам нужно предоставить? А можете по возможности скинуть контакты разработчиков, которые занимаются этой проблемой?

**Comment by vkycniichai** [comment]
Это не проблема с нашей стороны. Это специфика этого языка программирования.

**Comment by danchistyakov** [comment]
> Это не проблема с нашей стороны. Это специфика этого языка программирования.

А какую информацию предоставить-то?

**Comment by vkycniichai** [comment]
Это по возможности. Необходимо проверять структуру сценария в Graph, а также код на Вашем сервере.
Т.к. на данный момент то, что мы изначально идентифицировали как баг, им не оказалось. И мы можем предполагать только ошибку в самом сценарии.

**Comment by danchistyakov** [comment]
А Вы можете дать контакты в Телеграм разработчиков или Ваш - не хотелось бы выкладывать полный код здесь.

**Comment by vkycniichai** [comment]
Направьте на developer@sberdevices.ru

**Comment by vkycniichai** [comment]
@DCStudioProjects у Вас функция (https://tangerine.gq/cuefa/cuefa.php) возвращает от 0 до 2.
И в самом коде видно, что сравнение с нулем, про которое здесь писали выше, тоже осталось. Обратите внимание, в частности, на ноды: 10, 18. А в 21-й ноде "else" вообще отсутствует, как 0 был получен, так он и остался.
Еще раз отмечу, что в js сравнение с значением "0" не является истинной. Перепроверьте код и функции.
