### ISSUE TITLE
Добавление команды при обращении к смартапу

### ISSUE THREAD

**Issue by anisakharov** [sberdevices/salute-issues#91]
Просьба рассмотреть возможность передачи команды в смартап при первом обращении.
Есть смартап с названием "Плейлист Радио". Также работает активационная фраза "что в эфире". Подскажет пользователю, что звучит в прямом эфире радиостанции, отобразит плейлист или назовёт новинки эфира. 
Сейчас чтобы узнать песню необходимо совершить 2 запроса - сперва зайти в смартап, а потом спросить внутри командой. Для информационных смартапов было бы отлично сразу передавать команду.
Например, если бы ещё добавили слово "скажи" для запуска смартапа, то вот такая фраза:
[скажи] [что в эфире] [Европы Плюс] - сразу бы сообщала пользователю название песни, одной командой. Это гораздо быстрее.

**Comment by subnetsRU** [comment]
#15

**Comment by Genenko-Svetlana** [comment]
@kuznetsovn Никита, посмотри, пожалуйста. Это дубликат #15?

**Comment by vkycniichai** [comment]
Есть нюанс, но по сути - дубликат [#15](https://github.com/sberdevices/salute-issues/issues/15)
