### ISSUE TITLE
Ассистент плохо распознаёт фразу "к ОГЭ"

### ISSUE THREAD

**Issue by danchistyakov** [sberdevices/salute-issues#93]
Где нашелся баг: в ассистенте?
Описание проблемы: плохо распознаёт фразу "к ОГЭ" после вчерашнего (04.12) обновления.
Проблема воспроизводится у других пользователей? не знаю.
Дополнительная информация: может распознать фразу " к ОГЭ" как "Куга", "Coca", "Okko", "круга", "Кука".

**Comment by RulevAnton** [comment]
А фраза просто "к ОГЭ" без контекста?
СалютАпп?

**Comment by danchistyakov** [comment]
Да, Салют, "Запусти подготовка к ОГЭ".

**Comment by RulevAnton** [comment]
Распознавание мигает, иногда некорректно распознаёт, да.
Завёл дефект SDVOICECOR-454, но скорее всего станет лучше уже со следущей выкаткой обновлённой модели, которая будет скоро.
Ну плюс уже вот-вот можно будет для ключевых фраз запуска (да и где захочется) использовать asr_hints = words.
Тогда ОГЭ будет лучше распознаваться.

**Comment by RulevAnton** [comment]
@DCStudioProjects Напомните, пожалуйста, есть возможность использовать asr_hints?
https://developer.sberdevices.ru/docs/ru/platform_services/hints_usage

**Comment by danchistyakov** [comment]
> @DCStudioProjects Напомните, пожалуйста, есть возможность использовать asr_hints?
> https://developer.sberdevices.ru/docs/ru/platform_services/hints_usage

Уже распознавание восстановилось, всё работает, поэтому думаю некритично, если опять будут проблемы, то переоткроем тикет.

**Comment by RulevAnton** [comment]
Такие ключевые фразы можно покрыть хинтами, вы их можете использовать согласно инструкции https://developer.sberdevices.ru/docs/ru/platform_services/hints_usage
Или апп написан на graph?

**Comment by danchistyakov** [comment]
> Такие ключевые фразы можно покрыть хинтами, вы их можете использовать согласно инструкции https://developer.sberdevices.ru/docs/ru/platform_services/hints_usage
> Или апп написан на graph?

Написан на Graph
