### ISSUE TITLE
Иногда двоится список смартапов в хедере

### ISSUE THREAD

**Issue by danchistyakov** [sberdevices/salute-issues#94]
Где нашелся баг: в инструментах;
Описание проблемы: Иногда двоится список смартапов в хедере;
Проблема воспроизводится у других пользователей? не знаю;

**Comment by xoxulin** [comment]
Без скриншотов невозможно понять, о чем идет речь. Снабдите скриншотами, пометьте стрелками, что вы имеете ввиду.

**Comment by Genenko-Svetlana** [comment]
@DCStudioProjects в связи с отсутствием комментариев тикет закрываем.
