### ISSUE TITLE
нет произношения слова "площадь"

### ISSUE THREAD

**Issue by kamnevtmb** [sberdevices/salute-issues#95]
**Где нашелся баг**: Graph, API
**Описание проблемы**: глотается слово "площадь", любой из персонажей отказывается произносить это слово.
**Проблема воспроизводится у других пользователей?** да.
**Дополнительная информация**: нет

**Comment by subnetsRU** [comment]
Присоединяюсь.
```
"pronounceText": "Какая площадь помещения?"
```
Произносит как "Какая помещения". 
```
"pronounceText": "площадь квартиры",
```
Произносит просто "квартиры".

Но при этом текст "Красная площадь" произносит без проблем.

**Comment by kamnevtmb** [comment]
> Присоединяюсь.
> 
> ```
> "pronounceText": "Какая площадь помещения?"
> ```
> 
> Произносит как "Какая помещения".
> 
> ```
> "pronounceText": "площадь квартиры",
> ```
> 
> Произносит просто "квартиры".
> 
> Но при этом текст "Красная площадь" произносит без проблем.

да, спасибо, забыл указать полную фразу

**Comment by RulevAnton** [comment]
Завёл TTSQA-1238, постараемся успеть в след релиз (пара недель).

**Comment by RulevAnton** [comment]
Исправлено, в ПРОД появится с пятницы на субботу.

**Comment by Genenko-Svetlana** [comment]
@kamnevtmb @subnetsRU проверяйте, пожалуйста, исправление.

**Comment by subnetsRU** [comment]
Проверил. Заработало. Теперь эти фразы произносятся полностью.
