### ISSUE TITLE
Ассистент может не ответить ВНЕ зависимости от введённой фразы

### ISSUE THREAD

**Issue by danchistyakov** [sberdevices/salute-issues#96]
Где нашелся баг: в ассистенте;
Описание проблемы: ассистент может не ответить ВНЕ зависимости от введённой фразы;
Проблема воспроизводится у других пользователей? Да;
Дополнительная информация: есть Ап, в котором это происходит очень часто.

**Comment by Genenko-Svetlana** [comment]
Дубликат #90

**Comment by talagaev** [comment]
а можете прислать MID чтобы мы посмотрели логи, какая система не ответила

**Comment by vkycniichai** [comment]
@talagaev 
"Могу сказать точнее:
ID сообщения: -1;
Время 17:58;
Xiaomi MI 9.
Причём, сообщение просто не выводится, но если ответить фразой после этого, то сценарий продолжается."

По этому кейсу баг есть SMSAIDE-1612

**Comment by vkycniichai** [comment]
Продолжаем в [90](https://github.com/sberdevices/salute-issues/issues/90)
