### ISSUE TITLE
В мобильной версии Studio если навык уже запущен, то по-прежнему висит статус "в разработке"

### ISSUE THREAD

**Issue by danchistyakov** [sberdevices/salute-issues#97]
Где нашелся баг: в инструментах;
Описание проблемы: в мобильной версии Studio если навык уже запущен, то по-прежнему висит статус "в разработке";
Проблема воспроизводится у других пользователей? Не знаю;

**Comment by xoxulin** [comment]
Обратим внимание, но не с самым высоким приоритетом.

**Comment by danchistyakov** [comment]
Ок

**Comment by Genenko-Svetlana** [comment]
@xoxulin  Алексей, есть новая информация?

**Comment by Genenko-Svetlana** [comment]
@DCStudioProjects  
см. https://github.com/sberdevices/salute-issues/issues/103
Нужно попробовать в мобильной версии переключиться на “опубликованную версию“, то по ней можно будет увидеть статус опубликованной версии “Работает”.
А статус “в разработке” относится к параллельной версии смартапа - к черновику. 2 версии существуют одновременно и между ними можно переключаться.
