### ISSUE TITLE
добавить функционал для отладки приложений которые создаются целиком на SmartApp API

### ISSUE THREAD

**Issue by exitoso** [sberdevices/salute-issues#98]
**Где пригодится фича**: на сайте
**Описание фичи**: облегчит отладку приложений которые создаются целиком на SmartApp API
**Дополнительная информация**: 
Мои предложения:
1. Лог запросов и ответов
2. Коды ошибок
3. Валидатор json который уходит с сервера в Салют

**Comment by xoxulin** [comment]
Это есть в наших планах, и уже довольно скоро. Stay tuned!

**Comment by Genenko-Svetlana** [comment]
@xoxulin  есть более точный срок? Квартал?

**Comment by Genenko-Svetlana** [comment]
Срок реализации - февраль, 21

**Comment by Genenko-Svetlana** [comment]
Реализовано.
Предложения по доработке можно оставлять в тикете https://github.com/sberdevices/salute-issues/issues/157
