### ISSUE TITLE
Вместо окна тестирования сценария пустота

### ISSUE THREAD

**Issue by danchistyakov** [sberdevices/salute-issues#99]
**Где нашелся баг**: в инструментах;
**Описание проблемы**: вместо окна тестирования сценария пустота;
**Проблема воспроизводится у других пользователей?** Варианты: не знаю;
**Дополнительная информация**: могу предоставить информацию по Апу.

**Comment by asmalakhov-sberdevices** [comment]
@DCStudioProjects проблема сохранятся?
уточни, пожалуйста кейс. Проблема в графе, верно?
1. Открыт редактор сценария в Graph
2. Нажали тестировать 
Пропало все окно графа или только тестовый виджет пустой?

До этого тестовый виджет работал? что-то сделали, перед тем, как начала возникать проблема?

**Comment by danchistyakov** [comment]
Переписку продолжили в Телеграме.

**Comment by Genenko-Svetlana** [comment]
@DCStudioProjects  тикет можно закрыть?

**Comment by danchistyakov** [comment]
Не знаю как у вас устроено, проблема ещё не решена, но переписка в Телеграме.

**Comment by Genenko-Svetlana** [comment]
Нет, тикет остается открытым до решения проблемы.
Срок реализации 31.01.2021.

**Comment by asmalakhov-sberdevices** [comment]
@DCStudioProjects подскажите, пожалуйста, проблема актуальна? была исправлена схожая проблема и после исправление, указанное поведение воспроизвести не смогли.
